'use strict';
const byId=id=>document.getElementById(id);
function associateAuthLabels(){for(const label of document.querySelectorAll('label:not([for])')){const control=label.nextElementSibling?.matches?.('input,select,textarea')?label.nextElementSibling:label.parentElement?.querySelector('input,select,textarea');if(control?.id)label.htmlFor=control.id}}
function enhanceAuthPasswords(){for(const input of document.querySelectorAll('input[type="password"]')){if(input.dataset.passwordToggle)continue;input.dataset.passwordToggle='1';const wrapper=document.createElement('div'),button=document.createElement('button');wrapper.className='passwordInput';input.before(wrapper);wrapper.append(input);button.type='button';button.className='passwordToggle';button.textContent='Göster';button.setAttribute('aria-label','Şifreyi göster');button.addEventListener('click',()=>{const visible=input.type==='text';input.type=visible?'password':'text';button.textContent=visible?'Göster':'Gizle';button.setAttribute('aria-label',visible?'Şifreyi göster':'Şifreyi gizle')});wrapper.append(button)}}
async function jsonFetch(url,options){const response=await fetch(url,options),data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'İşlem başarısız');return data}
async function forgot(){const button=byId('send');button.disabled=true;byId('message').textContent='İstek gönderiliyor…';try{const data=await jsonFetch('/api/auth/forgot-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:byId('email').value})});byId('message').className='standaloneMessage success';byId('message').textContent=data.message}catch(error){byId('message').className='standaloneMessage error';byId('message').textContent=error.message}finally{button.disabled=false}}
async function resetInit(){const token=new URLSearchParams(location.search).get('token')||'';try{const data=await jsonFetch('/api/auth/reset-password/validate?token='+encodeURIComponent(token));if(!data.valid)throw Error('Bu şifre yenileme bağlantısının süresi dolmuş veya geçersiz.');byId('intro').textContent='Hesabın için güçlü ve yeni bir şifre belirle.';byId('form').classList.remove('hide')}catch(error){byId('intro').textContent=error.message;byId('message').className='standaloneMessage error'}byId('save').addEventListener('click',async()=>{const password=byId('password').value,confirm=byId('confirm').value;if(password.length<10){byId('message').textContent='Şifre en az 10 karakter olmalı';return}if(password!==confirm){byId('message').textContent='Şifreler eşleşmiyor';return}try{await jsonFetch('/api/auth/reset-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,password})});byId('form').classList.add('hide');byId('intro').textContent='Şifren başarıyla yenilendi.';byId('message').className='standaloneMessage success';byId('message').textContent='Artık yeni şifrenle giriş yapabilirsin.'}catch(error){byId('message').className='standaloneMessage error';byId('message').textContent=error.message}})}
async function verifyEmail(){const token=new URLSearchParams(location.search).get('token')||'';try{const data=await jsonFetch('/api/auth/verify-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});byId('message').className='standaloneMessage success';byId('message').textContent=data.message||'E-posta adresin doğrulandı.'}catch(error){byId('message').className='standaloneMessage error';byId('message').textContent=error.message}}
enhanceAuthPasswords();associateAuthLabels();if(byId('send'))byId('send').addEventListener('click',forgot);if(byId('save'))resetInit();if(document.body.dataset.page==='verify-email')verifyEmail();
