const express=require('express');
const path=require('path');
const cookieParser=require('cookie-parser');
const helmet=require('helmet');
const rateLimit=require('express-rate-limit');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const multer=require('multer');
const QRCode=require('qrcode');
const {Pool}=require('pg');

const app=express();
const PORT=process.env.PORT||3000;
const JWT_SECRET=process.env.JWT_SECRET||'DEVELOPMENT_ONLY_CHANGE_ME';
const DATABASE_URL=process.env.DATABASE_URL;
if(!DATABASE_URL){console.error('DATABASE_URL tanımlı değil.');process.exit(1)}
const pool=new Pool({connectionString:DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:1}});

app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:false}));
app.use(express.json({limit:'700kb'}));
app.use(cookieParser());
app.use(express.static(path.join(__dirname,'public'),{maxAge:0,etag:true,setHeaders:res=>res.setHeader('Cache-Control','no-store, max-age=0')}));
app.use('/api/auth',rateLimit({windowMs:15*60*1000,max:60,standardHeaders:true,legacyHeaders:false}));

const clean=s=>String(s??'').trim();
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const nil=v=>clean(v)||null;
const emailOk=s=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
const companyRoles=['owner','manager','technician','operator','viewer'];
const roleLabel={owner:'Firma Sahibi',manager:'Yönetici',technician:'Teknisyen',operator:'Operatör',viewer:'Görüntüleyici'};
async function q(text,params=[]){return pool.query(text,params)}
function sign(u){return jwt.sign({id:u.id,email:u.email,name:u.name,role:u.role},JWT_SECRET,{expiresIn:'7d'})}
function setCookie(res,t){res.cookie('dm_token',t,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:7*24*60*60*1000})}
function auth(req,res,next){const t=req.cookies.dm_token;if(!t)return res.status(401).json({error:'Giriş gerekli'});try{req.user=jwt.verify(t,JWT_SECRET);next()}catch{res.clearCookie('dm_token');res.status(401).json({error:'Oturum geçersiz'})}}
function siteAdmin(req,res,next){if(req.user?.role!=='admin')return res.status(403).json({error:'Site yöneticisi yetkisi gerekli'});next()}
function permit(...roles){return(req,res,next)=>{if(req.user?.role==='admin'||roles.includes(req.company?.role))return next();return res.status(403).json({error:`Bu işlem için yetkiniz yok (${roleLabel[req.company?.role]||'rol'})`})}}
function healthScore(m){let s=100;if(m.status==='Arızalı')s-=35;else if(m.status==='Bakımda')s-=15;else if(m.status==='Devre dışı')s-=25;if(m.criticality==='Kritik')s-=5;s-=Math.min(24,num(m.open_faults)*6);s-=Math.min(16,num(m.critical_faults)*8);s-=Math.min(21,num(m.overdue_maintenance)*7);s-=Math.min(9,num(m.due30)*3);if(num(m.faults90)>=3)s-=8;if(m.last_maintenance_date){const days=(Date.now()-new Date(m.last_maintenance_date).getTime())/86400000;if(days>180)s-=10}else if(num(m.hours)>250)s-=8;return Math.max(5,Math.min(100,Math.round(s)))}
function slug(s){return clean(s).toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ş/g,'s').replace(/ç/g,'c').replace(/ö/g,'o').replace(/ü/g,'u').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,40)||'firma'}
async function addCols(table,cols){for(const c of cols)await q(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS ${c}`)}
async function uniqueCompanyCode(name){const base=slug(name);for(let i=0;i<20;i++){const code=(base+'-'+Math.random().toString(36).slice(2,7)).slice(0,60);if(!(await q('SELECT 1 FROM companies WHERE code=$1',[code])).rows.length)return code}return base+'-'+Date.now()}
async function createPersonalCompany(user){const name=`${user.name} Atölyesi`,code=await uniqueCompanyCode(name);const c=(await q('INSERT INTO companies(name,code,owner_user_id) VALUES($1,$2,$3) RETURNING *',[name,code,user.id])).rows[0];await q("INSERT INTO company_members(company_id,user_id,role) VALUES($1,$2,'owner') ON CONFLICT(company_id,user_id) DO UPDATE SET role='owner',is_active=true",[c.id,user.id]);await q('UPDATE users SET active_company_id=$1 WHERE id=$2',[c.id,user.id]);return c}
async function ensureCompanyForUser(userId){let u=(await q('SELECT id,name,active_company_id FROM users WHERE id=$1',[userId])).rows[0];if(!u)return null;let m=(await q(`SELECT c.id,c.name,c.code,cm.role FROM company_members cm JOIN companies c ON c.id=cm.company_id WHERE cm.user_id=$1 AND cm.is_active=true AND c.id=$2`,[userId,u.active_company_id||0])).rows[0];if(!m)m=(await q(`SELECT c.id,c.name,c.code,cm.role FROM company_members cm JOIN companies c ON c.id=cm.company_id WHERE cm.user_id=$1 AND cm.is_active=true ORDER BY cm.id LIMIT 1`,[userId])).rows[0];if(!m){const c=await createPersonalCompany(u);m={...c,role:'owner'}}if(Number(u.active_company_id)!==Number(m.id))await q('UPDATE users SET active_company_id=$1 WHERE id=$2',[m.id,userId]);return m}
async function companyCtx(req,res,next){try{const c=await ensureCompanyForUser(req.user.id);if(!c)return res.status(403).json({error:'Aktif firma bulunamadı'});req.company=c;next()}catch(e){next(e)}}
async function ownMachine(id,companyId){return (await q('SELECT id FROM machines WHERE id=$1 AND company_id=$2',[id,companyId])).rows[0]}
async function audit(req,action,entityType,entityId,details={}){try{await q('INSERT INTO audit_log(company_id,user_id,action,entity_type,entity_id,details) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[req.company?.id||null,req.user?.id||null,action,entityType,entityId||null,JSON.stringify(details||{})])}catch(e){console.warn('audit:',e.message)}}
function validDateMonth(v){return /^\d{4}-\d{2}$/.test(String(v||''))?String(v):new Date().toISOString().slice(0,7)}

async function initDb(){
 await q(`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(200) UNIQUE NOT NULL,password_hash TEXT NOT NULL,role VARCHAR(20) NOT NULL DEFAULT 'user',is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS companies(id BIGSERIAL PRIMARY KEY,name VARCHAR(180) NOT NULL,code VARCHAR(80) UNIQUE NOT NULL,owner_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS company_members(id BIGSERIAL PRIMARY KEY,company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,role VARCHAR(30) NOT NULL DEFAULT 'viewer',is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(company_id,user_id))`);
 await addCols('users',['active_company_id BIGINT']);
 await q(`CREATE TABLE IF NOT EXISTS machines(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name VARCHAR(160) NOT NULL,model VARCHAR(160) DEFAULT '',hours NUMERIC(12,1) DEFAULT 0,criticality VARCHAR(30) DEFAULT 'Normal',serial_no VARCHAR(120) DEFAULT '',note TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols('machines',["company_id BIGINT","manufacturer VARCHAR(160) DEFAULT ''","category VARCHAR(100) DEFAULT ''","location VARCHAR(180) DEFAULT ''","status VARCHAR(30) DEFAULT 'Çalışıyor'","power_kw NUMERIC(10,2) DEFAULT 0","year INTEGER","last_maintenance_date DATE","next_maintenance_date DATE","lubricant VARCHAR(180) DEFAULT ''","bearing_info TEXT DEFAULT ''","belt_info TEXT DEFAULT ''","motor_info TEXT DEFAULT ''"]);
 await q(`CREATE TABLE IF NOT EXISTS maintenance(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,machine_id BIGINT REFERENCES machines(id) ON DELETE CASCADE,task VARCHAR(220) NOT NULL,due_date DATE NOT NULL,priority VARCHAR(30) DEFAULT 'Normal',status VARCHAR(20) DEFAULT 'open',note TEXT DEFAULT '',completed_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols('maintenance',["company_id BIGINT","maintenance_type VARCHAR(50) DEFAULT 'Periyodik'","frequency VARCHAR(80) DEFAULT ''","technician VARCHAR(160) DEFAULT ''","technician_user_id BIGINT","parts_used TEXT DEFAULT ''","cost NUMERIC(12,2) DEFAULT 0","duration_min INTEGER DEFAULT 0","meter_hours NUMERIC(12,1) DEFAULT 0"]);
 await q(`CREATE TABLE IF NOT EXISTS faults(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,machine_id BIGINT REFERENCES machines(id) ON DELETE SET NULL,system VARCHAR(40),symptom VARCHAR(180) NOT NULL,measurements JSONB DEFAULT '{}'::jsonb,note TEXT DEFAULT '',diagnosis TEXT DEFAULT '',status VARCHAR(20) DEFAULT 'open',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols('faults',["company_id BIGINT","severity VARCHAR(30) DEFAULT 'Orta'","root_cause TEXT DEFAULT ''","action_taken TEXT DEFAULT ''","downtime_min INTEGER DEFAULT 0","closed_at TIMESTAMPTZ"]);
 await q(`CREATE TABLE IF NOT EXISTS parts(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name VARCHAR(180) NOT NULL,part_code VARCHAR(120) DEFAULT '',category VARCHAR(80) DEFAULT '',quantity NUMERIC(12,2) DEFAULT 0,min_quantity NUMERIC(12,2) DEFAULT 0,unit VARCHAR(30) DEFAULT 'adet',location VARCHAR(140) DEFAULT '',supplier VARCHAR(180) DEFAULT '',unit_cost NUMERIC(12,2) DEFAULT 0,note TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols('parts',['company_id BIGINT']);
 await q(`CREATE TABLE IF NOT EXISTS favorites(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,article_key VARCHAR(180) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,article_key))`);
 await q(`CREATE TABLE IF NOT EXISTS calc_history(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,tool VARCHAR(120) NOT NULL,input_data JSONB DEFAULT '{}'::jsonb,result TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS work_orders(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,machine_id BIGINT REFERENCES machines(id) ON DELETE SET NULL,title VARCHAR(220) NOT NULL,description TEXT DEFAULT '',priority VARCHAR(30) DEFAULT 'Normal',status VARCHAR(30) DEFAULT 'open',assigned_to VARCHAR(160) DEFAULT '',due_date DATE,started_at TIMESTAMPTZ,completed_at TIMESTAMPTZ,parts_used TEXT DEFAULT '',cost NUMERIC(12,2) DEFAULT 0,downtime_min INTEGER DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols('work_orders',['company_id BIGINT','assigned_user_id BIGINT']);
 await q(`CREATE TABLE IF NOT EXISTS machine_measurements(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,machine_id BIGINT NOT NULL REFERENCES machines(id) ON DELETE CASCADE,temperature NUMERIC(10,2),pressure NUMERIC(10,2),current_amp NUMERIC(10,2),voltage NUMERIC(10,2),vibration NUMERIC(10,3),rpm NUMERIC(12,1),note TEXT DEFAULT '',measured_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols('machine_measurements',['company_id BIGINT']);
 await q(`CREATE TABLE IF NOT EXISTS attachments(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,machine_id BIGINT NOT NULL REFERENCES machines(id) ON DELETE CASCADE,file_name VARCHAR(240) NOT NULL,mime_type VARCHAR(120) NOT NULL,size_bytes INTEGER NOT NULL,file_data BYTEA NOT NULL,caption VARCHAR(240) DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols('attachments',['company_id BIGINT']);
 await q(`CREATE TABLE IF NOT EXISTS audit_log(id BIGSERIAL PRIMARY KEY,company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,action VARCHAR(80) NOT NULL,entity_type VARCHAR(80) NOT NULL,entity_id BIGINT,details JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);

 const users=(await q('SELECT id,name,active_company_id FROM users ORDER BY id')).rows;
 for(const u of users)await ensureCompanyForUser(u.id);
 const shared=['machines','maintenance','faults','parts','work_orders','machine_measurements','attachments'];
 for(const t of shared)await q(`UPDATE ${t} x SET company_id=u.active_company_id FROM users u WHERE x.user_id=u.id AND x.company_id IS NULL`);
 await q('CREATE INDEX IF NOT EXISTS idx_machines_company ON machines(company_id)');
 await q('CREATE INDEX IF NOT EXISTS idx_maintenance_company_due ON maintenance(company_id,due_date)');
 await q('CREATE INDEX IF NOT EXISTS idx_faults_company_created ON faults(company_id,created_at)');
 await q('CREATE INDEX IF NOT EXISTS idx_work_company_due ON work_orders(company_id,due_date)');
 await q('CREATE INDEX IF NOT EXISTS idx_parts_company ON parts(company_id)');

 const ae=clean(process.env.ADMIN_EMAIL).toLowerCase(),ap=clean(process.env.ADMIN_PASSWORD);
 if(ae&&ap){const f=await q('SELECT id,name FROM users WHERE email=$1',[ae]);if(!f.rows.length){const h=await bcrypt.hash(ap,12);const u=(await q("INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,'admin') RETURNING id,name",[process.env.ADMIN_NAME||'Site Yöneticisi',ae,h])).rows[0];await createPersonalCompany(u)}else{await q("UPDATE users SET role='admin' WHERE email=$1",[ae]);await ensureCompanyForUser(f.rows[0].id)}}
}

// AUTH
app.post('/api/auth/register',async(req,res,next)=>{try{const name=clean(req.body.name),email=clean(req.body.email).toLowerCase(),password=String(req.body.password||'');if(name.length<2)return res.status(400).json({error:'Ad soyad gerekli'});if(!emailOk(email))return res.status(400).json({error:'Geçerli e-posta gir'});if(password.length<8)return res.status(400).json({error:'Şifre en az 8 karakter olmalı'});const h=await bcrypt.hash(password,12);const u=(await q('INSERT INTO users(name,email,password_hash) VALUES($1,$2,$3) RETURNING id,name,email,role,is_active,created_at',[name,email,h])).rows[0];await createPersonalCompany(u);setCookie(res,sign(u));res.json({user:u})}catch(e){if(e.code==='23505')return res.status(409).json({error:'Bu e-posta zaten kayıtlı'});next(e)}});
app.post('/api/auth/login',async(req,res,next)=>{try{const email=clean(req.body.email).toLowerCase(),password=String(req.body.password||'');const u=(await q('SELECT * FROM users WHERE email=$1',[email])).rows[0];if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'E-posta veya şifre hatalı'});if(!u.is_active)return res.status(403).json({error:'Hesabınız devre dışı'});await ensureCompanyForUser(u.id);setCookie(res,sign(u));res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role,is_active:u.is_active}})}catch(e){next(e)}});
app.post('/api/auth/logout',(req,res)=>{res.clearCookie('dm_token');res.json({ok:true})});
app.get('/api/auth/me',auth,companyCtx,async(req,res)=>{const u=(await q('SELECT id,name,email,role,is_active,created_at,active_company_id FROM users WHERE id=$1',[req.user.id])).rows[0];if(!u?.is_active)return res.status(403).json({error:'Hesap devre dışı'});res.json({user:{...u,company:req.company,company_role:req.company.role}})});

// COMPANY / TEAM
app.get('/api/company',auth,companyCtx,async(req,res)=>{const companies=(await q(`SELECT c.id,c.name,c.code,cm.role,cm.is_active FROM company_members cm JOIN companies c ON c.id=cm.company_id WHERE cm.user_id=$1 AND cm.is_active=true ORDER BY c.name`,[req.user.id])).rows;const members=(await q(`SELECT u.id,u.name,u.email,cm.role,cm.is_active,cm.created_at FROM company_members cm JOIN users u ON u.id=cm.user_id WHERE cm.company_id=$1 ORDER BY CASE cm.role WHEN 'owner' THEN 0 WHEN 'manager' THEN 1 WHEN 'technician' THEN 2 WHEN 'operator' THEN 3 ELSE 4 END,u.name`,[req.company.id])).rows;res.json({active:req.company,companies,members,permissions:{canManageCompany:req.user.role==='admin'||['owner','manager'].includes(req.company.role),canManageRoles:req.user.role==='admin'||req.company.role==='owner',canEditAssets:req.user.role==='admin'||['owner','manager'].includes(req.company.role),canWork:req.user.role==='admin'||['owner','manager','technician'].includes(req.company.role),canOperate:req.user.role==='admin'||['owner','manager','technician','operator'].includes(req.company.role)}})});
app.post('/api/company',auth,async(req,res,next)=>{try{const name=clean(req.body.name);if(name.length<2)return res.status(400).json({error:'Firma adı gerekli'});const code=await uniqueCompanyCode(name);const c=(await q('INSERT INTO companies(name,code,owner_user_id) VALUES($1,$2,$3) RETURNING *',[name,code,req.user.id])).rows[0];await q("INSERT INTO company_members(company_id,user_id,role) VALUES($1,$2,'owner')",[c.id,req.user.id]);await q('UPDATE users SET active_company_id=$1 WHERE id=$2',[c.id,req.user.id]);res.json(c)}catch(e){next(e)}});
app.post('/api/company/switch/:id',auth,async(req,res)=>{const m=(await q(`SELECT c.id,c.name,c.code,cm.role FROM company_members cm JOIN companies c ON c.id=cm.company_id WHERE cm.user_id=$1 AND cm.company_id=$2 AND cm.is_active=true`,[req.user.id,req.params.id])).rows[0];if(!m)return res.status(403).json({error:'Bu firmaya erişiminiz yok'});await q('UPDATE users SET active_company_id=$1 WHERE id=$2',[m.id,req.user.id]);res.json(m)});
app.patch('/api/company',auth,companyCtx,permit('owner','manager'),async(req,res)=>{const name=clean(req.body.name);if(name.length<2)return res.status(400).json({error:'Firma adı gerekli'});const c=(await q('UPDATE companies SET name=$1 WHERE id=$2 RETURNING id,name,code',[name,req.company.id])).rows[0];await audit(req,'update','company',req.company.id,{name});res.json(c)});
app.post('/api/company/members',auth,companyCtx,permit('owner','manager'),async(req,res)=>{const email=clean(req.body.email).toLowerCase(),role=companyRoles.includes(req.body.role)?req.body.role:'viewer';if(role==='owner'&&req.company.role!=='owner'&&req.user.role!=='admin')return res.status(403).json({error:'Sadece firma sahibi yeni sahip atayabilir'});const u=(await q('SELECT id,name,email,is_active FROM users WHERE email=$1',[email])).rows[0];if(!u)return res.status(404).json({error:'Bu e-posta ile kayıtlı kullanıcı yok. Önce siteye kayıt olması gerekir.'});if(!u.is_active)return res.status(400).json({error:'Bu kullanıcı pasif'});await q(`INSERT INTO company_members(company_id,user_id,role,is_active) VALUES($1,$2,$3,true) ON CONFLICT(company_id,user_id) DO UPDATE SET role=EXCLUDED.role,is_active=true`,[req.company.id,u.id,role]);await audit(req,'member_add','company_member',u.id,{email,role});res.json({ok:true,user:u,role})});
app.patch('/api/company/members/:userId',auth,companyCtx,permit('owner'),async(req,res)=>{if(Number(req.params.userId)===Number(req.user.id)&&req.body.role!=='owner')return res.status(400).json({error:'Kendi firma sahibi rolünüzü kaldıramazsınız'});const role=companyRoles.includes(req.body.role)?req.body.role:'viewer';await q('UPDATE company_members SET role=$1,is_active=true WHERE company_id=$2 AND user_id=$3',[role,req.company.id,req.params.userId]);await audit(req,'member_role','company_member',req.params.userId,{role});res.json({ok:true})});
app.delete('/api/company/members/:userId',auth,companyCtx,permit('owner','manager'),async(req,res)=>{if(Number(req.params.userId)===Number(req.user.id))return res.status(400).json({error:'Kendinizi aktif firmadan çıkaramazsınız'});const target=(await q('SELECT role FROM company_members WHERE company_id=$1 AND user_id=$2',[req.company.id,req.params.userId])).rows[0];if(target?.role==='owner'&&req.company.role!=='owner'&&req.user.role!=='admin')return res.status(403).json({error:'Firma sahibi kaldırılamaz'});await q('UPDATE company_members SET is_active=false WHERE company_id=$1 AND user_id=$2',[req.company.id,req.params.userId]);await audit(req,'member_remove','company_member',req.params.userId,{});res.json({ok:true})});
app.get('/api/audit',auth,companyCtx,async(req,res)=>{const limit=Math.min(200,Math.max(10,num(req.query.limit,60)));res.json((await q(`SELECT a.*,u.name user_name FROM audit_log a LEFT JOIN users u ON u.id=a.user_id WHERE a.company_id=$1 ORDER BY a.id DESC LIMIT $2`,[req.company.id,limit])).rows)});

// MACHINES
const machineStats=`(SELECT COUNT(*) FROM faults f WHERE f.machine_id=m.id AND f.company_id=m.company_id AND f.status='open')::int open_faults,(SELECT COUNT(*) FROM faults f WHERE f.machine_id=m.id AND f.company_id=m.company_id AND f.status='open' AND f.severity='Kritik')::int critical_faults,(SELECT COUNT(*) FROM faults f WHERE f.machine_id=m.id AND f.company_id=m.company_id AND f.created_at>=NOW()-INTERVAL '90 days')::int faults90,(SELECT COUNT(*) FROM maintenance x WHERE x.machine_id=m.id AND x.company_id=m.company_id AND x.status='open' AND x.due_date<CURRENT_DATE)::int overdue_maintenance,(SELECT COUNT(*) FROM maintenance x WHERE x.machine_id=m.id AND x.company_id=m.company_id AND x.status='open' AND x.due_date BETWEEN CURRENT_DATE AND CURRENT_DATE+30)::int due30`;
app.get('/api/machines',auth,companyCtx,async(req,res)=>{const r=await q(`SELECT m.*,${machineStats} FROM machines m WHERE m.company_id=$1 ORDER BY m.id DESC`,[req.company.id]);res.json(r.rows.map(x=>({...x,health_score:healthScore(x)})))});
app.get('/api/machines/:id/detail',auth,companyCtx,async(req,res)=>{const m=(await q(`SELECT m.*,${machineStats} FROM machines m WHERE m.id=$1 AND m.company_id=$2`,[req.params.id,req.company.id])).rows[0];if(!m)return res.status(404).json({error:'Makine bulunamadı'});const [ma,f,w,ms,a]=await Promise.all([q('SELECT * FROM maintenance WHERE machine_id=$1 AND company_id=$2 ORDER BY due_date DESC,id DESC LIMIT 80',[m.id,req.company.id]),q('SELECT * FROM faults WHERE machine_id=$1 AND company_id=$2 ORDER BY id DESC LIMIT 80',[m.id,req.company.id]),q('SELECT * FROM work_orders WHERE machine_id=$1 AND company_id=$2 ORDER BY id DESC LIMIT 80',[m.id,req.company.id]),q('SELECT * FROM machine_measurements WHERE machine_id=$1 AND company_id=$2 ORDER BY measured_at DESC LIMIT 120',[m.id,req.company.id]),q('SELECT id,file_name,mime_type,size_bytes,caption,created_at FROM attachments WHERE machine_id=$1 AND company_id=$2 ORDER BY id DESC LIMIT 80',[m.id,req.company.id])]);m.health_score=healthScore(m);res.json({machine:m,maintenance:ma.rows,faults:f.rows,workOrders:w.rows,measurements:ms.rows.reverse(),attachments:a.rows})});
app.post('/api/machines',auth,companyCtx,permit('owner','manager'),async(req,res)=>{const b=req.body;if(!clean(b.name))return res.status(400).json({error:'Makine adı gerekli'});const r=await q(`INSERT INTO machines(user_id,company_id,name,manufacturer,model,category,serial_no,location,status,hours,power_kw,year,criticality,last_maintenance_date,next_maintenance_date,lubricant,bearing_info,belt_info,motor_info,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20) RETURNING *`,[req.user.id,req.company.id,clean(b.name),clean(b.manufacturer),clean(b.model),clean(b.category),clean(b.serial_no),clean(b.location),clean(b.status)||'Çalışıyor',num(b.hours),num(b.power_kw),b.year?parseInt(b.year,10):null,clean(b.criticality)||'Normal',nil(b.last_maintenance_date),nil(b.next_maintenance_date),clean(b.lubricant),clean(b.bearing_info),clean(b.belt_info),clean(b.motor_info),clean(b.note)]);await audit(req,'create','machine',r.rows[0].id,{name:r.rows[0].name});res.json(r.rows[0])});
app.put('/api/machines/:id',auth,companyCtx,permit('owner','manager'),async(req,res)=>{const b=req.body;const r=await q(`UPDATE machines SET name=$1,manufacturer=$2,model=$3,category=$4,serial_no=$5,location=$6,status=$7,hours=$8,power_kw=$9,year=$10,criticality=$11,last_maintenance_date=$12,next_maintenance_date=$13,lubricant=$14,bearing_info=$15,belt_info=$16,motor_info=$17,note=$18 WHERE id=$19 AND company_id=$20 RETURNING *`,[clean(b.name),clean(b.manufacturer),clean(b.model),clean(b.category),clean(b.serial_no),clean(b.location),clean(b.status)||'Çalışıyor',num(b.hours),num(b.power_kw),b.year?parseInt(b.year,10):null,clean(b.criticality)||'Normal',nil(b.last_maintenance_date),nil(b.next_maintenance_date),clean(b.lubricant),clean(b.bearing_info),clean(b.belt_info),clean(b.motor_info),clean(b.note),req.params.id,req.company.id]);if(!r.rows[0])return res.status(404).json({error:'Makine bulunamadı'});await audit(req,'update','machine',req.params.id,{name:r.rows[0].name});res.json(r.rows[0])});
app.delete('/api/machines/:id',auth,companyCtx,permit('owner','manager'),async(req,res)=>{const r=await q('DELETE FROM machines WHERE id=$1 AND company_id=$2 RETURNING id,name',[req.params.id,req.company.id]);if(r.rows[0])await audit(req,'delete','machine',r.rows[0].id,{name:r.rows[0].name});res.json({ok:true})});

// MAINTENANCE
app.get('/api/maintenance',auth,companyCtx,async(req,res)=>res.json((await q(`SELECT m.*,x.name machine_name,u.name technician_member_name FROM maintenance m LEFT JOIN machines x ON x.id=m.machine_id LEFT JOIN users u ON u.id=m.technician_user_id WHERE m.company_id=$1 ORDER BY CASE WHEN m.status='open' THEN 0 ELSE 1 END,m.due_date ASC,m.id DESC`,[req.company.id])).rows));
app.post('/api/maintenance',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{const b=req.body;if(!b.machine_id||!clean(b.task)||!b.due_date)return res.status(400).json({error:'Makine, görev ve tarih gerekli'});if(!(await ownMachine(b.machine_id,req.company.id)))return res.status(403).json({error:'Makine aktif firmaya ait değil'});const r=await q(`INSERT INTO maintenance(user_id,company_id,machine_id,task,due_date,priority,note,maintenance_type,frequency,technician,technician_user_id,parts_used,cost,duration_min,meter_hours) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`,[req.user.id,req.company.id,b.machine_id,clean(b.task),b.due_date,clean(b.priority)||'Normal',clean(b.note),clean(b.maintenance_type)||'Periyodik',clean(b.frequency),clean(b.technician),b.technician_user_id||null,clean(b.parts_used),num(b.cost),Math.round(num(b.duration_min)),num(b.meter_hours)]);await audit(req,'create','maintenance',r.rows[0].id,{task:r.rows[0].task});res.json(r.rows[0])});
app.patch('/api/maintenance/:id/status',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{const st=req.body.status==='done'?'done':'open';const r=await q(`UPDATE maintenance SET status=$1,completed_at=CASE WHEN $1='done' THEN NOW() ELSE NULL END WHERE id=$2 AND company_id=$3 RETURNING *`,[st,req.params.id,req.company.id]);if(!r.rows[0])return res.status(404).json({error:'Kayıt bulunamadı'});await audit(req,st==='done'?'complete':'reopen','maintenance',req.params.id,{task:r.rows[0].task});res.json(r.rows[0])});
app.delete('/api/maintenance/:id',auth,companyCtx,permit('owner','manager'),async(req,res)=>{const r=await q('DELETE FROM maintenance WHERE id=$1 AND company_id=$2 RETURNING id,task',[req.params.id,req.company.id]);if(r.rows[0])await audit(req,'delete','maintenance',r.rows[0].id,{task:r.rows[0].task});res.json({ok:true})});

// FAULTS
app.get('/api/faults',auth,companyCtx,async(req,res)=>res.json((await q(`SELECT f.*,x.name machine_name,u.name created_by_name FROM faults f LEFT JOIN machines x ON x.id=f.machine_id LEFT JOIN users u ON u.id=f.user_id WHERE f.company_id=$1 ORDER BY CASE WHEN f.status='open' THEN 0 ELSE 1 END,f.id DESC LIMIT 400`,[req.company.id])).rows));
app.post('/api/faults',auth,companyCtx,permit('owner','manager','technician','operator'),async(req,res)=>{const b=req.body;if(!clean(b.symptom))return res.status(400).json({error:'Belirti gerekli'});if(b.machine_id&&!(await ownMachine(b.machine_id,req.company.id)))return res.status(403).json({error:'Makine aktif firmaya ait değil'});const r=await q(`INSERT INTO faults(user_id,company_id,machine_id,system,symptom,measurements,note,diagnosis,severity,root_cause,action_taken,downtime_min) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10,$11,$12) RETURNING *`,[req.user.id,req.company.id,b.machine_id||null,clean(b.system),clean(b.symptom),JSON.stringify(b.measurements||{}),clean(b.note),clean(b.diagnosis),clean(b.severity)||'Orta',clean(b.root_cause),clean(b.action_taken),Math.round(num(b.downtime_min))]);await audit(req,'create','fault',r.rows[0].id,{symptom:r.rows[0].symptom,severity:r.rows[0].severity});res.json(r.rows[0])});
app.patch('/api/faults/:id/status',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{const st=req.body.status==='closed'?'closed':'open';const r=await q(`UPDATE faults SET status=$1,root_cause=COALESCE($2,root_cause),action_taken=COALESCE($3,action_taken),downtime_min=COALESCE($4,downtime_min),closed_at=CASE WHEN $1='closed' THEN NOW() ELSE NULL END WHERE id=$5 AND company_id=$6 RETURNING *`,[st,req.body.root_cause??null,req.body.action_taken??null,req.body.downtime_min===undefined?null:Math.round(num(req.body.downtime_min)),req.params.id,req.company.id]);if(!r.rows[0])return res.status(404).json({error:'Arıza kaydı bulunamadı'});await audit(req,st==='closed'?'close':'reopen','fault',req.params.id,{symptom:r.rows[0].symptom});res.json(r.rows[0])});
app.delete('/api/faults/:id',auth,companyCtx,permit('owner','manager'),async(req,res)=>{const r=await q('DELETE FROM faults WHERE id=$1 AND company_id=$2 RETURNING id,symptom',[req.params.id,req.company.id]);if(r.rows[0])await audit(req,'delete','fault',r.rows[0].id,{symptom:r.rows[0].symptom});res.json({ok:true})});

// PARTS
app.get('/api/parts',auth,companyCtx,async(req,res)=>res.json((await q('SELECT * FROM parts WHERE company_id=$1 ORDER BY name',[req.company.id])).rows));
app.post('/api/parts',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{const b=req.body;if(!clean(b.name))return res.status(400).json({error:'Parça adı gerekli'});const r=await q(`INSERT INTO parts(user_id,company_id,name,part_code,category,quantity,min_quantity,unit,location,supplier,unit_cost,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[req.user.id,req.company.id,clean(b.name),clean(b.part_code),clean(b.category),num(b.quantity),num(b.min_quantity),clean(b.unit)||'adet',clean(b.location),clean(b.supplier),num(b.unit_cost),clean(b.note)]);await audit(req,'create','part',r.rows[0].id,{name:r.rows[0].name});res.json(r.rows[0])});
app.put('/api/parts/:id',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{const b=req.body;const r=await q(`UPDATE parts SET name=$1,part_code=$2,category=$3,quantity=$4,min_quantity=$5,unit=$6,location=$7,supplier=$8,unit_cost=$9,note=$10 WHERE id=$11 AND company_id=$12 RETURNING *`,[clean(b.name),clean(b.part_code),clean(b.category),num(b.quantity),num(b.min_quantity),clean(b.unit)||'adet',clean(b.location),clean(b.supplier),num(b.unit_cost),clean(b.note),req.params.id,req.company.id]);if(!r.rows[0])return res.status(404).json({error:'Parça bulunamadı'});await audit(req,'update','part',req.params.id,{name:r.rows[0].name});res.json(r.rows[0])});
app.delete('/api/parts/:id',auth,companyCtx,permit('owner','manager'),async(req,res)=>{await q('DELETE FROM parts WHERE id=$1 AND company_id=$2',[req.params.id,req.company.id]);await audit(req,'delete','part',req.params.id,{});res.json({ok:true})});

// WORK ORDERS
app.get('/api/work-orders',auth,companyCtx,async(req,res)=>res.json((await q(`SELECT w.*,m.name machine_name,u.name assigned_member_name FROM work_orders w LEFT JOIN machines m ON m.id=w.machine_id LEFT JOIN users u ON u.id=w.assigned_user_id WHERE w.company_id=$1 ORDER BY CASE w.status WHEN 'open' THEN 0 WHEN 'in_progress' THEN 1 WHEN 'waiting' THEN 2 ELSE 3 END,w.due_date NULLS LAST,w.id DESC`,[req.company.id])).rows));
app.post('/api/work-orders',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{const b=req.body;if(!clean(b.title))return res.status(400).json({error:'İş emri başlığı gerekli'});if(b.machine_id&&!(await ownMachine(b.machine_id,req.company.id)))return res.status(403).json({error:'Makine aktif firmaya ait değil'});const r=await q(`INSERT INTO work_orders(user_id,company_id,machine_id,title,description,priority,status,assigned_to,assigned_user_id,due_date,parts_used,cost,downtime_min) VALUES($1,$2,$3,$4,$5,$6,'open',$7,$8,$9,$10,$11,$12) RETURNING *`,[req.user.id,req.company.id,b.machine_id||null,clean(b.title),clean(b.description),clean(b.priority)||'Normal',clean(b.assigned_to),b.assigned_user_id||null,nil(b.due_date),clean(b.parts_used),num(b.cost),Math.round(num(b.downtime_min))]);await audit(req,'create','work_order',r.rows[0].id,{title:r.rows[0].title});res.json(r.rows[0])});
app.patch('/api/work-orders/:id',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{const allowed=['open','in_progress','waiting','done'],st=allowed.includes(req.body.status)?req.body.status:'open';const r=await q(`UPDATE work_orders SET status=$1,assigned_to=COALESCE($2,assigned_to),assigned_user_id=COALESCE($3,assigned_user_id),parts_used=COALESCE($4,parts_used),cost=COALESCE($5,cost),downtime_min=COALESCE($6,downtime_min),started_at=CASE WHEN $1='in_progress' AND started_at IS NULL THEN NOW() ELSE started_at END,completed_at=CASE WHEN $1='done' THEN NOW() WHEN $1<>'done' THEN NULL ELSE completed_at END WHERE id=$7 AND company_id=$8 RETURNING *`,[st,req.body.assigned_to??null,req.body.assigned_user_id??null,req.body.parts_used??null,req.body.cost===undefined?null:num(req.body.cost),req.body.downtime_min===undefined?null:Math.round(num(req.body.downtime_min)),req.params.id,req.company.id]);if(!r.rows[0])return res.status(404).json({error:'İş emri bulunamadı'});await audit(req,st==='done'?'complete':'update','work_order',req.params.id,{status:st,title:r.rows[0].title});res.json(r.rows[0])});
app.delete('/api/work-orders/:id',auth,companyCtx,permit('owner','manager'),async(req,res)=>{await q('DELETE FROM work_orders WHERE id=$1 AND company_id=$2',[req.params.id,req.company.id]);await audit(req,'delete','work_order',req.params.id,{});res.json({ok:true})});

// MEASUREMENTS / ATTACHMENTS / QR
app.post('/api/machines/:id/measurements',auth,companyCtx,permit('owner','manager','technician','operator'),async(req,res)=>{if(!(await ownMachine(req.params.id,req.company.id)))return res.status(404).json({error:'Makine bulunamadı'});const b=req.body,r=await q(`INSERT INTO machine_measurements(user_id,company_id,machine_id,temperature,pressure,current_amp,voltage,vibration,rpm,note,measured_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,COALESCE($11::timestamptz,NOW())) RETURNING *`,[req.user.id,req.company.id,req.params.id,b.temperature===''?null:num(b.temperature),b.pressure===''?null:num(b.pressure),b.current_amp===''?null:num(b.current_amp),b.voltage===''?null:num(b.voltage),b.vibration===''?null:num(b.vibration),b.rpm===''?null:num(b.rpm),clean(b.note),nil(b.measured_at)]);await audit(req,'create','measurement',r.rows[0].id,{machine_id:req.params.id});res.json(r.rows[0])});
app.delete('/api/measurements/:id',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{await q('DELETE FROM machine_measurements WHERE id=$1 AND company_id=$2',[req.params.id,req.company.id]);res.json({ok:true})});
const allowedMime=new Set(['image/jpeg','image/png','image/webp','application/pdf','text/plain','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document']);
app.post('/api/machines/:id/attachments',auth,companyCtx,permit('owner','manager','technician','operator'),upload.single('file'),async(req,res)=>{if(!(await ownMachine(req.params.id,req.company.id)))return res.status(404).json({error:'Makine bulunamadı'});if(!req.file)return res.status(400).json({error:'Dosya seçilmedi'});if(!allowedMime.has(req.file.mimetype))return res.status(415).json({error:'Desteklenmeyen dosya türü'});const r=await q(`INSERT INTO attachments(user_id,company_id,machine_id,file_name,mime_type,size_bytes,file_data,caption) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,file_name,mime_type,size_bytes,caption,created_at`,[req.user.id,req.company.id,req.params.id,clean(req.file.originalname).slice(0,240),req.file.mimetype,req.file.size,req.file.buffer,clean(req.body.caption).slice(0,240)]);await audit(req,'create','attachment',r.rows[0].id,{file_name:r.rows[0].file_name});res.json(r.rows[0])});
app.get('/api/attachments/:id',auth,companyCtx,async(req,res)=>{const a=(await q('SELECT file_name,mime_type,file_data FROM attachments WHERE id=$1 AND company_id=$2',[req.params.id,req.company.id])).rows[0];if(!a)return res.status(404).end();res.setHeader('Content-Type',a.mime_type);res.setHeader('Content-Disposition',`inline; filename*=UTF-8''${encodeURIComponent(a.file_name)}`);res.send(a.file_data)});
app.delete('/api/attachments/:id',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{await q('DELETE FROM attachments WHERE id=$1 AND company_id=$2',[req.params.id,req.company.id]);res.json({ok:true})});
app.get('/api/machines/:id/qr',auth,companyCtx,async(req,res)=>{const m=(await q('SELECT id,name FROM machines WHERE id=$1 AND company_id=$2',[req.params.id,req.company.id])).rows[0];if(!m)return res.status(404).json({error:'Makine bulunamadı'});const base=`${req.protocol}://${req.get('host')}`,url=`${base}/?machine=${m.id}`;const svg=await QRCode.toString(url,{type:'svg',margin:1,width:360,errorCorrectionLevel:'M'});res.type('image/svg+xml').send(svg)});

// PERSONAL FAVORITES / CALC HISTORY
app.get('/api/favorites',auth,async(req,res)=>res.json((await q('SELECT article_key FROM favorites WHERE user_id=$1 ORDER BY id DESC',[req.user.id])).rows.map(x=>x.article_key)));
app.post('/api/favorites/toggle',auth,async(req,res)=>{const key=clean(req.body.article_key);if(!key)return res.status(400).json({error:'Makale anahtarı gerekli'});const f=await q('SELECT id FROM favorites WHERE user_id=$1 AND article_key=$2',[req.user.id,key]);if(f.rows.length){await q('DELETE FROM favorites WHERE id=$1',[f.rows[0].id]);return res.json({favorite:false})}await q('INSERT INTO favorites(user_id,article_key) VALUES($1,$2)',[req.user.id,key]);res.json({favorite:true})});
app.get('/api/calc-history',auth,async(req,res)=>res.json((await q('SELECT * FROM calc_history WHERE user_id=$1 ORDER BY id DESC LIMIT 40',[req.user.id])).rows));
app.post('/api/calc-history',auth,async(req,res)=>{const b=req.body;await q('INSERT INTO calc_history(user_id,tool,input_data,result) VALUES($1,$2,$3::jsonb,$4)',[req.user.id,clean(b.tool),JSON.stringify(b.input_data||{}),clean(b.result)]);res.json({ok:true})});

// CALENDAR
app.get('/api/calendar',auth,companyCtx,async(req,res)=>{const month=validDateMonth(req.query.month);const [y,m]=month.split('-').map(Number),start=`${month}-01`,next=m===12?`${y+1}-01-01`:`${y}-${String(m+1).padStart(2,'0')}-01`;const [ma,wo]=await Promise.all([q(`SELECT ma.id,ma.task title,ma.due_date date,ma.status,ma.priority,ma.maintenance_type type,x.name machine_name,'maintenance' kind FROM maintenance ma LEFT JOIN machines x ON x.id=ma.machine_id WHERE ma.company_id=$1 AND ma.due_date >= $2::date AND ma.due_date < $3::date ORDER BY ma.due_date`,[req.company.id,start,next]),q(`SELECT w.id,w.title,w.due_date date,w.status,w.priority,'İş Emri' type,m.name machine_name,'work' kind FROM work_orders w LEFT JOIN machines m ON m.id=w.machine_id WHERE w.company_id=$1 AND w.due_date >= $2::date AND w.due_date < $3::date ORDER BY w.due_date`,[req.company.id,start,next])]);res.json({month,events:[...ma.rows,...wo.rows].sort((a,b)=>String(a.date).localeCompare(String(b.date)))})});

// ADVANCED FAULT ANALYTICS
app.get('/api/analytics/faults',auth,companyCtx,async(req,res)=>{const days=Math.min(730,Math.max(7,Math.round(num(req.query.days,90))));const params=[req.company.id,days];const [sum,systems,severity,recurrent,machinesR,roots,trend]=await Promise.all([
 q(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='open')::int open,COUNT(*) FILTER(WHERE status='closed')::int closed,COALESCE(SUM(downtime_min),0)::int downtime_min,COALESCE(ROUND(AVG(downtime_min) FILTER(WHERE status='closed')),0)::int avg_downtime_min,COALESCE(ROUND(AVG(EXTRACT(EPOCH FROM(closed_at-created_at))/60) FILTER(WHERE closed_at IS NOT NULL)),0)::int mttr_min FROM faults WHERE company_id=$1 AND created_at>=NOW()-make_interval(days=>$2::int)`,params),
 q(`SELECT COALESCE(NULLIF(system,''),'Diğer') label,COUNT(*)::int value FROM faults WHERE company_id=$1 AND created_at>=NOW()-make_interval(days=>$2::int) GROUP BY 1 ORDER BY value DESC LIMIT 12`,params),
 q(`SELECT COALESCE(NULLIF(severity,''),'Orta') label,COUNT(*)::int value FROM faults WHERE company_id=$1 AND created_at>=NOW()-make_interval(days=>$2::int) GROUP BY 1 ORDER BY value DESC`,params),
 q(`SELECT symptom label,COUNT(*)::int value,COALESCE(SUM(downtime_min),0)::int downtime_min FROM faults WHERE company_id=$1 AND created_at>=NOW()-make_interval(days=>$2::int) GROUP BY symptom HAVING COUNT(*)>1 ORDER BY value DESC,downtime_min DESC LIMIT 10`,params),
 q(`SELECT COALESCE(m.name,'Makine seçilmedi') label,COUNT(*)::int value,COALESCE(SUM(f.downtime_min),0)::int downtime_min FROM faults f LEFT JOIN machines m ON m.id=f.machine_id WHERE f.company_id=$1 AND f.created_at>=NOW()-make_interval(days=>$2::int) GROUP BY m.name ORDER BY value DESC,downtime_min DESC LIMIT 10`,params),
 q(`SELECT root_cause label,COUNT(*)::int value FROM faults WHERE company_id=$1 AND created_at>=NOW()-make_interval(days=>$2::int) AND NULLIF(TRIM(root_cause),'') IS NOT NULL GROUP BY root_cause ORDER BY value DESC LIMIT 10`,params),
 q(`SELECT to_char(date_trunc('month',created_at),'YYYY-MM') month,COUNT(*)::int value,COALESCE(SUM(downtime_min),0)::int downtime_min FROM faults WHERE company_id=$1 AND created_at>=NOW()-make_interval(days=>$2::int) GROUP BY 1 ORDER BY 1`,params)
]);res.json({days,summary:sum.rows[0],systems:systems.rows,severity:severity.rows,recurrent:recurrent.rows,machines:machinesR.rows,rootCauses:roots.rows,trend:trend.rows})});

// SERVICE REPORT DATA — frontend turns this into print/PDF view
app.get('/api/reports/maintenance/:id',auth,companyCtx,async(req,res)=>{const r=(await q(`SELECT ma.*,m.name machine_name,m.manufacturer,m.model,m.serial_no,m.location,c.name company_name,u.name created_by_name FROM maintenance ma LEFT JOIN machines m ON m.id=ma.machine_id LEFT JOIN companies c ON c.id=ma.company_id LEFT JOIN users u ON u.id=ma.user_id WHERE ma.id=$1 AND ma.company_id=$2`,[req.params.id,req.company.id])).rows[0];if(!r)return res.status(404).json({error:'Bakım kaydı bulunamadı'});res.json({type:'maintenance',report_no:`SRV-B-${String(r.id).padStart(6,'0')}`,record:r,generated_at:new Date().toISOString(),generated_by:req.user.name})});
app.get('/api/reports/work-order/:id',auth,companyCtx,async(req,res)=>{const r=(await q(`SELECT w.*,m.name machine_name,m.manufacturer,m.model,m.serial_no,m.location,c.name company_name,u.name created_by_name FROM work_orders w LEFT JOIN machines m ON m.id=w.machine_id LEFT JOIN companies c ON c.id=w.company_id LEFT JOIN users u ON u.id=w.user_id WHERE w.id=$1 AND w.company_id=$2`,[req.params.id,req.company.id])).rows[0];if(!r)return res.status(404).json({error:'İş emri bulunamadı'});res.json({type:'work_order',report_no:`SRV-I-${String(r.id).padStart(6,'0')}`,record:r,generated_at:new Date().toISOString(),generated_by:req.user.name})});

// NOTIFICATIONS / DASHBOARD
app.get('/api/notifications',auth,companyCtx,async(req,res)=>{const c=req.company.id;const [ma,f,p,w]=await Promise.all([q(`SELECT ma.id,ma.task title,ma.due_date,x.name machine_name FROM maintenance ma LEFT JOIN machines x ON x.id=ma.machine_id WHERE ma.company_id=$1 AND ma.status='open' AND ma.due_date<=CURRENT_DATE+7 ORDER BY ma.due_date LIMIT 20`,[c]),q(`SELECT f.id,f.symptom title,f.severity,x.name machine_name,f.created_at FROM faults f LEFT JOIN machines x ON x.id=f.machine_id WHERE f.company_id=$1 AND f.status='open' AND f.severity IN ('Yüksek','Kritik') ORDER BY f.id DESC LIMIT 20`,[c]),q(`SELECT id,name title,quantity,min_quantity,unit FROM parts WHERE company_id=$1 AND quantity<=min_quantity ORDER BY quantity-min_quantity LIMIT 20`,[c]),q(`SELECT w.id,w.title,w.due_date,w.priority,m.name machine_name FROM work_orders w LEFT JOIN machines m ON m.id=w.machine_id WHERE w.company_id=$1 AND w.status<>'done' AND (w.due_date IS NULL OR w.due_date<=CURRENT_DATE+7) ORDER BY w.due_date NULLS LAST LIMIT 20`,[c])]);const n=[];ma.rows.forEach(x=>n.push({type:'maintenance',level:new Date(x.due_date)<new Date(new Date().toDateString())?'critical':'warning',title:x.title,detail:`${x.machine_name||'Makine'} • ${x.due_date}`,target:'maintenance'}));f.rows.forEach(x=>n.push({type:'fault',level:x.severity==='Kritik'?'critical':'warning',title:x.title,detail:`${x.machine_name||'Makine'} • ${x.severity}`,target:'diagnosis'}));p.rows.forEach(x=>n.push({type:'stock',level:'warning',title:`Düşük stok: ${x.title}`,detail:`${x.quantity} ${x.unit} / min ${x.min_quantity}`,target:'parts'}));w.rows.forEach(x=>n.push({type:'work',level:x.priority==='Kritik'?'critical':'info',title:x.title,detail:`${x.machine_name||'Makine'}${x.due_date?' • '+x.due_date:''}`,target:'workorders'}));res.json(n.slice(0,50))});
app.get('/api/dashboard',auth,companyCtx,async(req,res)=>{const c=req.company.id;const [m,ma,f,od,d30,done,crit,low,cost,rm,rf,wo]=await Promise.all([q('SELECT COUNT(*)::int c FROM machines WHERE company_id=$1',[c]),q("SELECT COUNT(*)::int c FROM maintenance WHERE company_id=$1 AND status='open'",[c]),q("SELECT COUNT(*)::int c FROM faults WHERE company_id=$1 AND status='open'",[c]),q("SELECT COUNT(*)::int c FROM maintenance WHERE company_id=$1 AND status='open' AND due_date<CURRENT_DATE",[c]),q("SELECT COUNT(*)::int c FROM maintenance WHERE company_id=$1 AND status='open' AND due_date BETWEEN CURRENT_DATE AND CURRENT_DATE+30",[c]),q("SELECT COUNT(*)::int c FROM maintenance WHERE company_id=$1 AND status='done' AND completed_at>=date_trunc('month',NOW())",[c]),q("SELECT COUNT(*)::int c FROM machines WHERE company_id=$1 AND (criticality='Kritik' OR status IN ('Arızalı','Bakımda'))",[c]),q('SELECT COUNT(*)::int c FROM parts WHERE company_id=$1 AND quantity<=min_quantity',[c]),q("SELECT COALESCE(SUM(cost),0)::numeric t FROM maintenance WHERE company_id=$1 AND completed_at>=date_trunc('month',NOW())",[c]),q(`SELECT ma.id,ma.task,ma.due_date,ma.status,ma.priority,x.name machine_name FROM maintenance ma LEFT JOIN machines x ON x.id=ma.machine_id WHERE ma.company_id=$1 ORDER BY ma.created_at DESC LIMIT 6`,[c]),q(`SELECT f.id,f.symptom,f.status,f.severity,f.created_at,x.name machine_name FROM faults f LEFT JOIN machines x ON x.id=f.machine_id WHERE f.company_id=$1 ORDER BY f.created_at DESC LIMIT 6`,[c]),q("SELECT COUNT(*)::int c FROM work_orders WHERE company_id=$1 AND status<>'done'",[c])]);const ms=await q(`SELECT m.*,${machineStats} FROM machines m WHERE m.company_id=$1`,[c]);const scores=ms.rows.map(healthScore),avgHealth=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0;res.json({machines:m.rows[0].c,maintenance:ma.rows[0].c,faults:f.rows[0].c,overdue:od.rows[0].c,due30:d30.rows[0].c,doneMonth:done.rows[0].c,critical:crit.rows[0].c,lowStock:low.rows[0].c,costMonth:Number(cost.rows[0].t||0),openWorkOrders:wo.rows[0].c,avgHealth,recentMaintenance:rm.rows,recentFaults:rf.rows,company:req.company})});

// SITE ADMIN
app.get('/api/admin/summary',auth,siteAdmin,async(req,res)=>{const r=await q(`SELECT (SELECT COUNT(*) FROM users)::int users,(SELECT COUNT(*) FROM users WHERE is_active)::int active_users,(SELECT COUNT(*) FROM users WHERE NOT is_active)::int inactive_users,(SELECT COUNT(*) FROM companies)::int companies,(SELECT COUNT(*) FROM machines)::int machines,(SELECT COUNT(*) FROM maintenance)::int maintenance,(SELECT COUNT(*) FROM faults)::int faults,(SELECT COUNT(*) FROM parts)::int parts,(SELECT COUNT(*) FROM work_orders)::int work_orders,(SELECT COUNT(*) FROM attachments)::int attachments`);res.json(r.rows[0])});
app.get('/api/admin/users',auth,siteAdmin,async(req,res)=>{const term=`%${clean(req.query.search)}%`;const r=await q(`SELECT u.id,u.name,u.email,u.role,u.is_active,u.created_at,(SELECT COUNT(*) FROM company_members cm WHERE cm.user_id=u.id AND cm.is_active)::int companies,(SELECT COUNT(*) FROM machines m WHERE m.user_id=u.id)::int machines,(SELECT COUNT(*) FROM maintenance ma WHERE ma.user_id=u.id)::int maintenance,(SELECT COUNT(*) FROM faults f WHERE f.user_id=u.id)::int faults,(SELECT COUNT(*) FROM parts p WHERE p.user_id=u.id)::int parts FROM users u WHERE ($1='%%' OR u.name ILIKE $1 OR u.email ILIKE $1) ORDER BY u.id DESC LIMIT 500`,[term]);res.json(r.rows)});
app.get('/api/admin/users/:id',auth,siteAdmin,async(req,res)=>{const u=(await q('SELECT id,name,email,role,is_active,created_at FROM users WHERE id=$1',[req.params.id])).rows[0];if(!u)return res.status(404).json({error:'Kullanıcı bulunamadı'});const [m,ma,f,p,cs]=await Promise.all([q('SELECT * FROM machines WHERE user_id=$1 ORDER BY id DESC LIMIT 50',[u.id]),q('SELECT ma.*,x.name machine_name FROM maintenance ma LEFT JOIN machines x ON x.id=ma.machine_id WHERE ma.user_id=$1 ORDER BY ma.id DESC LIMIT 50',[u.id]),q('SELECT f.*,x.name machine_name FROM faults f LEFT JOIN machines x ON x.id=f.machine_id WHERE f.user_id=$1 ORDER BY f.id DESC LIMIT 50',[u.id]),q('SELECT * FROM parts WHERE user_id=$1 ORDER BY name LIMIT 50',[u.id]),q(`SELECT c.id,c.name,cm.role FROM company_members cm JOIN companies c ON c.id=cm.company_id WHERE cm.user_id=$1 AND cm.is_active`,[u.id])]);res.json({user:u,machines:m.rows,maintenance:ma.rows,faults:f.rows,parts:p.rows,companies:cs.rows})});
app.patch('/api/admin/users/:id/active',auth,siteAdmin,async(req,res)=>{if(Number(req.params.id)===Number(req.user.id))return res.status(400).json({error:'Kendi admin hesabınızı devre dışı bırakamazsınız'});const r=await q('UPDATE users SET is_active=$1 WHERE id=$2 RETURNING id,name,email,role,is_active',[!!req.body.is_active,req.params.id]);res.json(r.rows[0]||{})});
app.patch('/api/admin/users/:id/role',auth,siteAdmin,async(req,res)=>{if(Number(req.params.id)===Number(req.user.id)&&req.body.role!=='admin')return res.status(400).json({error:'Kendi admin rolünüzü kaldıramazsınız'});const role=req.body.role==='admin'?'admin':'user';const r=await q('UPDATE users SET role=$1 WHERE id=$2 RETURNING id,name,email,role,is_active',[role,req.params.id]);res.json(r.rows[0]||{})});
app.delete('/api/admin/users/:id',auth,siteAdmin,async(req,res)=>{if(Number(req.params.id)===Number(req.user.id))return res.status(400).json({error:'Kendi admin hesabınızı silemezsiniz'});await q('DELETE FROM users WHERE id=$1',[req.params.id]);res.json({ok:true})});

app.get('/api/health',(req,res)=>res.json({ok:true,version:'15.0.0',product:'Dijital Makinacı V15 Pro CMMS'}));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.use((err,req,res,next)=>{console.error(err);if(err?.code==='LIMIT_FILE_SIZE')return res.status(413).json({error:'Dosya en fazla 5 MB olabilir'});res.status(500).json({error:'Sunucu hatası'})});

initDb().then(()=>app.listen(PORT,()=>console.log(`Dijital Makinacı V15 http://localhost:${PORT}`))).catch(e=>{console.error('DB init hatası:',e);process.exit(1)});
