const express=require("express");
const path=require("path");
const cookieParser=require("cookie-parser");
const helmet=require("helmet");
const rateLimit=require("express-rate-limit");
const bcrypt=require("bcryptjs");
const jwt=require("jsonwebtoken");
const multer=require("multer");
const QRCode=require("qrcode");
const {Pool}=require("pg");

const app=express();
const PORT=process.env.PORT||3000;
const JWT_SECRET=process.env.JWT_SECRET||"DEVELOPMENT_ONLY_CHANGE_ME";
const DATABASE_URL=process.env.DATABASE_URL;
if(!DATABASE_URL){console.error("DATABASE_URL tanımlı değil.");process.exit(1)}
const pool=new Pool({connectionString:DATABASE_URL,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:false});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:1}});
app.set("trust proxy",1);app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:"500kb"}));app.use(cookieParser());app.use(express.static(path.join(__dirname,"public"),{maxAge:0,etag:true,setHeaders:(res)=>res.setHeader("Cache-Control","no-cache")}));app.use("/api/auth",rateLimit({windowMs:15*60*1000,max:60,standardHeaders:true,legacyHeaders:false}));

const clean=s=>String(s??"").trim();
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const nil=v=>clean(v)||null;
const emailOk=s=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
async function q(text,params=[]){return pool.query(text,params)}
function sign(u){return jwt.sign({id:u.id,email:u.email,name:u.name,role:u.role},JWT_SECRET,{expiresIn:"7d"})}
function setCookie(res,t){res.cookie("dm_token",t,{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",maxAge:7*24*60*60*1000})}
function auth(req,res,next){const t=req.cookies.dm_token;if(!t)return res.status(401).json({error:"Giriş gerekli"});try{req.user=jwt.verify(t,JWT_SECRET);next()}catch{res.clearCookie("dm_token");res.status(401).json({error:"Oturum geçersiz"})}}
function admin(req,res,next){if(req.user?.role!=="admin")return res.status(403).json({error:"Admin yetkisi gerekli"});next()}
function healthScore(m){let s=100;if(m.status==="Arızalı")s-=35;else if(m.status==="Bakımda")s-=15;else if(m.status==="Devre dışı")s-=25;if(m.criticality==="Kritik")s-=5;s-=Math.min(24,num(m.open_faults)*6);s-=Math.min(16,num(m.critical_faults)*8);s-=Math.min(21,num(m.overdue_maintenance)*7);s-=Math.min(9,num(m.due30)*3);if(num(m.faults90)>=3)s-=8;if(m.last_maintenance_date){const days=(Date.now()-new Date(m.last_maintenance_date).getTime())/86400000;if(days>180)s-=10}else if(num(m.hours)>250)s-=8;return Math.max(5,Math.min(100,Math.round(s)))}
async function ownMachine(id,userId){return (await q("SELECT id FROM machines WHERE id=$1 AND user_id=$2",[id,userId])).rows[0]}

async function addCols(table,cols){for(const c of cols)await q(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS ${c}`)}
async function initDb(){
 await q(`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(200) UNIQUE NOT NULL,password_hash TEXT NOT NULL,role VARCHAR(20) NOT NULL DEFAULT 'user',is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS machines(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name VARCHAR(160) NOT NULL,model VARCHAR(160) DEFAULT '',hours NUMERIC(12,1) DEFAULT 0,criticality VARCHAR(30) DEFAULT 'Normal',serial_no VARCHAR(120) DEFAULT '',note TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols("machines",["manufacturer VARCHAR(160) DEFAULT ''","category VARCHAR(100) DEFAULT ''","location VARCHAR(180) DEFAULT ''","status VARCHAR(30) DEFAULT 'Çalışıyor'","power_kw NUMERIC(10,2) DEFAULT 0","year INTEGER","last_maintenance_date DATE","next_maintenance_date DATE","lubricant VARCHAR(180) DEFAULT ''","bearing_info TEXT DEFAULT ''","belt_info TEXT DEFAULT ''","motor_info TEXT DEFAULT ''"]);
 await q(`CREATE TABLE IF NOT EXISTS maintenance(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,machine_id BIGINT REFERENCES machines(id) ON DELETE CASCADE,task VARCHAR(220) NOT NULL,due_date DATE NOT NULL,priority VARCHAR(30) DEFAULT 'Normal',status VARCHAR(20) DEFAULT 'open',note TEXT DEFAULT '',completed_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols("maintenance",["maintenance_type VARCHAR(50) DEFAULT 'Periyodik'","frequency VARCHAR(80) DEFAULT ''","technician VARCHAR(160) DEFAULT ''","parts_used TEXT DEFAULT ''","cost NUMERIC(12,2) DEFAULT 0","duration_min INTEGER DEFAULT 0","meter_hours NUMERIC(12,1) DEFAULT 0"]);
 await q(`CREATE TABLE IF NOT EXISTS faults(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,machine_id BIGINT REFERENCES machines(id) ON DELETE SET NULL,system VARCHAR(40),symptom VARCHAR(180) NOT NULL,measurements JSONB DEFAULT '{}'::jsonb,note TEXT DEFAULT '',diagnosis TEXT DEFAULT '',status VARCHAR(20) DEFAULT 'open',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols("faults",["severity VARCHAR(30) DEFAULT 'Orta'","root_cause TEXT DEFAULT ''","action_taken TEXT DEFAULT ''","downtime_min INTEGER DEFAULT 0","closed_at TIMESTAMPTZ"]);
 await q(`CREATE TABLE IF NOT EXISTS parts(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name VARCHAR(180) NOT NULL,part_code VARCHAR(120) DEFAULT '',category VARCHAR(80) DEFAULT '',quantity NUMERIC(12,2) DEFAULT 0,min_quantity NUMERIC(12,2) DEFAULT 0,unit VARCHAR(30) DEFAULT 'adet',location VARCHAR(140) DEFAULT '',supplier VARCHAR(180) DEFAULT '',unit_cost NUMERIC(12,2) DEFAULT 0,note TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS favorites(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,article_key VARCHAR(180) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,article_key))`);
 await q(`CREATE TABLE IF NOT EXISTS calc_history(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,tool VARCHAR(120) NOT NULL,input_data JSONB DEFAULT '{}'::jsonb,result TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS work_orders(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,machine_id BIGINT REFERENCES machines(id) ON DELETE SET NULL,title VARCHAR(220) NOT NULL,description TEXT DEFAULT '',priority VARCHAR(30) DEFAULT 'Normal',status VARCHAR(30) DEFAULT 'open',assigned_to VARCHAR(160) DEFAULT '',due_date DATE,started_at TIMESTAMPTZ,completed_at TIMESTAMPTZ,parts_used TEXT DEFAULT '',cost NUMERIC(12,2) DEFAULT 0,downtime_min INTEGER DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS machine_measurements(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,machine_id BIGINT NOT NULL REFERENCES machines(id) ON DELETE CASCADE,temperature NUMERIC(10,2),pressure NUMERIC(10,2),current_amp NUMERIC(10,2),voltage NUMERIC(10,2),vibration NUMERIC(10,3),rpm NUMERIC(12,1),note TEXT DEFAULT '',measured_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS attachments(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,machine_id BIGINT NOT NULL REFERENCES machines(id) ON DELETE CASCADE,file_name VARCHAR(240) NOT NULL,mime_type VARCHAR(120) NOT NULL,size_bytes INTEGER NOT NULL,file_data BYTEA NOT NULL,caption VARCHAR(240) DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 const ae=clean(process.env.ADMIN_EMAIL).toLowerCase(),ap=clean(process.env.ADMIN_PASSWORD);if(ae&&ap){const f=await q("SELECT id FROM users WHERE email=$1",[ae]);if(!f.rows.length){const h=await bcrypt.hash(ap,12);await q("INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,'admin')",[process.env.ADMIN_NAME||"Site Yöneticisi",ae,h])}else await q("UPDATE users SET role='admin' WHERE email=$1",[ae])}
}
initDb().catch(e=>{console.error("DB init hatası:",e);process.exit(1)});

app.post("/api/auth/register",async(req,res)=>{try{const name=clean(req.body.name),email=clean(req.body.email).toLowerCase(),password=String(req.body.password||"");if(name.length<2)return res.status(400).json({error:"Ad soyad gerekli"});if(!emailOk(email))return res.status(400).json({error:"Geçerli e-posta gir"});if(password.length<8)return res.status(400).json({error:"Şifre en az 8 karakter olmalı"});const h=await bcrypt.hash(password,12);const r=await q("INSERT INTO users(name,email,password_hash) VALUES($1,$2,$3) RETURNING id,name,email,role,is_active,created_at",[name,email,h]);const u=r.rows[0];setCookie(res,sign(u));res.json({user:u})}catch(e){if(e.code==="23505")return res.status(409).json({error:"Bu e-posta zaten kayıtlı"});console.error(e);res.status(500).json({error:"Kayıt oluşturulamadı"})}});
app.post("/api/auth/login",async(req,res)=>{try{const email=clean(req.body.email).toLowerCase(),password=String(req.body.password||"");const u=(await q("SELECT * FROM users WHERE email=$1",[email])).rows[0];if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:"E-posta veya şifre hatalı"});if(!u.is_active)return res.status(403).json({error:"Hesabınız devre dışı"});setCookie(res,sign(u));res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role,is_active:u.is_active}})}catch(e){console.error(e);res.status(500).json({error:"Giriş yapılamadı"})}});
app.post("/api/auth/logout",(req,res)=>{res.clearCookie("dm_token");res.json({ok:true})});
app.get("/api/auth/me",auth,async(req,res)=>{const u=(await q("SELECT id,name,email,role,is_active,created_at FROM users WHERE id=$1",[req.user.id])).rows[0];if(!u?.is_active)return res.status(403).json({error:"Hesap devre dışı"});res.json({user:u})});

app.get("/api/machines",auth,async(req,res)=>{const r=await q(`SELECT m.*,(SELECT COUNT(*) FROM faults f WHERE f.machine_id=m.id AND f.user_id=m.user_id AND f.status='open')::int open_faults,(SELECT COUNT(*) FROM faults f WHERE f.machine_id=m.id AND f.user_id=m.user_id AND f.status='open' AND f.severity='Kritik')::int critical_faults,(SELECT COUNT(*) FROM faults f WHERE f.machine_id=m.id AND f.user_id=m.user_id AND f.created_at>=NOW()-INTERVAL '90 days')::int faults90,(SELECT COUNT(*) FROM maintenance x WHERE x.machine_id=m.id AND x.user_id=m.user_id AND x.status='open' AND x.due_date<CURRENT_DATE)::int overdue_maintenance,(SELECT COUNT(*) FROM maintenance x WHERE x.machine_id=m.id AND x.user_id=m.user_id AND x.status='open' AND x.due_date BETWEEN CURRENT_DATE AND CURRENT_DATE+30)::int due30 FROM machines m WHERE m.user_id=$1 ORDER BY m.id DESC`,[req.user.id]);res.json(r.rows.map(x=>({...x,health_score:healthScore(x)}))) });
app.get("/api/machines/:id/detail",auth,async(req,res)=>{const m=(await q(`SELECT m.*,(SELECT COUNT(*) FROM faults f WHERE f.machine_id=m.id AND f.user_id=m.user_id AND f.status='open')::int open_faults,(SELECT COUNT(*) FROM faults f WHERE f.machine_id=m.id AND f.user_id=m.user_id AND f.status='open' AND f.severity='Kritik')::int critical_faults,(SELECT COUNT(*) FROM faults f WHERE f.machine_id=m.id AND f.user_id=m.user_id AND f.created_at>=NOW()-INTERVAL '90 days')::int faults90,(SELECT COUNT(*) FROM maintenance x WHERE x.machine_id=m.id AND x.user_id=m.user_id AND x.status='open' AND x.due_date<CURRENT_DATE)::int overdue_maintenance,(SELECT COUNT(*) FROM maintenance x WHERE x.machine_id=m.id AND x.user_id=m.user_id AND x.status='open' AND x.due_date BETWEEN CURRENT_DATE AND CURRENT_DATE+30)::int due30 FROM machines m WHERE m.id=$1 AND m.user_id=$2`,[req.params.id,req.user.id])).rows[0];if(!m)return res.status(404).json({error:"Makine bulunamadı"});const [ma,f,w,ms,a]=await Promise.all([q("SELECT * FROM maintenance WHERE machine_id=$1 AND user_id=$2 ORDER BY due_date DESC,id DESC LIMIT 50",[m.id,req.user.id]),q("SELECT * FROM faults WHERE machine_id=$1 AND user_id=$2 ORDER BY id DESC LIMIT 50",[m.id,req.user.id]),q("SELECT * FROM work_orders WHERE machine_id=$1 AND user_id=$2 ORDER BY id DESC LIMIT 50",[m.id,req.user.id]),q("SELECT * FROM machine_measurements WHERE machine_id=$1 AND user_id=$2 ORDER BY measured_at DESC LIMIT 60",[m.id,req.user.id]),q("SELECT id,file_name,mime_type,size_bytes,caption,created_at FROM attachments WHERE machine_id=$1 AND user_id=$2 ORDER BY id DESC LIMIT 50",[m.id,req.user.id])]);m.health_score=healthScore(m);res.json({machine:m,maintenance:ma.rows,faults:f.rows,workOrders:w.rows,measurements:ms.rows.reverse(),attachments:a.rows})});
app.post("/api/machines",auth,async(req,res)=>{const b=req.body;if(!clean(b.name))return res.status(400).json({error:"Makine adı gerekli"});const r=await q(`INSERT INTO machines(user_id,name,manufacturer,model,category,serial_no,location,status,hours,power_kw,year,criticality,last_maintenance_date,next_maintenance_date,lubricant,bearing_info,belt_info,motor_info,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19) RETURNING *`,[req.user.id,clean(b.name),clean(b.manufacturer),clean(b.model),clean(b.category),clean(b.serial_no),clean(b.location),clean(b.status)||"Çalışıyor",num(b.hours),num(b.power_kw),b.year?parseInt(b.year,10):null,clean(b.criticality)||"Normal",nil(b.last_maintenance_date),nil(b.next_maintenance_date),clean(b.lubricant),clean(b.bearing_info),clean(b.belt_info),clean(b.motor_info),clean(b.note)]);res.json(r.rows[0])});
app.put("/api/machines/:id",auth,async(req,res)=>{const b=req.body;const r=await q(`UPDATE machines SET name=$1,manufacturer=$2,model=$3,category=$4,serial_no=$5,location=$6,status=$7,hours=$8,power_kw=$9,year=$10,criticality=$11,last_maintenance_date=$12,next_maintenance_date=$13,lubricant=$14,bearing_info=$15,belt_info=$16,motor_info=$17,note=$18 WHERE id=$19 AND user_id=$20 RETURNING *`,[clean(b.name),clean(b.manufacturer),clean(b.model),clean(b.category),clean(b.serial_no),clean(b.location),clean(b.status)||"Çalışıyor",num(b.hours),num(b.power_kw),b.year?parseInt(b.year,10):null,clean(b.criticality)||"Normal",nil(b.last_maintenance_date),nil(b.next_maintenance_date),clean(b.lubricant),clean(b.bearing_info),clean(b.belt_info),clean(b.motor_info),clean(b.note),req.params.id,req.user.id]);if(!r.rows[0])return res.status(404).json({error:"Makine bulunamadı"});res.json(r.rows[0])});
app.delete("/api/machines/:id",auth,async(req,res)=>{await q("DELETE FROM machines WHERE id=$1 AND user_id=$2",[req.params.id,req.user.id]);res.json({ok:true})});

app.get("/api/maintenance",auth,async(req,res)=>res.json((await q(`SELECT m.*,x.name machine_name FROM maintenance m LEFT JOIN machines x ON x.id=m.machine_id WHERE m.user_id=$1 ORDER BY CASE WHEN m.status='open' THEN 0 ELSE 1 END,m.due_date ASC,m.id DESC`,[req.user.id])).rows));
app.post("/api/maintenance",auth,async(req,res)=>{const b=req.body;if(!b.machine_id||!clean(b.task)||!b.due_date)return res.status(400).json({error:"Makine, görev ve tarih gerekli"});const own=await q("SELECT id FROM machines WHERE id=$1 AND user_id=$2",[b.machine_id,req.user.id]);if(!own.rows.length)return res.status(403).json({error:"Makine size ait değil"});const r=await q(`INSERT INTO maintenance(user_id,machine_id,task,due_date,priority,note,maintenance_type,frequency,technician,parts_used,cost,duration_min,meter_hours) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[req.user.id,b.machine_id,clean(b.task),b.due_date,clean(b.priority)||"Normal",clean(b.note),clean(b.maintenance_type)||"Periyodik",clean(b.frequency),clean(b.technician),clean(b.parts_used),num(b.cost),Math.round(num(b.duration_min)),num(b.meter_hours)]);res.json(r.rows[0])});
app.patch("/api/maintenance/:id/status",auth,async(req,res)=>{const st=req.body.status==="done"?"done":"open";const r=await q(`UPDATE maintenance SET status=$1,completed_at=CASE WHEN $1='done' THEN NOW() ELSE NULL END WHERE id=$2 AND user_id=$3 RETURNING *`,[st,req.params.id,req.user.id]);if(!r.rows[0])return res.status(404).json({error:"Kayıt bulunamadı"});res.json(r.rows[0])});
app.delete("/api/maintenance/:id",auth,async(req,res)=>{await q("DELETE FROM maintenance WHERE id=$1 AND user_id=$2",[req.params.id,req.user.id]);res.json({ok:true})});

app.get("/api/faults",auth,async(req,res)=>res.json((await q(`SELECT f.*,x.name machine_name FROM faults f LEFT JOIN machines x ON x.id=f.machine_id WHERE f.user_id=$1 ORDER BY CASE WHEN f.status='open' THEN 0 ELSE 1 END,f.id DESC LIMIT 200`,[req.user.id])).rows));
app.post("/api/faults",auth,async(req,res)=>{const b=req.body;if(!clean(b.symptom))return res.status(400).json({error:"Belirti gerekli"});if(b.machine_id){const own=await q("SELECT id FROM machines WHERE id=$1 AND user_id=$2",[b.machine_id,req.user.id]);if(!own.rows.length)return res.status(403).json({error:"Makine size ait değil"})}const r=await q(`INSERT INTO faults(user_id,machine_id,system,symptom,measurements,note,diagnosis,severity,root_cause,action_taken,downtime_min) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9,$10,$11) RETURNING *`,[req.user.id,b.machine_id||null,clean(b.system),clean(b.symptom),JSON.stringify(b.measurements||{}),clean(b.note),clean(b.diagnosis),clean(b.severity)||"Orta",clean(b.root_cause),clean(b.action_taken),Math.round(num(b.downtime_min))]);res.json(r.rows[0])});
app.patch("/api/faults/:id/status",auth,async(req,res)=>{const st=req.body.status==="closed"?"closed":"open";const r=await q(`UPDATE faults SET status=$1,root_cause=COALESCE($2,root_cause),action_taken=COALESCE($3,action_taken),downtime_min=COALESCE($4,downtime_min),closed_at=CASE WHEN $1='closed' THEN NOW() ELSE NULL END WHERE id=$5 AND user_id=$6 RETURNING *`,[st,req.body.root_cause??null,req.body.action_taken??null,req.body.downtime_min===undefined?null:Math.round(num(req.body.downtime_min)),req.params.id,req.user.id]);if(!r.rows[0])return res.status(404).json({error:"Arıza bulunamadı"});res.json(r.rows[0])});
app.delete("/api/faults/:id",auth,async(req,res)=>{await q("DELETE FROM faults WHERE id=$1 AND user_id=$2",[req.params.id,req.user.id]);res.json({ok:true})});

app.get("/api/parts",auth,async(req,res)=>res.json((await q("SELECT * FROM parts WHERE user_id=$1 ORDER BY (quantity<=min_quantity) DESC,name ASC",[req.user.id])).rows));
app.post("/api/parts",auth,async(req,res)=>{const b=req.body;if(!clean(b.name))return res.status(400).json({error:"Parça adı gerekli"});const r=await q(`INSERT INTO parts(user_id,name,part_code,category,quantity,min_quantity,unit,location,supplier,unit_cost,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[req.user.id,clean(b.name),clean(b.part_code),clean(b.category),num(b.quantity),num(b.min_quantity),clean(b.unit)||"adet",clean(b.location),clean(b.supplier),num(b.unit_cost),clean(b.note)]);res.json(r.rows[0])});
app.put("/api/parts/:id",auth,async(req,res)=>{const b=req.body;const r=await q(`UPDATE parts SET name=$1,part_code=$2,category=$3,quantity=$4,min_quantity=$5,unit=$6,location=$7,supplier=$8,unit_cost=$9,note=$10 WHERE id=$11 AND user_id=$12 RETURNING *`,[clean(b.name),clean(b.part_code),clean(b.category),num(b.quantity),num(b.min_quantity),clean(b.unit)||"adet",clean(b.location),clean(b.supplier),num(b.unit_cost),clean(b.note),req.params.id,req.user.id]);if(!r.rows[0])return res.status(404).json({error:"Parça bulunamadı"});res.json(r.rows[0])});
app.delete("/api/parts/:id",auth,async(req,res)=>{await q("DELETE FROM parts WHERE id=$1 AND user_id=$2",[req.params.id,req.user.id]);res.json({ok:true})});

// V14 — İş emirleri
app.get("/api/work-orders",auth,async(req,res)=>res.json((await q(`SELECT w.*,m.name machine_name FROM work_orders w LEFT JOIN machines m ON m.id=w.machine_id WHERE w.user_id=$1 ORDER BY CASE w.status WHEN 'open' THEN 0 WHEN 'in_progress' THEN 1 WHEN 'waiting' THEN 2 ELSE 3 END,COALESCE(w.due_date,CURRENT_DATE+9999),w.id DESC`,[req.user.id])).rows));
app.post("/api/work-orders",auth,async(req,res)=>{const b=req.body;if(!clean(b.title))return res.status(400).json({error:"İş emri başlığı gerekli"});if(b.machine_id&&!(await ownMachine(b.machine_id,req.user.id)))return res.status(403).json({error:"Makine size ait değil"});const r=await q(`INSERT INTO work_orders(user_id,machine_id,title,description,priority,status,assigned_to,due_date,parts_used,cost,downtime_min) VALUES($1,$2,$3,$4,$5,'open',$6,$7,$8,$9,$10) RETURNING *`,[req.user.id,b.machine_id||null,clean(b.title),clean(b.description),clean(b.priority)||"Normal",clean(b.assigned_to),nil(b.due_date),clean(b.parts_used),num(b.cost),Math.round(num(b.downtime_min))]);res.json(r.rows[0])});
app.patch("/api/work-orders/:id",auth,async(req,res)=>{const allowed=['open','in_progress','waiting','done'],st=allowed.includes(req.body.status)?req.body.status:'open';const r=await q(`UPDATE work_orders SET status=$1,assigned_to=COALESCE($2,assigned_to),parts_used=COALESCE($3,parts_used),cost=COALESCE($4,cost),downtime_min=COALESCE($5,downtime_min),started_at=CASE WHEN $1='in_progress' AND started_at IS NULL THEN NOW() ELSE started_at END,completed_at=CASE WHEN $1='done' THEN NOW() WHEN $1<>'done' THEN NULL ELSE completed_at END WHERE id=$6 AND user_id=$7 RETURNING *`,[st,req.body.assigned_to??null,req.body.parts_used??null,req.body.cost===undefined?null:num(req.body.cost),req.body.downtime_min===undefined?null:Math.round(num(req.body.downtime_min)),req.params.id,req.user.id]);if(!r.rows[0])return res.status(404).json({error:"İş emri bulunamadı"});res.json(r.rows[0])});
app.delete("/api/work-orders/:id",auth,async(req,res)=>{await q("DELETE FROM work_orders WHERE id=$1 AND user_id=$2",[req.params.id,req.user.id]);res.json({ok:true})});

// V14 — Ölçüm/trend kayıtları
app.post("/api/machines/:id/measurements",auth,async(req,res)=>{if(!(await ownMachine(req.params.id,req.user.id)))return res.status(404).json({error:"Makine bulunamadı"});const b=req.body,r=await q(`INSERT INTO machine_measurements(user_id,machine_id,temperature,pressure,current_amp,voltage,vibration,rpm,note,measured_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,COALESCE($10::timestamptz,NOW())) RETURNING *`,[req.user.id,req.params.id,b.temperature===''?null:num(b.temperature),b.pressure===''?null:num(b.pressure),b.current_amp===''?null:num(b.current_amp),b.voltage===''?null:num(b.voltage),b.vibration===''?null:num(b.vibration),b.rpm===''?null:num(b.rpm),clean(b.note),nil(b.measured_at)]);res.json(r.rows[0])});
app.delete("/api/measurements/:id",auth,async(req,res)=>{await q("DELETE FROM machine_measurements WHERE id=$1 AND user_id=$2",[req.params.id,req.user.id]);res.json({ok:true})});

// V14 — Fotoğraf/belge kasası (PostgreSQL içinde, deploy sonrası kaybolmaz)
const allowedMime=new Set(['image/jpeg','image/png','image/webp','application/pdf','text/plain','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document']);
app.post("/api/machines/:id/attachments",auth,upload.single('file'),async(req,res)=>{try{if(!(await ownMachine(req.params.id,req.user.id)))return res.status(404).json({error:"Makine bulunamadı"});if(!req.file)return res.status(400).json({error:"Dosya seçilmedi"});if(!allowedMime.has(req.file.mimetype))return res.status(415).json({error:"Desteklenmeyen dosya türü"});const r=await q(`INSERT INTO attachments(user_id,machine_id,file_name,mime_type,size_bytes,file_data,caption) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,file_name,mime_type,size_bytes,caption,created_at`,[req.user.id,req.params.id,clean(req.file.originalname).slice(0,240),req.file.mimetype,req.file.size,req.file.buffer,clean(req.body.caption).slice(0,240)]);res.json(r.rows[0])}catch(e){console.error(e);res.status(500).json({error:"Dosya yüklenemedi"})}});
app.get("/api/attachments/:id",auth,async(req,res)=>{const a=(await q("SELECT file_name,mime_type,file_data FROM attachments WHERE id=$1 AND user_id=$2",[req.params.id,req.user.id])).rows[0];if(!a)return res.status(404).end();res.setHeader('Content-Type',a.mime_type);res.setHeader('Content-Disposition',`inline; filename*=UTF-8''${encodeURIComponent(a.file_name)}`);res.send(a.file_data)});
app.delete("/api/attachments/:id",auth,async(req,res)=>{await q("DELETE FROM attachments WHERE id=$1 AND user_id=$2",[req.params.id,req.user.id]);res.json({ok:true})});

// V14 — QR varlık etiketi
app.get("/api/machines/:id/qr",auth,async(req,res)=>{const m=(await q("SELECT id,name FROM machines WHERE id=$1 AND user_id=$2",[req.params.id,req.user.id])).rows[0];if(!m)return res.status(404).json({error:"Makine bulunamadı"});const base=`${req.protocol}://${req.get('host')}`,url=`${base}/?machine=${m.id}`;const svg=await QRCode.toString(url,{type:'svg',margin:1,width:360,errorCorrectionLevel:'M'});res.type('image/svg+xml').send(svg)});

// V14 — Bildirim merkezi (canlı kayıtlardan türetilir)
app.get("/api/notifications",auth,async(req,res)=>{const u=req.user.id;const [ma,f,p,w]=await Promise.all([q(`SELECT ma.id,ma.task title,ma.due_date,x.name machine_name FROM maintenance ma LEFT JOIN machines x ON x.id=ma.machine_id WHERE ma.user_id=$1 AND ma.status='open' AND ma.due_date<=CURRENT_DATE+7 ORDER BY ma.due_date LIMIT 20`,[u]),q(`SELECT f.id,f.symptom title,f.severity,x.name machine_name,f.created_at FROM faults f LEFT JOIN machines x ON x.id=f.machine_id WHERE f.user_id=$1 AND f.status='open' AND f.severity IN ('Yüksek','Kritik') ORDER BY f.id DESC LIMIT 20`,[u]),q(`SELECT id,name title,quantity,min_quantity,unit FROM parts WHERE user_id=$1 AND quantity<=min_quantity ORDER BY quantity-min_quantity LIMIT 20`,[u]),q(`SELECT w.id,w.title,w.due_date,w.priority,m.name machine_name FROM work_orders w LEFT JOIN machines m ON m.id=w.machine_id WHERE w.user_id=$1 AND w.status<>'done' AND (w.due_date IS NULL OR w.due_date<=CURRENT_DATE+7) ORDER BY w.due_date NULLS LAST LIMIT 20`,[u])]);const n=[];ma.rows.forEach(x=>n.push({type:'maintenance',level:new Date(x.due_date)<new Date(new Date().toDateString())?'critical':'warning',title:x.title,detail:`${x.machine_name||'Makine'} • ${x.due_date}`,target:'maintenance'}));f.rows.forEach(x=>n.push({type:'fault',level:x.severity==='Kritik'?'critical':'warning',title:x.title,detail:`${x.machine_name||'Makine'} • ${x.severity}`,target:'diagnosis'}));p.rows.forEach(x=>n.push({type:'stock',level:'warning',title:`Düşük stok: ${x.title}`,detail:`${x.quantity} ${x.unit} / min ${x.min_quantity}`,target:'parts'}));w.rows.forEach(x=>n.push({type:'work',level:x.priority==='Kritik'?'critical':'info',title:x.title,detail:`${x.machine_name||'Makine'}${x.due_date?' • '+x.due_date:''}`,target:'workorders'}));res.json(n.slice(0,50))});

app.get("/api/favorites",auth,async(req,res)=>res.json((await q("SELECT article_key FROM favorites WHERE user_id=$1 ORDER BY id DESC",[req.user.id])).rows.map(x=>x.article_key)));
app.post("/api/favorites/toggle",auth,async(req,res)=>{const key=clean(req.body.article_key);if(!key)return res.status(400).json({error:"Makale anahtarı gerekli"});const f=await q("SELECT id FROM favorites WHERE user_id=$1 AND article_key=$2",[req.user.id,key]);if(f.rows.length){await q("DELETE FROM favorites WHERE id=$1",[f.rows[0].id]);return res.json({favorite:false})}await q("INSERT INTO favorites(user_id,article_key) VALUES($1,$2)",[req.user.id,key]);res.json({favorite:true})});
app.get("/api/calc-history",auth,async(req,res)=>res.json((await q("SELECT * FROM calc_history WHERE user_id=$1 ORDER BY id DESC LIMIT 40",[req.user.id])).rows));
app.post("/api/calc-history",auth,async(req,res)=>{const b=req.body;await q("INSERT INTO calc_history(user_id,tool,input_data,result) VALUES($1,$2,$3::jsonb,$4)",[req.user.id,clean(b.tool),JSON.stringify(b.input_data||{}),clean(b.result)]);res.json({ok:true})});

app.get("/api/dashboard",auth,async(req,res)=>{const u=req.user.id;const [m,ma,f,od,d30,done,crit,low,cost,rm,rf,wo]=await Promise.all([q("SELECT COUNT(*)::int c FROM machines WHERE user_id=$1",[u]),q("SELECT COUNT(*)::int c FROM maintenance WHERE user_id=$1 AND status='open'",[u]),q("SELECT COUNT(*)::int c FROM faults WHERE user_id=$1 AND status='open'",[u]),q("SELECT COUNT(*)::int c FROM maintenance WHERE user_id=$1 AND status='open' AND due_date<CURRENT_DATE",[u]),q("SELECT COUNT(*)::int c FROM maintenance WHERE user_id=$1 AND status='open' AND due_date BETWEEN CURRENT_DATE AND CURRENT_DATE+30",[u]),q("SELECT COUNT(*)::int c FROM maintenance WHERE user_id=$1 AND status='done' AND completed_at>=date_trunc('month',NOW())",[u]),q("SELECT COUNT(*)::int c FROM machines WHERE user_id=$1 AND (criticality='Kritik' OR status IN ('Arızalı','Bakımda'))",[u]),q("SELECT COUNT(*)::int c FROM parts WHERE user_id=$1 AND quantity<=min_quantity",[u]),q("SELECT COALESCE(SUM(cost),0)::numeric t FROM maintenance WHERE user_id=$1 AND completed_at>=date_trunc('month',NOW())",[u]),q(`SELECT ma.id,ma.task,ma.due_date,ma.status,ma.priority,x.name machine_name FROM maintenance ma LEFT JOIN machines x ON x.id=ma.machine_id WHERE ma.user_id=$1 ORDER BY ma.created_at DESC LIMIT 6`,[u]),q(`SELECT f.id,f.symptom,f.status,f.severity,f.created_at,x.name machine_name FROM faults f LEFT JOIN machines x ON x.id=f.machine_id WHERE f.user_id=$1 ORDER BY f.created_at DESC LIMIT 6`,[u]),q("SELECT COUNT(*)::int c FROM work_orders WHERE user_id=$1 AND status<>'done'",[u])]);const ms=await q(`SELECT m.*,(SELECT COUNT(*) FROM faults f WHERE f.machine_id=m.id AND f.user_id=m.user_id AND f.status='open')::int open_faults,(SELECT COUNT(*) FROM faults f WHERE f.machine_id=m.id AND f.user_id=m.user_id AND f.status='open' AND f.severity='Kritik')::int critical_faults,(SELECT COUNT(*) FROM faults f WHERE f.machine_id=m.id AND f.user_id=m.user_id AND f.created_at>=NOW()-INTERVAL '90 days')::int faults90,(SELECT COUNT(*) FROM maintenance x WHERE x.machine_id=m.id AND x.user_id=m.user_id AND x.status='open' AND x.due_date<CURRENT_DATE)::int overdue_maintenance,(SELECT COUNT(*) FROM maintenance x WHERE x.machine_id=m.id AND x.user_id=m.user_id AND x.status='open' AND x.due_date BETWEEN CURRENT_DATE AND CURRENT_DATE+30)::int due30 FROM machines m WHERE m.user_id=$1`,[u]);const scores=ms.rows.map(healthScore),avgHealth=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0;res.json({machines:m.rows[0].c,maintenance:ma.rows[0].c,faults:f.rows[0].c,overdue:od.rows[0].c,due30:d30.rows[0].c,doneMonth:done.rows[0].c,critical:crit.rows[0].c,lowStock:low.rows[0].c,costMonth:Number(cost.rows[0].t||0),openWorkOrders:wo.rows[0].c,avgHealth,recentMaintenance:rm.rows,recentFaults:rf.rows})});

app.get("/api/admin/summary",auth,admin,async(req,res)=>{const r=await q(`SELECT (SELECT COUNT(*) FROM users)::int users,(SELECT COUNT(*) FROM users WHERE is_active)::int active_users,(SELECT COUNT(*) FROM users WHERE NOT is_active)::int inactive_users,(SELECT COUNT(*) FROM machines)::int machines,(SELECT COUNT(*) FROM maintenance)::int maintenance,(SELECT COUNT(*) FROM faults)::int faults,(SELECT COUNT(*) FROM parts)::int parts,(SELECT COUNT(*) FROM work_orders)::int work_orders,(SELECT COUNT(*) FROM attachments)::int attachments`);res.json(r.rows[0])});
app.get("/api/admin/users",auth,admin,async(req,res)=>{const term=`%${clean(req.query.search)}%`;const r=await q(`SELECT u.id,u.name,u.email,u.role,u.is_active,u.created_at,(SELECT COUNT(*) FROM machines m WHERE m.user_id=u.id)::int machines,(SELECT COUNT(*) FROM maintenance ma WHERE ma.user_id=u.id)::int maintenance,(SELECT COUNT(*) FROM faults f WHERE f.user_id=u.id)::int faults,(SELECT COUNT(*) FROM parts p WHERE p.user_id=u.id)::int parts FROM users u WHERE ($1='%%' OR u.name ILIKE $1 OR u.email ILIKE $1) ORDER BY u.id DESC LIMIT 500`,[term]);res.json(r.rows)});
app.get("/api/admin/users/:id",auth,admin,async(req,res)=>{const u=(await q("SELECT id,name,email,role,is_active,created_at FROM users WHERE id=$1",[req.params.id])).rows[0];if(!u)return res.status(404).json({error:"Kullanıcı bulunamadı"});const [m,ma,f,p]=await Promise.all([q("SELECT * FROM machines WHERE user_id=$1 ORDER BY id DESC LIMIT 50",[u.id]),q("SELECT ma.*,x.name machine_name FROM maintenance ma LEFT JOIN machines x ON x.id=ma.machine_id WHERE ma.user_id=$1 ORDER BY ma.id DESC LIMIT 50",[u.id]),q("SELECT f.*,x.name machine_name FROM faults f LEFT JOIN machines x ON x.id=f.machine_id WHERE f.user_id=$1 ORDER BY f.id DESC LIMIT 50",[u.id]),q("SELECT * FROM parts WHERE user_id=$1 ORDER BY name LIMIT 50",[u.id])]);res.json({user:u,machines:m.rows,maintenance:ma.rows,faults:f.rows,parts:p.rows})});
app.patch("/api/admin/users/:id/active",auth,admin,async(req,res)=>{if(Number(req.params.id)===Number(req.user.id))return res.status(400).json({error:"Kendi admin hesabınızı devre dışı bırakamazsınız"});const r=await q("UPDATE users SET is_active=$1 WHERE id=$2 RETURNING id,name,email,role,is_active",[!!req.body.is_active,req.params.id]);res.json(r.rows[0]||{})});
app.patch("/api/admin/users/:id/role",auth,admin,async(req,res)=>{if(Number(req.params.id)===Number(req.user.id)&&req.body.role!=="admin")return res.status(400).json({error:"Kendi admin rolünüzü kaldıramazsınız"});const role=req.body.role==="admin"?"admin":"user";const r=await q("UPDATE users SET role=$1 WHERE id=$2 RETURNING id,name,email,role,is_active",[role,req.params.id]);res.json(r.rows[0]||{})});
app.delete("/api/admin/users/:id",auth,admin,async(req,res)=>{if(Number(req.params.id)===Number(req.user.id))return res.status(400).json({error:"Kendi admin hesabınızı silemezsiniz"});await q("DELETE FROM users WHERE id=$1",[req.params.id]);res.json({ok:true})});

app.get("/api/health",(req,res)=>res.json({ok:true,version:"14.0.0"}));app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:"Sunucu hatası"})});app.listen(PORT,()=>console.log(`Dijital Makinacı V14 http://localhost:${PORT}`));
