const express=require('express');
const path=require('path');
const cookieParser=require('cookie-parser');
const helmet=require('helmet');
const rateLimit=require('express-rate-limit');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const crypto=require('crypto');
const multer=require('multer');
const QRCode=require('qrcode');
const {Pool}=require('pg');

const app=express();
const PORT=process.env.PORT||3000;
const APP_VERSION=process.env.APP_VERSION||'17.2.0';
const JWT_SECRET=process.env.JWT_SECRET||'DEVELOPMENT_ONLY_CHANGE_ME';
const DATABASE_URL=process.env.DATABASE_URL;
if(!DATABASE_URL){console.error('DATABASE_URL tanımlı değil.');process.exit(1)}
const pool=new Pool({connectionString:DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:1}});

app.set('trust proxy',1);
if(process.env.NODE_ENV==='production'){app.use((req,res,next)=>{const proto=String(req.headers['x-forwarded-proto']||'').split(',')[0].trim();if(req.secure||proto==='https')return next();const host=req.get('host');if(!host)return next();return res.redirect(308,`https://${host}${req.originalUrl}`)});}
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],baseUri:["'self'"],fontSrc:["'self'","data:"],formAction:["'self'"],frameAncestors:["'none'"],imgSrc:["'self'","data:","blob:"],objectSrc:["'none'"],scriptSrc:["'self'","'unsafe-inline'"],scriptSrcAttr:["'unsafe-inline'"],styleSrc:["'self'","'unsafe-inline'"],connectSrc:["'self'"]}}}));
app.use(express.json({limit:'700kb'}));
app.use(cookieParser());
app.use((req,res,next)=>{if(req.path==='/manifest.webmanifest')res.type('application/manifest+json');if(req.path==='/service-worker.js')res.setHeader('Service-Worker-Allowed','/');next()});
// V16.2.1 ROOT-SAFE UI: Frontend files are served directly from repo root.
// This avoids mobile GitHub uploads accidentally placing the new UI outside /public.
function rootUiFile(res,file,type){
  res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, max-age=0');
  res.setHeader('Pragma','no-cache');
  res.setHeader('Expires','0');
  if(type)res.type(type);
  return res.sendFile(path.join(__dirname,file));
}
app.get(['/', '/index.html'],(req,res)=>rootUiFile(res,'v1621-index.html','html'));
app.get('/v1621-app.js',(req,res)=>rootUiFile(res,'v1621-app.js','application/javascript'));
app.get('/v1621-style.css',(req,res)=>rootUiFile(res,'v1621-style.css','text/css'));
app.get('/forgot-password.html',(req,res)=>rootUiFile(res,'v1621-forgot-password.html','html'));
app.get('/reset-password.html',(req,res)=>rootUiFile(res,'v1621-reset-password.html','html'));
app.get('/manifest.webmanifest',(req,res)=>rootUiFile(res,'v1621-manifest.webmanifest','application/manifest+json'));
app.get('/service-worker.js',(req,res)=>{res.setHeader('Service-Worker-Allowed','/');return rootUiFile(res,'v1621-service-worker.js','application/javascript')});
app.get(['/admin','/admin/','/admin.html'],(req,res)=>rootUiFile(res,'admin.html','html'));
app.get('/admin.js',(req,res)=>rootUiFile(res,'admin.js','application/javascript'));
app.get('/admin.css',(req,res)=>rootUiFile(res,'admin.css','text/css'));

app.use(express.static(path.join(__dirname,'public'),{index:false,maxAge:0,etag:true,setHeaders:res=>res.setHeader('Cache-Control','no-store, max-age=0')}));
app.use('/api/auth',rateLimit({windowMs:15*60*1000,max:60,standardHeaders:true,legacyHeaders:false}));

const clean=s=>String(s??'').trim();
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const nil=v=>clean(v)||null;
const emailOk=s=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
const companyRoles=['owner','manager','technician','operator','viewer'];
const roleLabel={owner:'Firma Sahibi',manager:'Yönetici',technician:'Teknisyen',operator:'Operatör',viewer:'Görüntüleyici'};
async function q(text,params=[]){return pool.query(text,params)}
function sign(u){return jwt.sign({id:u.id,email:u.email,name:u.name,role:u.role,platform_admin:!!u.platform_admin},JWT_SECRET,{expiresIn:'7d'})}
function setCookie(res,t){res.cookie('dm_token',t,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:7*24*60*60*1000})}
async function auth(req,res,next){const t=req.cookies.dm_token;if(!t)return res.status(401).json({error:'Giriş gerekli'});try{const token=jwt.verify(t,JWT_SECRET);const u=(await q('SELECT id,name,email,role,is_active,platform_admin FROM users WHERE id=$1',[token.id])).rows[0];if(!u?.is_active){res.clearCookie('dm_token');return res.status(403).json({error:'Hesabınız devre dışı'})}const st=await getSystemSettings();if(st.maintenance_mode===true&&!u.platform_admin)return res.status(503).json({error:'Sistem bakım modunda. Lütfen daha sonra tekrar deneyin.'});req.user=u;next()}catch(e){if(e?.name==='JsonWebTokenError'||e?.name==='TokenExpiredError'){res.clearCookie('dm_token');return res.status(401).json({error:'Oturum geçersiz'})}next(e)}}
async function siteAdmin(req,res,next){try{if(!req.user?.platform_admin)return res.status(403).json({error:'Platform yöneticisi yetkisi gerekli'});next()}catch(e){next(e)}}
function permit(...roles){return(req,res,next)=>{if(req.user?.platform_admin||roles.includes(req.company?.role))return next();return res.status(403).json({error:`Bu işlem için yetkiniz yok (${roleLabel[req.company?.role]||'rol'})`})}}
function healthScore(m){let s=100;if(m.status==='Arızalı')s-=35;else if(m.status==='Bakımda')s-=15;else if(m.status==='Devre dışı')s-=25;if(m.criticality==='Kritik')s-=5;s-=Math.min(24,num(m.open_faults)*6);s-=Math.min(16,num(m.critical_faults)*8);s-=Math.min(21,num(m.overdue_maintenance)*7);s-=Math.min(9,num(m.due30)*3);if(num(m.faults90)>=3)s-=8;if(m.last_maintenance_date){const days=(Date.now()-new Date(m.last_maintenance_date).getTime())/86400000;if(days>180)s-=10}else if(num(m.hours)>250)s-=8;return Math.max(5,Math.min(100,Math.round(s)))}
function slug(s){return clean(s).toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ş/g,'s').replace(/ç/g,'c').replace(/ö/g,'o').replace(/ü/g,'u').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,40)||'firma'}
async function addCols(table,cols){for(const c of cols)await q(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS ${c}`)}
async function uniqueCompanyCode(name){const base=slug(name);for(let i=0;i<20;i++){const code=(base+'-'+Math.random().toString(36).slice(2,7)).slice(0,60);if(!(await q('SELECT 1 FROM companies WHERE code=$1',[code])).rows.length)return code}return base+'-'+Date.now()}
async function createPersonalCompany(user){const name=`${user.name} Atölyesi`,code=await uniqueCompanyCode(name);const c=(await q('INSERT INTO companies(name,code,owner_user_id) VALUES($1,$2,$3) RETURNING *',[name,code,user.id])).rows[0];await q("INSERT INTO company_members(company_id,user_id,role) VALUES($1,$2,'owner') ON CONFLICT(company_id,user_id) DO UPDATE SET role='owner',is_active=true",[c.id,user.id]);await q('UPDATE users SET active_company_id=$1 WHERE id=$2',[c.id,user.id]);return c}
async function ensureCompanyForUser(userId){let u=(await q('SELECT id,name,active_company_id FROM users WHERE id=$1',[userId])).rows[0];if(!u)return null;let m=(await q(`SELECT c.id,c.name,c.code,cm.role FROM company_members cm JOIN companies c ON c.id=cm.company_id WHERE cm.user_id=$1 AND cm.is_active=true AND c.id=$2`,[userId,u.active_company_id||0])).rows[0];if(!m)m=(await q(`SELECT c.id,c.name,c.code,cm.role FROM company_members cm JOIN companies c ON c.id=cm.company_id WHERE cm.user_id=$1 AND cm.is_active=true ORDER BY cm.id LIMIT 1`,[userId])).rows[0];if(!m){const c=await createPersonalCompany(u);m={...c,role:'owner'}}if(Number(u.active_company_id)!==Number(m.id))await q('UPDATE users SET active_company_id=$1 WHERE id=$2',[m.id,userId]);return m}
async function companyCtx(req,res,next){try{const c=await ensureCompanyForUser(req.user.id);if(!c)return res.status(403).json({error:'Aktif firma bulunamadı'});req.company=c;next()}catch(e){next(e)}}
async function ownMachine(id,companyId){return (await q('SELECT id FROM machines WHERE id=$1 AND company_id=$2',[id,companyId])).rows[0]}
async function audit(req,action,entityType,entityId,details={}){try{await q('INSERT INTO audit_log(company_id,user_id,action,entity_type,entity_id,details) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[req.company?.id||null,req.user?.id||null,action,entityType,entityId||null,JSON.stringify(details||{})])}catch(e){console.warn('audit:',e.message)}}
function validDateMonth(v){return /^\d{4}-\d{2}$/.test(String(v||''))?String(v):new Date().toISOString().slice(0,7)}
let settingsCache={at:0,data:{}};
async function getSystemSettings(force=false){if(!force&&Date.now()-settingsCache.at<10000)return settingsCache.data;const rows=(await q('SELECT key,value FROM system_settings')).rows;const data={};for(const r of rows)data[r.key]=r.value;settingsCache={at:Date.now(),data};return data}
async function adminAudit(req,action,targetType,targetId=null,details={}){try{await q('INSERT INTO admin_action_log(admin_user_id,action,target_type,target_id,details,ip,user_agent) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7)',[req.user?.id||null,action,targetType,targetId||null,JSON.stringify(details||{}),String(req.ip||'').slice(0,80),String(req.get?.('user-agent')||'').slice(0,500)])}catch(e){console.warn('admin audit:',e.message)}}
async function loginEvent(req,email,success,userId=null,reason=''){try{await q('INSERT INTO login_events(user_id,email,success,reason,ip,user_agent) VALUES($1,$2,$3,$4,$5,$6)',[userId||null,clean(email).toLowerCase(),!!success,clean(reason).slice(0,160),String(req.ip||'').slice(0,80),String(req.get('user-agent')||'').slice(0,500)])}catch(e){console.warn('login event:',e.message)}}

function resetTokenHash(token){return crypto.createHash('sha256').update(String(token||'')).digest('hex')}
async function sendPasswordResetMail(to,name,resetUrl){
 const key=clean(process.env.RESEND_API_KEY),from=clean(process.env.PASSWORD_RESET_FROM);
 if(!key||!from)return false;
 const body={from,to:[to],subject:'Dijital Makinacı • Şifre yenileme',html:`<div style="font-family:Arial,sans-serif;background:#071015;color:#eef5f3;padding:28px"><div style="max-width:560px;margin:auto;background:#0b171d;border:1px solid #20343d;border-radius:16px;padding:28px"><h2 style="margin:0 0 14px;color:#65ef9b">Şifreni yenile</h2><p>Merhaba ${clean(name)||'kullanıcı'}, Dijital Makinacı hesabın için şifre yenileme isteği aldık.</p><p><a href="${resetUrl}" style="display:inline-block;background:#65ef9b;color:#06110a;text-decoration:none;font-weight:700;padding:12px 18px;border-radius:9px">Yeni şifre oluştur</a></p><p style="color:#91a4ab;font-size:13px">Bu bağlantı 30 dakika geçerlidir ve yalnızca bir kez kullanılabilir. Bu isteği sen yapmadıysan e-postayı yok sayabilirsin.</p></div></div>`};
 const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(body)});
 if(!r.ok){const t=await r.text().catch(()=>'');throw Error(`E-posta servisi ${r.status}: ${t.slice(0,180)}`)}
 return true;
}

async function initDb(){
 await q(`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(200) UNIQUE NOT NULL,password_hash TEXT NOT NULL,role VARCHAR(20) NOT NULL DEFAULT 'user',is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS companies(id BIGSERIAL PRIMARY KEY,name VARCHAR(180) NOT NULL,code VARCHAR(80) UNIQUE NOT NULL,owner_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS company_members(id BIGSERIAL PRIMARY KEY,company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,role VARCHAR(30) NOT NULL DEFAULT 'viewer',is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(company_id,user_id))`);
 await addCols('users',['active_company_id BIGINT']);
 await q(`CREATE TABLE IF NOT EXISTS machines(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name VARCHAR(160) NOT NULL,model VARCHAR(160) DEFAULT '',hours NUMERIC(12,1) DEFAULT 0,criticality VARCHAR(30) DEFAULT 'Normal',serial_no VARCHAR(120) DEFAULT '',note TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols('machines',["company_id BIGINT","manufacturer VARCHAR(160) DEFAULT ''","category VARCHAR(100) DEFAULT ''","location VARCHAR(180) DEFAULT ''","status VARCHAR(30) DEFAULT 'Çalışıyor'","power_kw NUMERIC(10,2) DEFAULT 0","year INTEGER","last_maintenance_date DATE","next_maintenance_date DATE","lubricant VARCHAR(180) DEFAULT ''","bearing_info TEXT DEFAULT ''","belt_info TEXT DEFAULT ''","motor_info TEXT DEFAULT ''"]);
 await q(`CREATE TABLE IF NOT EXISTS maintenance(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,machine_id BIGINT REFERENCES machines(id) ON DELETE CASCADE,task VARCHAR(220) NOT NULL,due_date DATE NOT NULL,priority VARCHAR(30) DEFAULT 'Normal',status VARCHAR(20) DEFAULT 'open',note TEXT DEFAULT '',completed_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols('maintenance',["company_id BIGINT","maintenance_type VARCHAR(50) DEFAULT 'Periyodik'","frequency VARCHAR(80) DEFAULT ''","technician VARCHAR(160) DEFAULT ''","technician_user_id BIGINT","parts_used TEXT DEFAULT ''","cost NUMERIC(12,2) DEFAULT 0","duration_min INTEGER DEFAULT 0","meter_hours NUMERIC(12,1) DEFAULT 0"]);
 await q(`CREATE TABLE IF NOT EXISTS faults(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,machine_id BIGINT REFERENCES machines(id) ON DELETE SET NULL,system VARCHAR(40),symptom VARCHAR(180) NOT NULL,measurements JSONB DEFAULT '{}'::jsonb,note TEXT DEFAULT '',diagnosis TEXT DEFAULT '',status VARCHAR(20) DEFAULT 'open',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols('faults',["company_id BIGINT","severity VARCHAR(30) DEFAULT 'Orta'","root_cause TEXT DEFAULT ''","action_taken TEXT DEFAULT ''","downtime_min INTEGER DEFAULT 0","closed_at TIMESTAMPTZ"]);
 await q(`CREATE TABLE IF NOT EXISTS parts(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name VARCHAR(180) NOT NULL,part_code VARCHAR(120) DEFAULT '',category VARCHAR(80) DEFAULT '',quantity NUMERIC(12,2) DEFAULT 0,min_quantity NUMERIC(12,2) DEFAULT 0,unit VARCHAR(30) DEFAULT 'adet',location VARCHAR(140) DEFAULT '',supplier VARCHAR(180) DEFAULT '',unit_cost NUMERIC(12,2) DEFAULT 0,note TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols('parts',['company_id BIGINT']);
 await q(`CREATE TABLE IF NOT EXISTS favorites(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,article_key VARCHAR(180) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,article_key))`);
 await q(`CREATE TABLE IF NOT EXISTS calc_history(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,tool VARCHAR(120) NOT NULL,input_data JSONB DEFAULT '{}'::jsonb,result TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS work_orders(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,machine_id BIGINT REFERENCES machines(id) ON DELETE SET NULL,title VARCHAR(220) NOT NULL,description TEXT DEFAULT '',priority VARCHAR(30) DEFAULT 'Normal',status VARCHAR(30) DEFAULT 'open',assigned_to VARCHAR(160) DEFAULT '',due_date DATE,started_at TIMESTAMPTZ,completed_at TIMESTAMPTZ,parts_used TEXT DEFAULT '',cost NUMERIC(12,2) DEFAULT 0,downtime_min INTEGER DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols('work_orders',['company_id BIGINT','assigned_user_id BIGINT']);
 await q(`CREATE TABLE IF NOT EXISTS machine_measurements(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,machine_id BIGINT NOT NULL REFERENCES machines(id) ON DELETE CASCADE,temperature NUMERIC(10,2),pressure NUMERIC(10,2),current_amp NUMERIC(10,2),voltage NUMERIC(10,2),vibration NUMERIC(10,3),rpm NUMERIC(12,1),note TEXT DEFAULT '',measured_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols('machine_measurements',['company_id BIGINT']);
 await q(`CREATE TABLE IF NOT EXISTS attachments(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,machine_id BIGINT NOT NULL REFERENCES machines(id) ON DELETE CASCADE,file_name VARCHAR(240) NOT NULL,mime_type VARCHAR(120) NOT NULL,size_bytes INTEGER NOT NULL,file_data BYTEA NOT NULL,caption VARCHAR(240) DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols('attachments',['company_id BIGINT']);
 await q(`CREATE TABLE IF NOT EXISTS audit_log(id BIGSERIAL PRIMARY KEY,company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,action VARCHAR(80) NOT NULL,entity_type VARCHAR(80) NOT NULL,entity_id BIGINT,details JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await addCols('users',["platform_admin BOOLEAN NOT NULL DEFAULT FALSE","last_login_at TIMESTAMPTZ"]);
 await q("UPDATE users SET platform_admin=true WHERE role='admin' AND platform_admin=false");
 await q(`CREATE TABLE IF NOT EXISTS system_settings(key VARCHAR(80) PRIMARY KEY,value JSONB NOT NULL DEFAULT 'null'::jsonb,updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS announcements(id BIGSERIAL PRIMARY KEY,title VARCHAR(220) NOT NULL,body TEXT NOT NULL,level VARCHAR(30) NOT NULL DEFAULT 'info',is_active BOOLEAN NOT NULL DEFAULT TRUE,publish_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),expires_at TIMESTAMPTZ,created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS knowledge_articles(id BIGSERIAL PRIMARY KEY,slug VARCHAR(180) UNIQUE NOT NULL,title VARCHAR(240) NOT NULL,category VARCHAR(100) NOT NULL DEFAULT 'Genel',summary TEXT DEFAULT '',body TEXT NOT NULL DEFAULT '',is_published BOOLEAN NOT NULL DEFAULT TRUE,created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS admin_action_log(id BIGSERIAL PRIMARY KEY,admin_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,action VARCHAR(100) NOT NULL,target_type VARCHAR(100) NOT NULL,target_id BIGINT,details JSONB NOT NULL DEFAULT '{}'::jsonb,ip VARCHAR(80) DEFAULT '',user_agent TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS login_events(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,email VARCHAR(200) DEFAULT '',success BOOLEAN NOT NULL DEFAULT FALSE,reason VARCHAR(160) DEFAULT '',ip VARCHAR(80) DEFAULT '',user_agent TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS support_tickets(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,company_id BIGINT REFERENCES companies(id) ON DELETE SET NULL,subject VARCHAR(220) NOT NULL,message TEXT NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'open',priority VARCHAR(30) NOT NULL DEFAULT 'Normal',admin_note TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE TABLE IF NOT EXISTS password_reset_tokens(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash VARCHAR(64) UNIQUE NOT NULL,expires_at TIMESTAMPTZ NOT NULL,used_at TIMESTAMPTZ,requested_ip VARCHAR(80) DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE INDEX IF NOT EXISTS idx_password_reset_token ON password_reset_tokens(token_hash,expires_at)`);
 await q(`CREATE TABLE IF NOT EXISTS part_movements(id BIGSERIAL PRIMARY KEY,company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,part_id BIGINT NOT NULL REFERENCES parts(id) ON DELETE CASCADE,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,movement_type VARCHAR(12) NOT NULL,quantity NUMERIC(12,2) NOT NULL,previous_qty NUMERIC(12,2) NOT NULL,new_qty NUMERIC(12,2) NOT NULL,note VARCHAR(240) DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
 await q(`CREATE INDEX IF NOT EXISTS idx_part_movements_part ON part_movements(company_id,part_id,created_at DESC)`);
 const defaultSettings={site_name:'Dijital Makinacı',registrations_enabled:true,maintenance_mode:false,support_email:'',allow_file_uploads:true};
 for(const [k,v] of Object.entries(defaultSettings))await q('INSERT INTO system_settings(key,value) VALUES($1,$2::jsonb) ON CONFLICT(key) DO NOTHING',[k,JSON.stringify(v)]);
 settingsCache.at=0;

 const users=(await q('SELECT id,name,active_company_id FROM users ORDER BY id')).rows;
 for(const u of users)await ensureCompanyForUser(u.id);
 const shared=['machines','maintenance','faults','parts','work_orders','machine_measurements','attachments'];
 for(const t of shared)await q(`UPDATE ${t} x SET company_id=u.active_company_id FROM users u WHERE x.user_id=u.id AND x.company_id IS NULL`);
 await q('CREATE INDEX IF NOT EXISTS idx_machines_company ON machines(company_id)');
 await q('CREATE INDEX IF NOT EXISTS idx_maintenance_company_due ON maintenance(company_id,due_date)');
 await q('CREATE INDEX IF NOT EXISTS idx_faults_company_created ON faults(company_id,created_at)');
 await q('CREATE INDEX IF NOT EXISTS idx_work_company_due ON work_orders(company_id,due_date)');
 await q('CREATE INDEX IF NOT EXISTS idx_parts_company ON parts(company_id)');

 const ae=clean(process.env.ADMIN_EMAIL).toLowerCase(),ap=clean(process.env.ADMIN_PASSWORD);
 if(ae&&ap){const f=await q('SELECT id,name FROM users WHERE email=$1',[ae]);if(!f.rows.length){const h=await bcrypt.hash(ap,12);const u=(await q("INSERT INTO users(name,email,password_hash,role,platform_admin) VALUES($1,$2,$3,'admin',true) RETURNING id,name,email,role,platform_admin",[process.env.ADMIN_NAME||'Site Yöneticisi',ae,h])).rows[0];await createPersonalCompany(u)}else{await q("UPDATE users SET role='admin',platform_admin=true WHERE email=$1",[ae]);await ensureCompanyForUser(f.rows[0].id)}}
}

// AUTH
app.post('/api/auth/register',async(req,res,next)=>{try{const st=await getSystemSettings();if(st.registrations_enabled===false)return res.status(403).json({error:'Yeni kullanıcı kaydı geçici olarak kapalı'});if(st.maintenance_mode===true)return res.status(503).json({error:'Sistem bakım modunda'});const name=clean(req.body.name),email=clean(req.body.email).toLowerCase(),password=String(req.body.password||'');if(name.length<2)return res.status(400).json({error:'Ad soyad gerekli'});if(!emailOk(email))return res.status(400).json({error:'Geçerli e-posta gir'});if(password.length<8)return res.status(400).json({error:'Şifre en az 8 karakter olmalı'});const h=await bcrypt.hash(password,12);const u=(await q('INSERT INTO users(name,email,password_hash) VALUES($1,$2,$3) RETURNING id,name,email,role,is_active,platform_admin,created_at',[name,email,h])).rows[0];await createPersonalCompany(u);setCookie(res,sign(u));await loginEvent(req,email,true,u.id,'register');res.json({user:u})}catch(e){if(e.code==='23505')return res.status(409).json({error:'Bu e-posta zaten kayıtlı'});next(e)}});
app.post('/api/auth/login',async(req,res,next)=>{try{const email=clean(req.body.email).toLowerCase(),password=String(req.body.password||'');const u=(await q('SELECT * FROM users WHERE email=$1',[email])).rows[0];if(!u||!(await bcrypt.compare(password,u.password_hash))){await loginEvent(req,email,false,u?.id||null,'invalid_credentials');return res.status(401).json({error:'E-posta veya şifre hatalı'})}if(!u.is_active){await loginEvent(req,email,false,u.id,'inactive_account');return res.status(403).json({error:'Hesabınız devre dışı'})}const st=await getSystemSettings();if(st.maintenance_mode===true&&!u.platform_admin){await loginEvent(req,email,false,u.id,'maintenance_mode');return res.status(503).json({error:'Sistem bakım modunda. Platform yöneticileri giriş yapabilir.'})}await ensureCompanyForUser(u.id);await q('UPDATE users SET last_login_at=NOW() WHERE id=$1',[u.id]);await loginEvent(req,email,true,u.id,'login');setCookie(res,sign(u));res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role,is_active:u.is_active,platform_admin:!!u.platform_admin}})}catch(e){next(e)}});
app.post('/api/auth/logout',(req,res)=>{res.clearCookie('dm_token');res.json({ok:true})});
app.get('/api/auth/me',auth,companyCtx,async(req,res)=>{const u=(await q('SELECT id,name,email,role,is_active,platform_admin,created_at,last_login_at,active_company_id FROM users WHERE id=$1',[req.user.id])).rows[0];if(!u?.is_active)return res.status(403).json({error:'Hesap devre dışı'});res.json({user:{...u,company:req.company,company_role:req.company.role}})});
app.post('/api/auth/forgot-password',async(req,res,next)=>{try{
 const email=clean(req.body.email).toLowerCase();
 const configured=!!(clean(process.env.RESEND_API_KEY)&&clean(process.env.PASSWORD_RESET_FROM));
 if(emailOk(email)){
  const u=(await q('SELECT id,name,email,is_active FROM users WHERE email=$1',[email])).rows[0];
  if(u?.is_active&&configured){
   const raw=crypto.randomBytes(32).toString('hex'),hash=resetTokenHash(raw);
   await q('UPDATE password_reset_tokens SET used_at=NOW() WHERE user_id=$1 AND used_at IS NULL',[u.id]);
   await q("INSERT INTO password_reset_tokens(user_id,token_hash,expires_at,requested_ip) VALUES($1,$2,NOW()+INTERVAL '30 minutes',$3)",[u.id,hash,String(req.ip||'').slice(0,80)]);
   const base=(clean(process.env.PUBLIC_BASE_URL)||`${req.protocol}://${req.get('host')}`).replace(/\/$/,'');
   try{await sendPasswordResetMail(u.email,u.name,`${base}/reset-password.html?token=${encodeURIComponent(raw)}`)}catch(err){console.error('Şifre yenileme e-postası:',err.message)}
  }
 }
 res.json({ok:true,email_enabled:configured,message:configured?'E-posta sistemde kayıtlıysa 30 dakika geçerli şifre yenileme bağlantısı gönderildi.':'Şifre yenileme sayfası hazır; e-posta ile sıfırlama için yönetici RESEND_API_KEY ve PASSWORD_RESET_FROM ayarlarını etkinleştirmeli.'});
}catch(e){next(e)}});
app.get('/api/auth/reset-password/validate',async(req,res,next)=>{try{const hash=resetTokenHash(req.query.token);const r=(await q("SELECT id FROM password_reset_tokens WHERE token_hash=$1 AND used_at IS NULL AND expires_at>NOW()",[hash])).rows[0];res.json({valid:!!r})}catch(e){next(e)}});
app.post('/api/auth/reset-password',async(req,res,next)=>{try{
 const token=String(req.body.token||''),password=String(req.body.password||'');
 if(token.length<32)return res.status(400).json({error:'Şifre yenileme bağlantısı geçersiz'});
 if(password.length<8||password.length>128)return res.status(400).json({error:'Yeni şifre 8–128 karakter olmalı'});
 const hash=resetTokenHash(token),c=await pool.connect();
 try{await c.query('BEGIN');const r=(await c.query("SELECT pr.id,pr.user_id,u.email FROM password_reset_tokens pr JOIN users u ON u.id=pr.user_id WHERE pr.token_hash=$1 AND pr.used_at IS NULL AND pr.expires_at>NOW() FOR UPDATE",[hash])).rows[0];if(!r){await c.query('ROLLBACK');return res.status(400).json({error:'Bu bağlantının süresi dolmuş veya daha önce kullanılmış'})}const ph=await bcrypt.hash(password,12);await c.query('UPDATE users SET password_hash=$1 WHERE id=$2',[ph,r.user_id]);await c.query('UPDATE password_reset_tokens SET used_at=NOW() WHERE user_id=$1 AND used_at IS NULL',[r.user_id]);await c.query('COMMIT');res.clearCookie('dm_token');await loginEvent(req,r.email,true,r.user_id,'password_reset');res.json({ok:true})}catch(e){await c.query('ROLLBACK').catch(()=>{});throw e}finally{c.release()}
}catch(e){next(e)}});
app.post('/api/account/password',auth,async(req,res,next)=>{try{
 const current=String(req.body.current_password||''),nextPassword=String(req.body.new_password||'');
 if(nextPassword.length<8||nextPassword.length>128)return res.status(400).json({error:'Yeni şifre 8–128 karakter olmalı'});
 if(current===nextPassword)return res.status(400).json({error:'Yeni şifre mevcut şifreden farklı olmalı'});
 const u=(await q('SELECT id,email,password_hash FROM users WHERE id=$1',[req.user.id])).rows[0];
 if(!u||!(await bcrypt.compare(current,u.password_hash)))return res.status(401).json({error:'Mevcut şifre yanlış'});
 const ph=await bcrypt.hash(nextPassword,12);await q('UPDATE users SET password_hash=$1 WHERE id=$2',[ph,u.id]);await q('UPDATE password_reset_tokens SET used_at=NOW() WHERE user_id=$1 AND used_at IS NULL',[u.id]);await loginEvent(req,u.email,true,u.id,'password_changed');res.json({ok:true,message:'Şifren başarıyla yenilendi'});
}catch(e){next(e)}});
app.get('/api/public/settings',async(req,res,next)=>{try{const s=await getSystemSettings();res.json({site_name:s.site_name||'Dijital Makinacı',registrations_enabled:s.registrations_enabled!==false,maintenance_mode:s.maintenance_mode===true,support_email:s.support_email||''})}catch(e){next(e)}});
app.get('/api/announcements',auth,async(req,res,next)=>{try{res.json((await q(`SELECT id,title,body,level,publish_at,expires_at FROM announcements WHERE is_active=true AND publish_at<=NOW() AND (expires_at IS NULL OR expires_at>NOW()) ORDER BY id DESC LIMIT 20`)).rows)}catch(e){next(e)}});
app.get('/api/content/articles',auth,async(req,res,next)=>{try{res.json((await q(`SELECT id,slug,title,category,summary,body,updated_at FROM knowledge_articles WHERE is_published=true ORDER BY category,title`)).rows)}catch(e){next(e)}});
app.post('/api/support',auth,companyCtx,async(req,res,next)=>{try{const subject=clean(req.body.subject),message=clean(req.body.message),priority=['Düşük','Normal','Yüksek'].includes(req.body.priority)?req.body.priority:'Normal';if(subject.length<3||message.length<5)return res.status(400).json({error:'Konu ve açıklama gerekli'});const r=(await q('INSERT INTO support_tickets(user_id,company_id,subject,message,priority) VALUES($1,$2,$3,$4,$5) RETURNING id,subject,status,priority,created_at',[req.user.id,req.company.id,subject,message,priority])).rows[0];res.status(201).json(r)}catch(e){next(e)}});

// COMPANY / TEAM
app.get('/api/company',auth,companyCtx,async(req,res)=>{const companies=(await q(`SELECT c.id,c.name,c.code,cm.role,cm.is_active FROM company_members cm JOIN companies c ON c.id=cm.company_id WHERE cm.user_id=$1 AND cm.is_active=true ORDER BY c.name`,[req.user.id])).rows;const members=(await q(`SELECT u.id,u.name,u.email,cm.role,cm.is_active,cm.created_at FROM company_members cm JOIN users u ON u.id=cm.user_id WHERE cm.company_id=$1 ORDER BY CASE cm.role WHEN 'owner' THEN 0 WHEN 'manager' THEN 1 WHEN 'technician' THEN 2 WHEN 'operator' THEN 3 ELSE 4 END,u.name`,[req.company.id])).rows;res.json({active:req.company,companies,members,permissions:{canManageCompany:req.user.role==='admin'||['owner','manager'].includes(req.company.role),canManageRoles:req.user.role==='admin'||req.company.role==='owner',canEditAssets:req.user.role==='admin'||['owner','manager'].includes(req.company.role),canWork:req.user.role==='admin'||['owner','manager','technician'].includes(req.company.role),canOperate:req.user.role==='admin'||['owner','manager','technician','operator'].includes(req.company.role)}})});
app.post('/api/company',auth,async(req,res,next)=>{try{const name=clean(req.body.name);if(name.length<2)return res.status(400).json({error:'Firma adı gerekli'});const code=await uniqueCompanyCode(name);const c=(await q('INSERT INTO companies(name,code,owner_user_id) VALUES($1,$2,$3) RETURNING *',[name,code,req.user.id])).rows[0];await q("INSERT INTO company_members(company_id,user_id,role) VALUES($1,$2,'owner')",[c.id,req.user.id]);await q('UPDATE users SET active_company_id=$1 WHERE id=$2',[c.id,req.user.id]);res.json(c)}catch(e){next(e)}});
app.post('/api/company/switch/:id',auth,async(req,res)=>{const m=(await q(`SELECT c.id,c.name,c.code,cm.role FROM company_members cm JOIN companies c ON c.id=cm.company_id WHERE cm.user_id=$1 AND cm.company_id=$2 AND cm.is_active=true`,[req.user.id,req.params.id])).rows[0];if(!m)return res.status(403).json({error:'Bu firmaya erişiminiz yok'});await q('UPDATE users SET active_company_id=$1 WHERE id=$2',[m.id,req.user.id]);res.json(m)});
app.patch('/api/company',auth,companyCtx,permit('owner','manager'),async(req,res)=>{const name=clean(req.body.name);if(name.length<2)return res.status(400).json({error:'Firma adı gerekli'});const c=(await q('UPDATE companies SET name=$1 WHERE id=$2 RETURNING id,name,code',[name,req.company.id])).rows[0];await audit(req,'update','company',req.company.id,{name});res.json(c)});
app.post('/api/company/members',auth,companyCtx,permit('owner','manager'),async(req,res)=>{const email=clean(req.body.email).toLowerCase(),role=companyRoles.includes(req.body.role)?req.body.role:'viewer';if(role==='owner'&&req.company.role!=='owner'&&req.user.role!=='admin')return res.status(403).json({error:'Sadece firma sahibi yeni sahip atayabilir'});const u=(await q('SELECT id,name,email,is_active FROM users WHERE email=$1',[email])).rows[0];if(!u)return res.status(404).json({error:'Bu e-posta ile kayıtlı kullanıcı yok. Önce siteye kayıt olması gerekir.'});if(!u.is_active)return res.status(400).json({error:'Bu kullanıcı pasif'});await q(`INSERT INTO company_members(company_id,user_id,role,is_active) VALUES($1,$2,$3,true) ON CONFLICT(company_id,user_id) DO UPDATE SET role=EXCLUDED.role,is_active=true`,[req.company.id,u.id,role]);await audit(req,'member_add','company_member',u.id,{email,role});res.json({ok:true,user:u,role})});
app.patch('/api/company/members/:userId',auth,companyCtx,permit('owner'),async(req,res)=>{if(Number(req.params.userId)===Number(req.user.id)&&req.body.role!=='owner')return res.status(400).json({error:'Kendi firma sahibi rolünüzü kaldıramazsınız'});const role=companyRoles.includes(req.body.role)?req.body.role:'viewer';await q('UPDATE company_members SET role=$1,is_active=true WHERE company_id=$2 AND user_id=$3',[role,req.company.id,req.params.userId]);await audit(req,'member_role','company_member',req.params.userId,{role});res.json({ok:true})});
app.delete('/api/company/members/:userId',auth,companyCtx,permit('owner','manager'),async(req,res)=>{if(Number(req.params.userId)===Number(req.user.id))return res.status(400).json({error:'Kendinizi aktif firmadan çıkaramazsınız'});const target=(await q('SELECT role FROM company_members WHERE company_id=$1 AND user_id=$2',[req.company.id,req.params.userId])).rows[0];if(target?.role==='owner'&&req.company.role!=='owner'&&req.user.role!=='admin')return res.status(403).json({error:'Firma sahibi kaldırılamaz'});await q('UPDATE company_members SET is_active=false WHERE company_id=$1 AND user_id=$2',[req.company.id,req.params.userId]);await audit(req,'member_remove','company_member',req.params.userId,{});res.json({ok:true})});
app.get('/api/audit',auth,companyCtx,async(req,res)=>{const limit=Math.min(200,Math.max(10,num(req.query.limit,60)));res.json((await q(`SELECT a.*,u.name user_name FROM audit_log a LEFT JOIN users u ON u.id=a.user_id WHERE a.company_id=$1 ORDER BY a.id DESC LIMIT $2`,[req.company.id,limit])).rows)});

// MACHINES
const machineStats=`(SELECT COUNT(*) FROM faults f WHERE f.machine_id=m.id AND f.company_id=m.company_id AND f.status='open')::int open_faults,(SELECT COUNT(*) FROM faults f WHERE f.machine_id=m.id AND f.company_id=m.company_id AND f.status='open' AND f.severity='Kritik')::int critical_faults,(SELECT COUNT(*) FROM faults f WHERE f.machine_id=m.id AND f.company_id=m.company_id AND f.created_at>=NOW()-INTERVAL '90 days')::int faults90,(SELECT COUNT(*) FROM maintenance x WHERE x.machine_id=m.id AND x.company_id=m.company_id AND x.status='open' AND x.due_date<CURRENT_DATE)::int overdue_maintenance,(SELECT COUNT(*) FROM maintenance x WHERE x.machine_id=m.id AND x.company_id=m.company_id AND x.status='open' AND x.due_date BETWEEN CURRENT_DATE AND CURRENT_DATE+30)::int due30`;
app.get('/api/machines',auth,companyCtx,async(req,res)=>{const r=await q(`SELECT m.*,${machineStats} FROM machines m WHERE m.company_id=$1 ORDER BY m.id DESC`,[req.company.id]);res.json(r.rows.map(x=>({...x,health_score:healthScore(x)})))});
app.get('/api/machines/:id/detail',auth,companyCtx,async(req,res)=>{const m=(await q(`SELECT m.*,${machineStats} FROM machines m WHERE m.id=$1 AND m.company_id=$2`,[req.params.id,req.company.id])).rows[0];if(!m)return res.status(404).json({error:'Makine bulunamadı'});const [ma,f,w,ms,a]=await Promise.all([q('SELECT * FROM maintenance WHERE machine_id=$1 AND company_id=$2 ORDER BY due_date DESC,id DESC LIMIT 80',[m.id,req.company.id]),q('SELECT * FROM faults WHERE machine_id=$1 AND company_id=$2 ORDER BY id DESC LIMIT 80',[m.id,req.company.id]),q('SELECT * FROM work_orders WHERE machine_id=$1 AND company_id=$2 ORDER BY id DESC LIMIT 80',[m.id,req.company.id]),q('SELECT * FROM machine_measurements WHERE machine_id=$1 AND company_id=$2 ORDER BY measured_at DESC LIMIT 120',[m.id,req.company.id]),q('SELECT id,file_name,mime_type,size_bytes,caption,created_at FROM attachments WHERE machine_id=$1 AND company_id=$2 ORDER BY id DESC LIMIT 80',[m.id,req.company.id])]);m.health_score=healthScore(m);res.json({machine:m,maintenance:ma.rows,faults:f.rows,workOrders:w.rows,measurements:ms.rows.reverse(),attachments:a.rows})});
app.post('/api/machines',auth,companyCtx,permit('owner','manager'),async(req,res)=>{const b=req.body;if(!clean(b.name))return res.status(400).json({error:'Makine adı gerekli'});const r=await q(`INSERT INTO machines(user_id,company_id,name,manufacturer,model,category,serial_no,location,status,hours,power_kw,year,criticality,last_maintenance_date,next_maintenance_date,lubricant,bearing_info,belt_info,motor_info,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20) RETURNING *`,[req.user.id,req.company.id,clean(b.name),clean(b.manufacturer),clean(b.model),clean(b.category),clean(b.serial_no),clean(b.location),clean(b.status)||'Çalışıyor',num(b.hours),num(b.power_kw),b.year?parseInt(b.year,10):null,clean(b.criticality)||'Normal',nil(b.last_maintenance_date),nil(b.next_maintenance_date),clean(b.lubricant),clean(b.bearing_info),clean(b.belt_info),clean(b.motor_info),clean(b.note)]);await audit(req,'create','machine',r.rows[0].id,{name:r.rows[0].name});res.json(r.rows[0])});
app.put('/api/machines/:id',auth,companyCtx,permit('owner','manager'),async(req,res)=>{const b=req.body;const r=await q(`UPDATE machines SET name=$1,manufacturer=$2,model=$3,category=$4,serial_no=$5,location=$6,status=$7,hours=$8,power_kw=$9,year=$10,criticality=$11,last_maintenance_date=$12,next_maintenance_date=$13,lubricant=$14,bearing_info=$15,belt_info=$16,motor_info=$17,note=$18 WHERE id=$19 AND company_id=$20 RETURNING *`,[clean(b.name),clean(b.manufacturer),clean(b.model),clean(b.category),clean(b.serial_no),clean(b.location),clean(b.status)||'Çalışıyor',num(b.hours),num(b.power_kw),b.year?parseInt(b.year,10):null,clean(b.criticality)||'Normal',nil(b.last_maintenance_date),nil(b.next_maintenance_date),clean(b.lubricant),clean(b.bearing_info),clean(b.belt_info),clean(b.motor_info),clean(b.note),req.params.id,req.company.id]);if(!r.rows[0])return res.status(404).json({error:'Makine bulunamadı'});await audit(req,'update','machine',req.params.id,{name:r.rows[0].name});res.json(r.rows[0])});
app.delete('/api/machines/:id',auth,companyCtx,permit('owner','manager'),async(req,res)=>{const r=await q('DELETE FROM machines WHERE id=$1 AND company_id=$2 RETURNING id,name',[req.params.id,req.company.id]);if(r.rows[0])await audit(req,'delete','machine',r.rows[0].id,{name:r.rows[0].name});res.json({ok:true})});

// MAINTENANCE
app.get('/api/maintenance',auth,companyCtx,async(req,res)=>res.json((await q(`SELECT m.*,x.name machine_name,u.name technician_member_name FROM maintenance m LEFT JOIN machines x ON x.id=m.machine_id LEFT JOIN users u ON u.id=m.technician_user_id WHERE m.company_id=$1 ORDER BY CASE WHEN m.status='open' THEN 0 ELSE 1 END,m.due_date ASC,m.id DESC`,[req.company.id])).rows));
app.post('/api/maintenance',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{const b=req.body;if(!b.machine_id||!clean(b.task)||!b.due_date)return res.status(400).json({error:'Makine, görev ve tarih gerekli'});if(!(await ownMachine(b.machine_id,req.company.id)))return res.status(403).json({error:'Makine aktif firmaya ait değil'});const r=await q(`INSERT INTO maintenance(user_id,company_id,machine_id,task,due_date,priority,note,maintenance_type,frequency,technician,technician_user_id,parts_used,cost,duration_min,meter_hours) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`,[req.user.id,req.company.id,b.machine_id,clean(b.task),b.due_date,clean(b.priority)||'Normal',clean(b.note),clean(b.maintenance_type)||'Periyodik',clean(b.frequency),clean(b.technician),b.technician_user_id||null,clean(b.parts_used),num(b.cost),Math.round(num(b.duration_min)),num(b.meter_hours)]);await audit(req,'create','maintenance',r.rows[0].id,{task:r.rows[0].task});res.json(r.rows[0])});
app.patch('/api/maintenance/:id/status',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{const st=req.body.status==='done'?'done':'open';const r=await q(`UPDATE maintenance SET status=$1,completed_at=CASE WHEN $1='done' THEN NOW() ELSE NULL END WHERE id=$2 AND company_id=$3 RETURNING *`,[st,req.params.id,req.company.id]);if(!r.rows[0])return res.status(404).json({error:'Kayıt bulunamadı'});await audit(req,st==='done'?'complete':'reopen','maintenance',req.params.id,{task:r.rows[0].task});res.json(r.rows[0])});
app.delete('/api/maintenance/:id',auth,companyCtx,permit('owner','manager'),async(req,res)=>{const r=await q('DELETE FROM maintenance WHERE id=$1 AND company_id=$2 RETURNING id,task',[req.params.id,req.company.id]);if(r.rows[0])await audit(req,'delete','maintenance',r.rows[0].id,{task:r.rows[0].task});res.json({ok:true})});

// FAULTS
app.get('/api/faults',auth,companyCtx,async(req,res)=>res.json((await q(`SELECT f.*,x.name machine_name,u.name created_by_name FROM faults f LEFT JOIN machines x ON x.id=f.machine_id LEFT JOIN users u ON u.id=f.user_id WHERE f.company_id=$1 ORDER BY CASE WHEN f.status='open' THEN 0 ELSE 1 END,f.id DESC LIMIT 400`,[req.company.id])).rows));
app.post('/api/faults',auth,companyCtx,permit('owner','manager','technician','operator'),async(req,res)=>{const b=req.body;if(!clean(b.symptom))return res.status(400).json({error:'Belirti gerekli'});if(b.machine_id&&!(await ownMachine(b.machine_id,req.company.id)))return res.status(403).json({error:'Makine aktif firmaya ait değil'});const r=await q(`INSERT INTO faults(user_id,company_id,machine_id,system,symptom,measurements,note,diagnosis,severity,root_cause,action_taken,downtime_min) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10,$11,$12) RETURNING *`,[req.user.id,req.company.id,b.machine_id||null,clean(b.system),clean(b.symptom),JSON.stringify(b.measurements||{}),clean(b.note),clean(b.diagnosis),clean(b.severity)||'Orta',clean(b.root_cause),clean(b.action_taken),Math.round(num(b.downtime_min))]);await audit(req,'create','fault',r.rows[0].id,{symptom:r.rows[0].symptom,severity:r.rows[0].severity});res.json(r.rows[0])});
app.patch('/api/faults/:id/status',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{const st=req.body.status==='closed'?'closed':'open';const r=await q(`UPDATE faults SET status=$1,root_cause=COALESCE($2,root_cause),action_taken=COALESCE($3,action_taken),downtime_min=COALESCE($4,downtime_min),closed_at=CASE WHEN $1='closed' THEN NOW() ELSE NULL END WHERE id=$5 AND company_id=$6 RETURNING *`,[st,req.body.root_cause??null,req.body.action_taken??null,req.body.downtime_min===undefined?null:Math.round(num(req.body.downtime_min)),req.params.id,req.company.id]);if(!r.rows[0])return res.status(404).json({error:'Arıza kaydı bulunamadı'});await audit(req,st==='closed'?'close':'reopen','fault',req.params.id,{symptom:r.rows[0].symptom});res.json(r.rows[0])});
app.delete('/api/faults/:id',auth,companyCtx,permit('owner','manager'),async(req,res)=>{const r=await q('DELETE FROM faults WHERE id=$1 AND company_id=$2 RETURNING id,symptom',[req.params.id,req.company.id]);if(r.rows[0])await audit(req,'delete','fault',r.rows[0].id,{symptom:r.rows[0].symptom});res.json({ok:true})});

// PARTS
app.get('/api/parts',auth,companyCtx,async(req,res)=>res.json((await q('SELECT * FROM parts WHERE company_id=$1 ORDER BY name',[req.company.id])).rows));
app.get('/api/parts/:id/movements',auth,companyCtx,async(req,res,next)=>{try{res.json((await q(`SELECT pm.*,u.name user_name FROM part_movements pm LEFT JOIN users u ON u.id=pm.user_id WHERE pm.company_id=$1 AND pm.part_id=$2 ORDER BY pm.id DESC LIMIT 80`,[req.company.id,req.params.id])).rows)}catch(e){next(e)}});
app.post('/api/parts/:id/movement',auth,companyCtx,permit('owner','manager','technician'),async(req,res,next)=>{const type=['in','out'].includes(req.body.type)?req.body.type:null,qty=num(req.body.quantity);if(!type)return res.status(400).json({error:'Stok hareket tipi geçersiz'});if(!(qty>0))return res.status(400).json({error:'Miktar 0’dan büyük olmalı'});const c=await pool.connect();try{await c.query('BEGIN');const part=(await c.query('SELECT * FROM parts WHERE id=$1 AND company_id=$2 FOR UPDATE',[req.params.id,req.company.id])).rows[0];if(!part){await c.query('ROLLBACK');return res.status(404).json({error:'Parça bulunamadı'})}const prev=num(part.quantity),nextQty=type==='in'?prev+qty:prev-qty;if(nextQty<0){await c.query('ROLLBACK');return res.status(400).json({error:`Stok yetersiz. Mevcut: ${prev} ${part.unit}`})}const updated=(await c.query('UPDATE parts SET quantity=$1 WHERE id=$2 RETURNING *',[nextQty,part.id])).rows[0];const movement=(await c.query(`INSERT INTO part_movements(company_id,part_id,user_id,movement_type,quantity,previous_qty,new_qty,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[req.company.id,part.id,req.user.id,type,qty,prev,nextQty,clean(req.body.note).slice(0,240)])).rows[0];await c.query('COMMIT');await audit(req,type==='in'?'stock_in':'stock_out','part',part.id,{quantity:qty,previous_qty:prev,new_qty:nextQty});res.json({part:updated,movement})}catch(e){await c.query('ROLLBACK').catch(()=>{});next(e)}finally{c.release()}});
app.post('/api/parts',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{const b=req.body;if(!clean(b.name))return res.status(400).json({error:'Parça adı gerekli'});const r=await q(`INSERT INTO parts(user_id,company_id,name,part_code,category,quantity,min_quantity,unit,location,supplier,unit_cost,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[req.user.id,req.company.id,clean(b.name),clean(b.part_code),clean(b.category),num(b.quantity),num(b.min_quantity),clean(b.unit)||'adet',clean(b.location),clean(b.supplier),num(b.unit_cost),clean(b.note)]);await audit(req,'create','part',r.rows[0].id,{name:r.rows[0].name});res.json(r.rows[0])});
app.put('/api/parts/:id',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{const b=req.body;const r=await q(`UPDATE parts SET name=$1,part_code=$2,category=$3,quantity=$4,min_quantity=$5,unit=$6,location=$7,supplier=$8,unit_cost=$9,note=$10 WHERE id=$11 AND company_id=$12 RETURNING *`,[clean(b.name),clean(b.part_code),clean(b.category),num(b.quantity),num(b.min_quantity),clean(b.unit)||'adet',clean(b.location),clean(b.supplier),num(b.unit_cost),clean(b.note),req.params.id,req.company.id]);if(!r.rows[0])return res.status(404).json({error:'Parça bulunamadı'});await audit(req,'update','part',req.params.id,{name:r.rows[0].name});res.json(r.rows[0])});
app.delete('/api/parts/:id',auth,companyCtx,permit('owner','manager'),async(req,res)=>{await q('DELETE FROM parts WHERE id=$1 AND company_id=$2',[req.params.id,req.company.id]);await audit(req,'delete','part',req.params.id,{});res.json({ok:true})});

// WORK ORDERS
app.get('/api/work-orders',auth,companyCtx,async(req,res)=>res.json((await q(`SELECT w.*,m.name machine_name,u.name assigned_member_name FROM work_orders w LEFT JOIN machines m ON m.id=w.machine_id LEFT JOIN users u ON u.id=w.assigned_user_id WHERE w.company_id=$1 ORDER BY CASE w.status WHEN 'open' THEN 0 WHEN 'in_progress' THEN 1 WHEN 'waiting' THEN 2 ELSE 3 END,w.due_date NULLS LAST,w.id DESC`,[req.company.id])).rows));
app.post('/api/work-orders',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{const b=req.body;if(!clean(b.title))return res.status(400).json({error:'İş emri başlığı gerekli'});if(b.machine_id&&!(await ownMachine(b.machine_id,req.company.id)))return res.status(403).json({error:'Makine aktif firmaya ait değil'});const r=await q(`INSERT INTO work_orders(user_id,company_id,machine_id,title,description,priority,status,assigned_to,assigned_user_id,due_date,parts_used,cost,downtime_min) VALUES($1,$2,$3,$4,$5,$6,'open',$7,$8,$9,$10,$11,$12) RETURNING *`,[req.user.id,req.company.id,b.machine_id||null,clean(b.title),clean(b.description),clean(b.priority)||'Normal',clean(b.assigned_to),b.assigned_user_id||null,nil(b.due_date),clean(b.parts_used),num(b.cost),Math.round(num(b.downtime_min))]);await audit(req,'create','work_order',r.rows[0].id,{title:r.rows[0].title});res.json(r.rows[0])});
app.patch('/api/work-orders/:id',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{const allowed=['open','in_progress','waiting','done'],st=allowed.includes(req.body.status)?req.body.status:'open';const r=await q(`UPDATE work_orders SET status=$1,assigned_to=COALESCE($2,assigned_to),assigned_user_id=COALESCE($3,assigned_user_id),parts_used=COALESCE($4,parts_used),cost=COALESCE($5,cost),downtime_min=COALESCE($6,downtime_min),started_at=CASE WHEN $1='in_progress' AND started_at IS NULL THEN NOW() ELSE started_at END,completed_at=CASE WHEN $1='done' THEN NOW() WHEN $1<>'done' THEN NULL ELSE completed_at END WHERE id=$7 AND company_id=$8 RETURNING *`,[st,req.body.assigned_to??null,req.body.assigned_user_id??null,req.body.parts_used??null,req.body.cost===undefined?null:num(req.body.cost),req.body.downtime_min===undefined?null:Math.round(num(req.body.downtime_min)),req.params.id,req.company.id]);if(!r.rows[0])return res.status(404).json({error:'İş emri bulunamadı'});await audit(req,st==='done'?'complete':'update','work_order',req.params.id,{status:st,title:r.rows[0].title});res.json(r.rows[0])});
app.delete('/api/work-orders/:id',auth,companyCtx,permit('owner','manager'),async(req,res)=>{await q('DELETE FROM work_orders WHERE id=$1 AND company_id=$2',[req.params.id,req.company.id]);await audit(req,'delete','work_order',req.params.id,{});res.json({ok:true})});

// MEASUREMENTS / ATTACHMENTS / QR
app.post('/api/machines/:id/measurements',auth,companyCtx,permit('owner','manager','technician','operator'),async(req,res)=>{if(!(await ownMachine(req.params.id,req.company.id)))return res.status(404).json({error:'Makine bulunamadı'});const b=req.body,r=await q(`INSERT INTO machine_measurements(user_id,company_id,machine_id,temperature,pressure,current_amp,voltage,vibration,rpm,note,measured_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,COALESCE($11::timestamptz,NOW())) RETURNING *`,[req.user.id,req.company.id,req.params.id,b.temperature===''?null:num(b.temperature),b.pressure===''?null:num(b.pressure),b.current_amp===''?null:num(b.current_amp),b.voltage===''?null:num(b.voltage),b.vibration===''?null:num(b.vibration),b.rpm===''?null:num(b.rpm),clean(b.note),nil(b.measured_at)]);await audit(req,'create','measurement',r.rows[0].id,{machine_id:req.params.id});res.json(r.rows[0])});
app.delete('/api/measurements/:id',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{await q('DELETE FROM machine_measurements WHERE id=$1 AND company_id=$2',[req.params.id,req.company.id]);res.json({ok:true})});
const allowedMime=new Set(['image/jpeg','image/png','image/webp','application/pdf','text/plain','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document']);
app.post('/api/machines/:id/attachments',auth,companyCtx,permit('owner','manager','technician','operator'),upload.single('file'),async(req,res)=>{const st=await getSystemSettings();if(st.allow_file_uploads===false)return res.status(403).json({error:'Dosya yükleme platform yöneticisi tarafından kapatıldı'});if(!(await ownMachine(req.params.id,req.company.id)))return res.status(404).json({error:'Makine bulunamadı'});if(!req.file)return res.status(400).json({error:'Dosya seçilmedi'});if(!allowedMime.has(req.file.mimetype))return res.status(415).json({error:'Desteklenmeyen dosya türü'});const r=await q(`INSERT INTO attachments(user_id,company_id,machine_id,file_name,mime_type,size_bytes,file_data,caption) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,file_name,mime_type,size_bytes,caption,created_at`,[req.user.id,req.company.id,req.params.id,clean(req.file.originalname).slice(0,240),req.file.mimetype,req.file.size,req.file.buffer,clean(req.body.caption).slice(0,240)]);await audit(req,'create','attachment',r.rows[0].id,{file_name:r.rows[0].file_name});res.json(r.rows[0])});
app.get('/api/attachments/:id',auth,companyCtx,async(req,res)=>{const a=(await q('SELECT file_name,mime_type,file_data FROM attachments WHERE id=$1 AND company_id=$2',[req.params.id,req.company.id])).rows[0];if(!a)return res.status(404).end();res.setHeader('Content-Type',a.mime_type);res.setHeader('Content-Disposition',`inline; filename*=UTF-8''${encodeURIComponent(a.file_name)}`);res.send(a.file_data)});
app.delete('/api/attachments/:id',auth,companyCtx,permit('owner','manager','technician'),async(req,res)=>{await q('DELETE FROM attachments WHERE id=$1 AND company_id=$2',[req.params.id,req.company.id]);res.json({ok:true})});
app.get('/api/machines/:id/qr',auth,companyCtx,async(req,res)=>{const m=(await q('SELECT id,name FROM machines WHERE id=$1 AND company_id=$2',[req.params.id,req.company.id])).rows[0];if(!m)return res.status(404).json({error:'Makine bulunamadı'});const base=`${req.protocol}://${req.get('host')}`,url=`${base}/?machine=${m.id}`;const svg=await QRCode.toString(url,{type:'svg',margin:1,width:360,errorCorrectionLevel:'M'});res.type('image/svg+xml').send(svg)});

// PERSONAL FAVORITES / CALC HISTORY
app.get('/api/favorites',auth,async(req,res)=>res.json((await q('SELECT article_key FROM favorites WHERE user_id=$1 ORDER BY id DESC',[req.user.id])).rows.map(x=>x.article_key)));
app.post('/api/favorites/toggle',auth,async(req,res)=>{const key=clean(req.body.article_key);if(!key)return res.status(400).json({error:'Makale anahtarı gerekli'});const f=await q('SELECT id FROM favorites WHERE user_id=$1 AND article_key=$2',[req.user.id,key]);if(f.rows.length){await q('DELETE FROM favorites WHERE id=$1',[f.rows[0].id]);return res.json({favorite:false})}await q('INSERT INTO favorites(user_id,article_key) VALUES($1,$2)',[req.user.id,key]);res.json({favorite:true})});
app.get('/api/calc-history',auth,async(req,res)=>res.json((await q('SELECT * FROM calc_history WHERE user_id=$1 ORDER BY id DESC LIMIT 40',[req.user.id])).rows));
app.post('/api/calc-history',auth,async(req,res)=>{const b=req.body;await q('INSERT INTO calc_history(user_id,tool,input_data,result) VALUES($1,$2,$3::jsonb,$4)',[req.user.id,clean(b.tool),JSON.stringify(b.input_data||{}),clean(b.result)]);res.json({ok:true})});

// CALENDAR
app.get('/api/calendar',auth,companyCtx,async(req,res)=>{const month=validDateMonth(req.query.month);const [y,m]=month.split('-').map(Number),start=`${month}-01`,next=m===12?`${y+1}-01-01`:`${y}-${String(m+1).padStart(2,'0')}-01`;const [ma,wo]=await Promise.all([q(`SELECT ma.id,ma.task title,ma.due_date date,ma.status,ma.priority,ma.maintenance_type type,x.name machine_name,'maintenance' kind FROM maintenance ma LEFT JOIN machines x ON x.id=ma.machine_id WHERE ma.company_id=$1 AND ma.due_date >= $2::date AND ma.due_date < $3::date ORDER BY ma.due_date`,[req.company.id,start,next]),q(`SELECT w.id,w.title,w.due_date date,w.status,w.priority,'İş Emri' type,m.name machine_name,'work' kind FROM work_orders w LEFT JOIN machines m ON m.id=w.machine_id WHERE w.company_id=$1 AND w.due_date >= $2::date AND w.due_date < $3::date ORDER BY w.due_date`,[req.company.id,start,next])]);res.json({month,events:[...ma.rows,...wo.rows].sort((a,b)=>String(a.date).localeCompare(String(b.date)))})});

// ADVANCED FAULT ANALYTICS
app.get('/api/analytics/faults',auth,companyCtx,async(req,res)=>{const days=Math.min(730,Math.max(7,Math.round(num(req.query.days,90))));const params=[req.company.id,days];const [sum,systems,severity,recurrent,machinesR,roots,trend]=await Promise.all([
 q(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='open')::int open,COUNT(*) FILTER(WHERE status='closed')::int closed,COALESCE(SUM(downtime_min),0)::int downtime_min,COALESCE(ROUND(AVG(downtime_min) FILTER(WHERE status='closed')),0)::int avg_downtime_min,COALESCE(ROUND(AVG(EXTRACT(EPOCH FROM(closed_at-created_at))/60) FILTER(WHERE closed_at IS NOT NULL)),0)::int mttr_min FROM faults WHERE company_id=$1 AND created_at>=NOW()-make_interval(days=>$2::int)`,params),
 q(`SELECT COALESCE(NULLIF(system,''),'Diğer') label,COUNT(*)::int value FROM faults WHERE company_id=$1 AND created_at>=NOW()-make_interval(days=>$2::int) GROUP BY 1 ORDER BY value DESC LIMIT 12`,params),
 q(`SELECT COALESCE(NULLIF(severity,''),'Orta') label,COUNT(*)::int value FROM faults WHERE company_id=$1 AND created_at>=NOW()-make_interval(days=>$2::int) GROUP BY 1 ORDER BY value DESC`,params),
 q(`SELECT symptom label,COUNT(*)::int value,COALESCE(SUM(downtime_min),0)::int downtime_min FROM faults WHERE company_id=$1 AND created_at>=NOW()-make_interval(days=>$2::int) GROUP BY symptom HAVING COUNT(*)>1 ORDER BY value DESC,downtime_min DESC LIMIT 10`,params),
 q(`SELECT COALESCE(m.name,'Makine seçilmedi') label,COUNT(*)::int value,COALESCE(SUM(f.downtime_min),0)::int downtime_min FROM faults f LEFT JOIN machines m ON m.id=f.machine_id WHERE f.company_id=$1 AND f.created_at>=NOW()-make_interval(days=>$2::int) GROUP BY m.name ORDER BY value DESC,downtime_min DESC LIMIT 10`,params),
 q(`SELECT root_cause label,COUNT(*)::int value FROM faults WHERE company_id=$1 AND created_at>=NOW()-make_interval(days=>$2::int) AND NULLIF(TRIM(root_cause),'') IS NOT NULL GROUP BY root_cause ORDER BY value DESC LIMIT 10`,params),
 q(`SELECT to_char(date_trunc('month',created_at),'YYYY-MM') month,COUNT(*)::int value,COALESCE(SUM(downtime_min),0)::int downtime_min FROM faults WHERE company_id=$1 AND created_at>=NOW()-make_interval(days=>$2::int) GROUP BY 1 ORDER BY 1`,params)
]);res.json({days,summary:sum.rows[0],systems:systems.rows,severity:severity.rows,recurrent:recurrent.rows,machines:machinesR.rows,rootCauses:roots.rows,trend:trend.rows})});

// SERVICE REPORT DATA — frontend turns this into print/PDF view
app.get('/api/reports/maintenance/:id',auth,companyCtx,async(req,res)=>{const r=(await q(`SELECT ma.*,m.name machine_name,m.manufacturer,m.model,m.serial_no,m.location,c.name company_name,u.name created_by_name FROM maintenance ma LEFT JOIN machines m ON m.id=ma.machine_id LEFT JOIN companies c ON c.id=ma.company_id LEFT JOIN users u ON u.id=ma.user_id WHERE ma.id=$1 AND ma.company_id=$2`,[req.params.id,req.company.id])).rows[0];if(!r)return res.status(404).json({error:'Bakım kaydı bulunamadı'});res.json({type:'maintenance',report_no:`SRV-B-${String(r.id).padStart(6,'0')}`,record:r,generated_at:new Date().toISOString(),generated_by:req.user.name})});
app.get('/api/reports/work-order/:id',auth,companyCtx,async(req,res)=>{const r=(await q(`SELECT w.*,m.name machine_name,m.manufacturer,m.model,m.serial_no,m.location,c.name company_name,u.name created_by_name FROM work_orders w LEFT JOIN machines m ON m.id=w.machine_id LEFT JOIN companies c ON c.id=w.company_id LEFT JOIN users u ON u.id=w.user_id WHERE w.id=$1 AND w.company_id=$2`,[req.params.id,req.company.id])).rows[0];if(!r)return res.status(404).json({error:'İş emri bulunamadı'});res.json({type:'work_order',report_no:`SRV-I-${String(r.id).padStart(6,'0')}`,record:r,generated_at:new Date().toISOString(),generated_by:req.user.name})});

// NOTIFICATIONS / DASHBOARD
app.get('/api/notifications',auth,companyCtx,async(req,res)=>{const c=req.company.id;const [ma,f,p,w]=await Promise.all([q(`SELECT ma.id,ma.task title,ma.due_date,x.name machine_name FROM maintenance ma LEFT JOIN machines x ON x.id=ma.machine_id WHERE ma.company_id=$1 AND ma.status='open' AND ma.due_date<=CURRENT_DATE+7 ORDER BY ma.due_date LIMIT 20`,[c]),q(`SELECT f.id,f.symptom title,f.severity,x.name machine_name,f.created_at FROM faults f LEFT JOIN machines x ON x.id=f.machine_id WHERE f.company_id=$1 AND f.status='open' AND f.severity IN ('Yüksek','Kritik') ORDER BY f.id DESC LIMIT 20`,[c]),q(`SELECT id,name title,quantity,min_quantity,unit FROM parts WHERE company_id=$1 AND quantity<=min_quantity ORDER BY quantity-min_quantity LIMIT 20`,[c]),q(`SELECT w.id,w.title,w.due_date,w.priority,m.name machine_name FROM work_orders w LEFT JOIN machines m ON m.id=w.machine_id WHERE w.company_id=$1 AND w.status<>'done' AND (w.due_date IS NULL OR w.due_date<=CURRENT_DATE+7) ORDER BY w.due_date NULLS LAST LIMIT 20`,[c])]);const n=[];ma.rows.forEach(x=>n.push({type:'maintenance',level:new Date(x.due_date)<new Date(new Date().toDateString())?'critical':'warning',title:x.title,detail:`${x.machine_name||'Makine'} • ${x.due_date}`,target:'maintenance'}));f.rows.forEach(x=>n.push({type:'fault',level:x.severity==='Kritik'?'critical':'warning',title:x.title,detail:`${x.machine_name||'Makine'} • ${x.severity}`,target:'diagnosis'}));p.rows.forEach(x=>n.push({type:'stock',level:'warning',title:`Düşük stok: ${x.title}`,detail:`${x.quantity} ${x.unit} / min ${x.min_quantity}`,target:'parts'}));w.rows.forEach(x=>n.push({type:'work',level:x.priority==='Kritik'?'critical':'info',title:x.title,detail:`${x.machine_name||'Makine'}${x.due_date?' • '+x.due_date:''}`,target:'workorders'}));res.json(n.slice(0,50))});
app.get('/api/dashboard',auth,companyCtx,async(req,res)=>{const c=req.company.id;const [m,ma,f,od,d30,done,crit,low,cost,rm,rf,wo]=await Promise.all([q('SELECT COUNT(*)::int c FROM machines WHERE company_id=$1',[c]),q("SELECT COUNT(*)::int c FROM maintenance WHERE company_id=$1 AND status='open'",[c]),q("SELECT COUNT(*)::int c FROM faults WHERE company_id=$1 AND status='open'",[c]),q("SELECT COUNT(*)::int c FROM maintenance WHERE company_id=$1 AND status='open' AND due_date<CURRENT_DATE",[c]),q("SELECT COUNT(*)::int c FROM maintenance WHERE company_id=$1 AND status='open' AND due_date BETWEEN CURRENT_DATE AND CURRENT_DATE+30",[c]),q("SELECT COUNT(*)::int c FROM maintenance WHERE company_id=$1 AND status='done' AND completed_at>=date_trunc('month',NOW())",[c]),q("SELECT COUNT(*)::int c FROM machines WHERE company_id=$1 AND (criticality='Kritik' OR status IN ('Arızalı','Bakımda'))",[c]),q('SELECT COUNT(*)::int c FROM parts WHERE company_id=$1 AND quantity<=min_quantity',[c]),q("SELECT COALESCE(SUM(cost),0)::numeric t FROM maintenance WHERE company_id=$1 AND completed_at>=date_trunc('month',NOW())",[c]),q(`SELECT ma.id,ma.task,ma.due_date,ma.status,ma.priority,x.name machine_name FROM maintenance ma LEFT JOIN machines x ON x.id=ma.machine_id WHERE ma.company_id=$1 ORDER BY ma.created_at DESC LIMIT 6`,[c]),q(`SELECT f.id,f.symptom,f.status,f.severity,f.created_at,x.name machine_name FROM faults f LEFT JOIN machines x ON x.id=f.machine_id WHERE f.company_id=$1 ORDER BY f.created_at DESC LIMIT 6`,[c]),q("SELECT COUNT(*)::int c FROM work_orders WHERE company_id=$1 AND status<>'done'",[c])]);const ms=await q(`SELECT m.*,${machineStats} FROM machines m WHERE m.company_id=$1`,[c]);const scores=ms.rows.map(healthScore),avgHealth=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0;res.json({machines:m.rows[0].c,maintenance:ma.rows[0].c,faults:f.rows[0].c,overdue:od.rows[0].c,due30:d30.rows[0].c,doneMonth:done.rows[0].c,critical:crit.rows[0].c,lowStock:low.rows[0].c,costMonth:Number(cost.rows[0].t||0),openWorkOrders:wo.rows[0].c,avgHealth,recentMaintenance:rm.rows,recentFaults:rf.rows,company:req.company})});

// SITE ADMIN — V16 PLATFORM CONTROL CENTER
app.get('/api/admin/overview',auth,siteAdmin,async(req,res,next)=>{try{const [summary,userTrend,loginTrend,critical,recent]=await Promise.all([
 q(`SELECT (SELECT COUNT(*) FROM users)::int users,(SELECT COUNT(*) FROM users WHERE is_active)::int active_users,(SELECT COUNT(*) FROM users WHERE NOT is_active)::int inactive_users,(SELECT COUNT(*) FROM users WHERE platform_admin)::int platform_admins,(SELECT COUNT(*) FROM users WHERE created_at>=NOW()-INTERVAL '7 days')::int new_users_7d,(SELECT COUNT(*) FROM companies)::int companies,(SELECT COUNT(*) FROM companies WHERE created_at>=NOW()-INTERVAL '7 days')::int new_companies_7d,(SELECT COUNT(*) FROM machines)::int machines,(SELECT COUNT(*) FROM faults WHERE status='open')::int open_faults,(SELECT COUNT(*) FROM faults WHERE status='open' AND severity='Kritik')::int critical_faults,(SELECT COUNT(*) FROM maintenance WHERE status='open' AND due_date<CURRENT_DATE)::int overdue_maintenance,(SELECT COUNT(*) FROM work_orders WHERE status<>'done')::int open_work_orders,(SELECT COUNT(*) FROM parts WHERE quantity<=min_quantity)::int low_stock,(SELECT COALESCE(SUM(size_bytes),0) FROM attachments)::bigint storage_bytes,(SELECT COUNT(*) FROM login_events WHERE success=false AND created_at>=NOW()-INTERVAL '24 hours')::int failed_logins_24h,(SELECT COUNT(*) FROM admin_action_log WHERE created_at>=NOW()-INTERVAL '24 hours')::int admin_actions_24h`),
 q(`SELECT to_char(d,'YYYY-MM-DD') day,COUNT(u.id)::int value FROM generate_series(CURRENT_DATE-29,CURRENT_DATE,'1 day') d LEFT JOIN users u ON u.created_at>=d AND u.created_at<d+INTERVAL '1 day' GROUP BY d ORDER BY d`),
 q(`SELECT to_char(d,'YYYY-MM-DD') day,(COUNT(l.id) FILTER(WHERE l.success))::int success,(COUNT(l.id) FILTER(WHERE NOT l.success))::int failed FROM generate_series(CURRENT_DATE-13,CURRENT_DATE,'1 day') d LEFT JOIN login_events l ON l.created_at>=d AND l.created_at<d+INTERVAL '1 day' GROUP BY d ORDER BY d`),
 q(`SELECT f.id,f.symptom,f.severity,f.created_at,m.name machine_name,c.name company_name FROM faults f LEFT JOIN machines m ON m.id=f.machine_id LEFT JOIN companies c ON c.id=f.company_id WHERE f.status='open' AND f.severity IN ('Kritik','Yüksek') ORDER BY CASE f.severity WHEN 'Kritik' THEN 0 ELSE 1 END,f.created_at DESC LIMIT 12`),
 q(`SELECT l.*,u.name admin_name,u.email admin_email FROM admin_action_log l LEFT JOIN users u ON u.id=l.admin_user_id ORDER BY l.id DESC LIMIT 12`)
]);res.json({summary:summary.rows[0],userTrend:userTrend.rows,loginTrend:loginTrend.rows,critical:critical.rows,recentAdmin:recent.rows})}catch(e){next(e)}});
app.get('/api/admin/summary',auth,siteAdmin,async(req,res,next)=>{try{const r=await q(`SELECT (SELECT COUNT(*) FROM users)::int users,(SELECT COUNT(*) FROM users WHERE is_active)::int active_users,(SELECT COUNT(*) FROM users WHERE NOT is_active)::int inactive_users,(SELECT COUNT(*) FROM companies)::int companies,(SELECT COUNT(*) FROM machines)::int machines,(SELECT COUNT(*) FROM maintenance)::int maintenance,(SELECT COUNT(*) FROM faults)::int faults,(SELECT COUNT(*) FROM parts)::int parts,(SELECT COUNT(*) FROM work_orders)::int work_orders,(SELECT COUNT(*) FROM attachments)::int attachments`);res.json(r.rows[0])}catch(e){next(e)}});
app.get('/api/admin/users',auth,siteAdmin,async(req,res,next)=>{try{const term=`%${clean(req.query.search)}%`,status=clean(req.query.status),pa=clean(req.query.platform_admin);const r=await q(`SELECT u.id,u.name,u.email,u.role,u.platform_admin,u.is_active,u.last_login_at,u.created_at,(SELECT COUNT(*) FROM company_members cm WHERE cm.user_id=u.id AND cm.is_active)::int companies,(SELECT COUNT(*) FROM machines m WHERE m.user_id=u.id)::int machines,(SELECT COUNT(*) FROM faults f WHERE f.user_id=u.id)::int faults FROM users u WHERE ($1='%%' OR u.name ILIKE $1 OR u.email ILIKE $1) AND ($2='' OR ($2='active' AND u.is_active) OR ($2='inactive' AND NOT u.is_active)) AND ($3='' OR ($3='yes' AND u.platform_admin) OR ($3='no' AND NOT u.platform_admin)) ORDER BY u.id DESC LIMIT 500`,[term,status,pa]);res.json(r.rows)}catch(e){next(e)}});
app.get('/api/admin/users/:id',auth,siteAdmin,async(req,res,next)=>{try{const u=(await q('SELECT id,name,email,role,platform_admin,is_active,last_login_at,created_at FROM users WHERE id=$1',[req.params.id])).rows[0];if(!u)return res.status(404).json({error:'Kullanıcı bulunamadı'});const [m,ma,f,p,cs,logins]=await Promise.all([q('SELECT id,name,manufacturer,model,status,created_at FROM machines WHERE user_id=$1 ORDER BY id DESC LIMIT 50',[u.id]),q('SELECT ma.id,ma.task,ma.status,ma.due_date,x.name machine_name FROM maintenance ma LEFT JOIN machines x ON x.id=ma.machine_id WHERE ma.user_id=$1 ORDER BY ma.id DESC LIMIT 30',[u.id]),q('SELECT f.id,f.symptom,f.status,f.severity,f.created_at,x.name machine_name FROM faults f LEFT JOIN machines x ON x.id=f.machine_id WHERE f.user_id=$1 ORDER BY f.id DESC LIMIT 30',[u.id]),q('SELECT id,name,quantity,min_quantity,unit FROM parts WHERE user_id=$1 ORDER BY name LIMIT 30',[u.id]),q(`SELECT c.id,c.name,cm.role FROM company_members cm JOIN companies c ON c.id=cm.company_id WHERE cm.user_id=$1 AND cm.is_active ORDER BY c.name`,[u.id]),q('SELECT success,reason,ip,created_at FROM login_events WHERE user_id=$1 ORDER BY id DESC LIMIT 20',[u.id])]);res.json({user:u,machines:m.rows,maintenance:ma.rows,faults:f.rows,parts:p.rows,companies:cs.rows,logins:logins.rows})}catch(e){next(e)}});
app.patch('/api/admin/users/:id/active',auth,siteAdmin,async(req,res,next)=>{try{if(Number(req.params.id)===Number(req.user.id)&&!req.body.is_active)return res.status(400).json({error:'Kendi platform admin hesabınızı devre dışı bırakamazsınız'});const r=await q('UPDATE users SET is_active=$1 WHERE id=$2 RETURNING id,name,email,platform_admin,is_active',[!!req.body.is_active,req.params.id]);if(!r.rows[0])return res.status(404).json({error:'Kullanıcı bulunamadı'});await adminAudit(req,req.body.is_active?'user_enabled':'user_disabled','user',req.params.id,{email:r.rows[0].email});res.json(r.rows[0])}catch(e){next(e)}});
app.patch('/api/admin/users/:id/platform-admin',auth,siteAdmin,async(req,res,next)=>{try{const on=!!req.body.platform_admin;if(Number(req.params.id)===Number(req.user.id)&&!on)return res.status(400).json({error:'Kendi platform admin yetkinizi kaldıramazsınız'});const r=await q(`UPDATE users SET platform_admin=$1,role=CASE WHEN $1 THEN 'admin' ELSE 'user' END WHERE id=$2 RETURNING id,name,email,role,platform_admin,is_active`,[on,req.params.id]);if(!r.rows[0])return res.status(404).json({error:'Kullanıcı bulunamadı'});await adminAudit(req,on?'platform_admin_granted':'platform_admin_revoked','user',req.params.id,{email:r.rows[0].email});res.json(r.rows[0])}catch(e){next(e)}});
app.patch('/api/admin/users/:id/role',auth,siteAdmin,async(req,res,next)=>{try{const on=req.body.role==='admin';if(Number(req.params.id)===Number(req.user.id)&&!on)return res.status(400).json({error:'Kendi platform admin yetkinizi kaldıramazsınız'});const r=await q(`UPDATE users SET platform_admin=$1,role=CASE WHEN $1 THEN 'admin' ELSE 'user' END WHERE id=$2 RETURNING id,name,email,role,platform_admin,is_active`,[on,req.params.id]);if(r.rows[0])await adminAudit(req,on?'platform_admin_granted':'platform_admin_revoked','user',req.params.id,{email:r.rows[0].email});res.json(r.rows[0]||{})}catch(e){next(e)}});
app.delete('/api/admin/users/:id',auth,siteAdmin,async(req,res,next)=>{try{if(Number(req.params.id)===Number(req.user.id))return res.status(400).json({error:'Kendi platform admin hesabınızı silemezsiniz'});const u=(await q(`SELECT u.email,u.platform_admin,(SELECT COUNT(*) FROM machines WHERE user_id=u.id)::int machines,(SELECT COUNT(*) FROM maintenance WHERE user_id=u.id)::int maintenance,(SELECT COUNT(*) FROM faults WHERE user_id=u.id)::int faults,(SELECT COUNT(*) FROM parts WHERE user_id=u.id)::int parts,(SELECT COUNT(*) FROM companies WHERE owner_user_id=u.id)::int owned_companies FROM users u WHERE u.id=$1`,[req.params.id])).rows[0];if(!u)return res.status(404).json({error:'Kullanıcı bulunamadı'});const deps=num(u.machines)+num(u.maintenance)+num(u.faults)+num(u.parts)+num(u.owned_companies);if(deps>0)return res.status(409).json({error:'Bu kullanıcının operasyon kayıtları veya sahip olduğu firma var. Veri kaybını önlemek için hesabı silmek yerine pasifleştir.'});await q('DELETE FROM users WHERE id=$1',[req.params.id]);await adminAudit(req,'user_deleted','user',req.params.id,{email:u.email,was_platform_admin:u.platform_admin});res.json({ok:true})}catch(e){next(e)}});

app.get('/api/admin/companies',auth,siteAdmin,async(req,res,next)=>{try{const term=`%${clean(req.query.search)}%`;res.json((await q(`SELECT c.id,c.name,c.code,c.created_at,u.name owner_name,u.email owner_email,(SELECT COUNT(*) FROM company_members cm WHERE cm.company_id=c.id AND cm.is_active)::int members,(SELECT COUNT(*) FROM machines m WHERE m.company_id=c.id)::int machines,(SELECT COUNT(*) FROM faults f WHERE f.company_id=c.id AND f.status='open')::int open_faults,(SELECT COUNT(*) FROM maintenance ma WHERE ma.company_id=c.id AND ma.status='open')::int open_maintenance,(SELECT COUNT(*) FROM work_orders w WHERE w.company_id=c.id AND w.status<>'done')::int open_work_orders FROM companies c LEFT JOIN users u ON u.id=c.owner_user_id WHERE ($1='%%' OR c.name ILIKE $1 OR c.code ILIKE $1 OR u.email ILIKE $1) ORDER BY c.id DESC LIMIT 500`,[term])).rows)}catch(e){next(e)}});
app.get('/api/admin/companies/:id',auth,siteAdmin,async(req,res,next)=>{try{const c=(await q(`SELECT c.*,u.name owner_name,u.email owner_email FROM companies c LEFT JOIN users u ON u.id=c.owner_user_id WHERE c.id=$1`,[req.params.id])).rows[0];if(!c)return res.status(404).json({error:'Firma bulunamadı'});const [members,machinesR,faultsR,maintR,workR]=await Promise.all([q(`SELECT u.id,u.name,u.email,cm.role,cm.is_active FROM company_members cm JOIN users u ON u.id=cm.user_id WHERE cm.company_id=$1 ORDER BY cm.id`,[c.id]),q('SELECT id,name,manufacturer,model,status,criticality FROM machines WHERE company_id=$1 ORDER BY id DESC LIMIT 100',[c.id]),q(`SELECT f.id,f.symptom,f.severity,f.status,m.name machine_name,f.created_at FROM faults f LEFT JOIN machines m ON m.id=f.machine_id WHERE f.company_id=$1 ORDER BY f.id DESC LIMIT 50`,[c.id]),q(`SELECT ma.id,ma.task,ma.status,ma.due_date,m.name machine_name FROM maintenance ma LEFT JOIN machines m ON m.id=ma.machine_id WHERE ma.company_id=$1 ORDER BY ma.id DESC LIMIT 50`,[c.id]),q(`SELECT w.id,w.title,w.status,w.priority,w.due_date,m.name machine_name FROM work_orders w LEFT JOIN machines m ON m.id=w.machine_id WHERE w.company_id=$1 ORDER BY w.id DESC LIMIT 50`,[c.id])]);res.json({company:c,members:members.rows,machines:machinesR.rows,faults:faultsR.rows,maintenance:maintR.rows,workOrders:workR.rows})}catch(e){next(e)}});
app.patch('/api/admin/companies/:id',auth,siteAdmin,async(req,res,next)=>{try{const name=clean(req.body.name);if(name.length<2)return res.status(400).json({error:'Firma adı gerekli'});const r=(await q('UPDATE companies SET name=$1 WHERE id=$2 RETURNING id,name,code',[name,req.params.id])).rows[0];if(!r)return res.status(404).json({error:'Firma bulunamadı'});await adminAudit(req,'company_renamed','company',req.params.id,{name});res.json(r)}catch(e){next(e)}});

app.get('/api/admin/machines',auth,siteAdmin,async(req,res,next)=>{try{const term=`%${clean(req.query.search)}%`,status=clean(req.query.status);res.json((await q(`SELECT m.id,m.name,m.manufacturer,m.model,m.serial_no,m.status,m.criticality,m.hours,m.created_at,c.name company_name,u.name created_by,(SELECT COUNT(*) FROM faults f WHERE f.machine_id=m.id AND f.status='open')::int open_faults,(SELECT COUNT(*) FROM maintenance ma WHERE ma.machine_id=m.id AND ma.status='open' AND ma.due_date<CURRENT_DATE)::int overdue FROM machines m LEFT JOIN companies c ON c.id=m.company_id LEFT JOIN users u ON u.id=m.user_id WHERE ($1='%%' OR m.name ILIKE $1 OR m.manufacturer ILIKE $1 OR m.model ILIKE $1 OR m.serial_no ILIKE $1 OR c.name ILIKE $1) AND ($2='' OR m.status=$2) ORDER BY m.id DESC LIMIT 700`,[term,status])).rows)}catch(e){next(e)}});
app.get('/api/admin/faults',auth,siteAdmin,async(req,res,next)=>{try{const term=`%${clean(req.query.search)}%`,status=clean(req.query.status),severity=clean(req.query.severity);res.json((await q(`SELECT f.id,f.symptom,f.system,f.severity,f.status,f.root_cause,f.downtime_min,f.created_at,f.closed_at,m.name machine_name,c.name company_name,u.name created_by FROM faults f LEFT JOIN machines m ON m.id=f.machine_id LEFT JOIN companies c ON c.id=f.company_id LEFT JOIN users u ON u.id=f.user_id WHERE ($1='%%' OR f.symptom ILIKE $1 OR f.system ILIKE $1 OR m.name ILIKE $1 OR c.name ILIKE $1) AND ($2='' OR f.status=$2) AND ($3='' OR f.severity=$3) ORDER BY CASE f.severity WHEN 'Kritik' THEN 0 WHEN 'Yüksek' THEN 1 ELSE 2 END,f.id DESC LIMIT 700`,[term,status,severity])).rows)}catch(e){next(e)}});
app.get('/api/admin/maintenance',auth,siteAdmin,async(req,res,next)=>{try{const term=`%${clean(req.query.search)}%`,status=clean(req.query.status);res.json((await q(`SELECT ma.id,ma.task,ma.maintenance_type,ma.priority,ma.status,ma.due_date,ma.completed_at,ma.cost,ma.duration_min,m.name machine_name,c.name company_name,u.name created_by FROM maintenance ma LEFT JOIN machines m ON m.id=ma.machine_id LEFT JOIN companies c ON c.id=ma.company_id LEFT JOIN users u ON u.id=ma.user_id WHERE ($1='%%' OR ma.task ILIKE $1 OR m.name ILIKE $1 OR c.name ILIKE $1) AND ($2='' OR ma.status=$2) ORDER BY ma.id DESC LIMIT 700`,[term,status])).rows)}catch(e){next(e)}});
app.get('/api/admin/work-orders',auth,siteAdmin,async(req,res,next)=>{try{const term=`%${clean(req.query.search)}%`,status=clean(req.query.status);res.json((await q(`SELECT w.id,w.title,w.priority,w.status,w.assigned_to,w.due_date,w.cost,w.downtime_min,w.created_at,m.name machine_name,c.name company_name,u.name created_by FROM work_orders w LEFT JOIN machines m ON m.id=w.machine_id LEFT JOIN companies c ON c.id=w.company_id LEFT JOIN users u ON u.id=w.user_id WHERE ($1='%%' OR w.title ILIKE $1 OR m.name ILIKE $1 OR c.name ILIKE $1 OR w.assigned_to ILIKE $1) AND ($2='' OR w.status=$2) ORDER BY w.id DESC LIMIT 700`,[term,status])).rows)}catch(e){next(e)}});

app.get('/api/admin/announcements',auth,siteAdmin,async(req,res,next)=>{try{res.json((await q(`SELECT a.*,u.name created_by_name FROM announcements a LEFT JOIN users u ON u.id=a.created_by ORDER BY a.id DESC LIMIT 200`)).rows)}catch(e){next(e)}});
app.post('/api/admin/announcements',auth,siteAdmin,async(req,res,next)=>{try{const title=clean(req.body.title),body=clean(req.body.body),level=['info','warning','critical','success'].includes(req.body.level)?req.body.level:'info';if(title.length<3||body.length<3)return res.status(400).json({error:'Başlık ve duyuru metni gerekli'});const r=(await q(`INSERT INTO announcements(title,body,level,is_active,publish_at,expires_at,created_by) VALUES($1,$2,$3,$4,COALESCE($5::timestamptz,NOW()),$6::timestamptz,$7) RETURNING *`,[title,body,level,req.body.is_active!==false,nil(req.body.publish_at),nil(req.body.expires_at),req.user.id])).rows[0];await adminAudit(req,'announcement_created','announcement',r.id,{title});res.status(201).json(r)}catch(e){next(e)}});
app.patch('/api/admin/announcements/:id',auth,siteAdmin,async(req,res,next)=>{try{const title=clean(req.body.title),body=clean(req.body.body),level=['info','warning','critical','success'].includes(req.body.level)?req.body.level:'info';const r=(await q(`UPDATE announcements SET title=$1,body=$2,level=$3,is_active=$4,publish_at=COALESCE($5::timestamptz,publish_at),expires_at=$6::timestamptz,updated_at=NOW() WHERE id=$7 RETURNING *`,[title,body,level,req.body.is_active!==false,nil(req.body.publish_at),nil(req.body.expires_at),req.params.id])).rows[0];if(!r)return res.status(404).json({error:'Duyuru bulunamadı'});await adminAudit(req,'announcement_updated','announcement',r.id,{title});res.json(r)}catch(e){next(e)}});
app.delete('/api/admin/announcements/:id',auth,siteAdmin,async(req,res,next)=>{try{await q('DELETE FROM announcements WHERE id=$1',[req.params.id]);await adminAudit(req,'announcement_deleted','announcement',req.params.id);res.json({ok:true})}catch(e){next(e)}});

app.get('/api/admin/articles',auth,siteAdmin,async(req,res,next)=>{try{res.json((await q(`SELECT a.*,u.name updated_by_name FROM knowledge_articles a LEFT JOIN users u ON u.id=a.updated_by ORDER BY a.updated_at DESC LIMIT 300`)).rows)}catch(e){next(e)}});
app.post('/api/admin/articles',auth,siteAdmin,async(req,res,next)=>{try{const title=clean(req.body.title),category=clean(req.body.category)||'Genel',summary=clean(req.body.summary),body=clean(req.body.body);if(title.length<3||body.length<5)return res.status(400).json({error:'Başlık ve içerik gerekli'});const base=slug(req.body.slug||title);let articleSlug=base;for(let i=1;(await q('SELECT 1 FROM knowledge_articles WHERE slug=$1',[articleSlug])).rows.length;i++)articleSlug=`${base}-${i+1}`;const r=(await q(`INSERT INTO knowledge_articles(slug,title,category,summary,body,is_published,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$7) RETURNING *`,[articleSlug,title,category,summary,body,req.body.is_published!==false,req.user.id])).rows[0];await adminAudit(req,'article_created','article',r.id,{title,slug:articleSlug});res.status(201).json(r)}catch(e){next(e)}});
app.patch('/api/admin/articles/:id',auth,siteAdmin,async(req,res,next)=>{try{const title=clean(req.body.title),category=clean(req.body.category)||'Genel',summary=clean(req.body.summary),body=clean(req.body.body);const r=(await q(`UPDATE knowledge_articles SET title=$1,category=$2,summary=$3,body=$4,is_published=$5,updated_by=$6,updated_at=NOW() WHERE id=$7 RETURNING *`,[title,category,summary,body,req.body.is_published!==false,req.user.id,req.params.id])).rows[0];if(!r)return res.status(404).json({error:'İçerik bulunamadı'});await adminAudit(req,'article_updated','article',r.id,{title});res.json(r)}catch(e){next(e)}});
app.delete('/api/admin/articles/:id',auth,siteAdmin,async(req,res,next)=>{try{await q('DELETE FROM knowledge_articles WHERE id=$1',[req.params.id]);await adminAudit(req,'article_deleted','article',req.params.id);res.json({ok:true})}catch(e){next(e)}});

app.get('/api/admin/logs',auth,siteAdmin,async(req,res,next)=>{try{const limit=Math.min(500,Math.max(20,num(req.query.limit,150)));res.json((await q(`SELECT l.*,u.name admin_name,u.email admin_email FROM admin_action_log l LEFT JOIN users u ON u.id=l.admin_user_id ORDER BY l.id DESC LIMIT $1`,[limit])).rows)}catch(e){next(e)}});
app.get('/api/admin/security',auth,siteAdmin,async(req,res,next)=>{try{const [stats,events]=await Promise.all([q(`SELECT (COUNT(*) FILTER(WHERE success AND created_at>=NOW()-INTERVAL '24 hours'))::int successful_24h,(COUNT(*) FILTER(WHERE NOT success AND created_at>=NOW()-INTERVAL '24 hours'))::int failed_24h,(COUNT(DISTINCT ip) FILTER(WHERE NOT success AND created_at>=NOW()-INTERVAL '24 hours'))::int failed_ips_24h,(SELECT COUNT(*) FROM users WHERE NOT is_active)::int blocked_accounts FROM login_events`),q(`SELECT l.id,l.email,l.success,l.reason,l.ip,l.user_agent,l.created_at,u.name user_name FROM login_events l LEFT JOIN users u ON u.id=l.user_id ORDER BY l.id DESC LIMIT 250`)]);res.json({stats:stats.rows[0],events:events.rows})}catch(e){next(e)}});
app.get('/api/admin/settings',auth,siteAdmin,async(req,res,next)=>{try{res.json(await getSystemSettings(true))}catch(e){next(e)}});
app.patch('/api/admin/settings',auth,siteAdmin,async(req,res,next)=>{try{const allowed=['site_name','registrations_enabled','maintenance_mode','support_email','allow_file_uploads'];for(const k of allowed)if(Object.prototype.hasOwnProperty.call(req.body,k))await q(`INSERT INTO system_settings(key,value,updated_by,updated_at) VALUES($1,$2::jsonb,$3,NOW()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_by=EXCLUDED.updated_by,updated_at=NOW()`,[k,JSON.stringify(req.body[k]),req.user.id]);settingsCache.at=0;await adminAudit(req,'settings_updated','settings',null,Object.fromEntries(allowed.filter(k=>k in req.body).map(k=>[k,req.body[k]])));res.json(await getSystemSettings(true))}catch(e){next(e)}});
app.get('/api/admin/support',auth,siteAdmin,async(req,res,next)=>{try{res.json((await q(`SELECT t.*,u.name user_name,u.email user_email,c.name company_name FROM support_tickets t LEFT JOIN users u ON u.id=t.user_id LEFT JOIN companies c ON c.id=t.company_id ORDER BY CASE t.status WHEN 'open' THEN 0 WHEN 'in_progress' THEN 1 ELSE 2 END,t.id DESC LIMIT 400`)).rows)}catch(e){next(e)}});
app.patch('/api/admin/support/:id',auth,siteAdmin,async(req,res,next)=>{try{const status=['open','in_progress','closed'].includes(req.body.status)?req.body.status:'open',note=clean(req.body.admin_note);const r=(await q('UPDATE support_tickets SET status=$1,admin_note=$2,updated_at=NOW() WHERE id=$3 RETURNING *',[status,note,req.params.id])).rows[0];if(!r)return res.status(404).json({error:'Destek kaydı bulunamadı'});await adminAudit(req,'support_updated','support',r.id,{status});res.json(r)}catch(e){next(e)}});

app.get('/api/health',(req,res)=>res.json({ok:true,version:APP_VERSION,product:`Dijital Makinacı V${APP_VERSION} Pro CMMS`}));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.use((err,req,res,next)=>{console.error(err);if(err?.code==='LIMIT_FILE_SIZE')return res.status(413).json({error:'Dosya en fazla 5 MB olabilir'});res.status(500).json({error:'Sunucu hatası'})});

initDb().then(()=>app.listen(PORT,()=>console.log(`Dijital Makinacı V${APP_VERSION} http://localhost:${PORT}`))).catch(e=>{console.error('DB init hatası:',e);process.exit(1)});
