'use strict';
const qs=(s,r=document)=>r.querySelector(s);
const escHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const finite=(value,label,{positive=false,allowZero=false}={})=>{const number=Number(value);if(!Number.isFinite(number))throw Error(`${label} geçerli bir sayı olmalı.`);if(positive&&(allowZero?number<0:number<=0))throw Error(`${label} ${allowZero?'negatif olamaz':'0’dan büyük olmalı'}.`);return number};
const calculators={
  'iso-286-tolerans':{title:'ISO 286 Tolerans ve Geçme',intro:'Nominal ölçü ve tolerans bölgesine göre temel delik/mil limitlerini hesaplayın.',fields:[['nominal','Nominal ölçü (mm)','number'],['upper','Üst sapma (µm)','number'],['lower','Alt sapma (µm)','number']],calculate:v=>{const n=finite(v.nominal,'Nominal ölçü',{positive:true}),u=finite(v.upper,'Üst sapma'),l=finite(v.lower,'Alt sapma');if(u<l)throw Error('Üst sapma alt sapmadan küçük olamaz.');return `Üst limit: ${(n+u/1000).toFixed(3)} mm\nAlt limit: ${(n+l/1000).toFixed(3)} mm\nTolerans: ${(u-l).toFixed(1)} µm`}},
  'kilavuz-on-delik':{title:'Metrik / UNC / UNF Kılavuz Ön Delik',intro:'Diş çapı ve adım değerinden pratik ön delik çapını bulun.',fields:[['diameter','Anma çapı (mm)','number'],['pitch','Adım (mm)','number']],calculate:v=>{const d=finite(v.diameter,'Anma çapı',{positive:true}),p=finite(v.pitch,'Adım',{positive:true});if(p>=d)throw Error('Adım, anma çapından küçük olmalı.');return `Önerilen ön delik: ${(d-p).toFixed(2)} mm\nYaklaşık diş yüksekliği: ${(0.6134*p).toFixed(2)} mm`}},
  'cnc-kesme':{title:'CNC Kesme Hızı ve İlerleme',intro:'Takım çapı, kesme hızı, diş sayısı ve diş başı ilerlemeden devri hesaplayın.',fields:[['diameter','Takım çapı (mm)','number'],['speed','Kesme hızı Vc (m/dk)','number'],['teeth','Diş sayısı','number'],['fz','Diş başı ilerleme (mm)','number']],calculate:v=>{const d=finite(v.diameter,'Takım çapı',{positive:true}),vc=finite(v.speed,'Kesme hızı',{positive:true}),z=finite(v.teeth,'Diş sayısı',{positive:true}),fz=finite(v.fz,'Diş başı ilerleme',{positive:true});const rpm=vc*1000/(Math.PI*d),feed=rpm*z*fz;return `Devir: ${Math.round(rpm)} dev/dk\nİlerleme: ${Math.round(feed)} mm/dk`}},
  'rulman-kod':{title:'Rulman Kod Çözücü',intro:'Standart rulman temel kodundan tip ve yaklaşık iç çap bilgisini okuyun.',fields:[['code','Rulman kodu','text']],calculate:v=>{const code=String(v.code||'').trim().toUpperCase();if(!/^[0-9A-Z-]{3,20}$/.test(code))throw Error('Geçerli bir rulman kodu girin.');const match=code.match(/(60|62|63|64|68|69)(\d{2})/),bore=match?(Number(match[2])===0?10:Number(match[2])===1?12:Number(match[2])===2?15:Number(match[2])===3?17:Number(match[2])*5):null;return `Seri: ${match?.[1]||'Özel / doğrulanmalı'}\nİç çap: ${bore?bore+' mm':'Üretici kataloğundan doğrulayın'}\nNot: Sonekler kapak, boşluk ve hassasiyet bilgisini belirtir.`}},
  'hidrolik':{title:'Hidrolik Kuvvet, Debi ve Güç',intro:'Silindir çapı, basınç ve hızdan kuvvet, debi ve hidrolik gücü hesaplayın.',fields:[['diameter','Silindir çapı (mm)','number'],['pressure','Basınç (bar)','number'],['velocity','Piston hızı (mm/s)','number']],calculate:v=>{const d=finite(v.diameter,'Silindir çapı',{positive:true}),p=finite(v.pressure,'Basınç',{positive:true}),speed=finite(v.velocity,'Piston hızı',{positive:true,allowZero:true}),area=Math.PI*d*d/4,force=p*.1*area,flow=area*speed*60/1e6,power=p*flow/600;return `Kuvvet: ${(force/1000).toFixed(2)} kN\nDebi: ${flow.toFixed(2)} L/dk\nHidrolik güç: ${power.toFixed(2)} kW`}}
};
async function loadArticles(){const host=qs('#publicArticles');if(!host)return;try{const r=await fetch('/api/public/articles?limit=6'),rows=await r.json();host.innerHTML=rows.length?rows.map(x=>`<article><small>${escHtml(x.category)}</small><h3>${escHtml(x.title)}</h3><p>${escHtml(x.summary)}</p><a href="/teknik/${encodeURIComponent(x.slug)}">Makaleyi oku →</a></article>`).join(''):'<p class="siteMuted">Yayınlanmış teknik makale bulunmuyor.</p>'}catch{host.innerHTML='<p class="siteMuted">Teknik içerikler şu anda yüklenemiyor.</p>'}}
function initCalculator(){const slug=location.pathname.split('/').filter(Boolean).pop(),config=calculators[slug];if(!qs('#calcFields'))return;if(!config){qs('#calcTitle').textContent='Araç bulunamadı';return}document.title=`${config.title} • Dijital Makinacı`;qs('#calcTitle').textContent=config.title;qs('#calcIntro').textContent=config.intro;qs('#calcFields').innerHTML=config.fields.map(([id,label,type])=>`<label>${escHtml(label)}<input id="calc_${id}" type="${type}" inputmode="${type==='number'?'decimal':'text'}"></label>`).join('');let result='';qs('#calculateBtn').addEventListener('click',()=>{try{const values=Object.fromEntries(config.fields.map(([id])=>[id,qs('#calc_'+id).value]));result=config.calculate(values);qs('#calcResult').textContent=result;qs('#calcResult').classList.remove('error');updateShare(config.title,result)}catch(e){result='';qs('#calcResult').textContent=e.message;qs('#calcResult').classList.add('error')}});qs('#shareResult').addEventListener('click',async()=>{if(!result)return;const data={title:config.title,text:result,url:location.href};if(navigator.share)await navigator.share(data).catch(()=>{});else await navigator.clipboard?.writeText(`${data.title}\n${data.text}\n${data.url}`)});function updateShare(title,text){qs('#whatsappShare').href=`https://wa.me/?text=${encodeURIComponent(title+'\n'+text+'\n'+location.href)}`}}
async function initArticle(){if(!qs('#articleBody'))return;const slug=decodeURIComponent(location.pathname.split('/').filter(Boolean).pop()||'');try{const r=await fetch('/api/public/articles/'+encodeURIComponent(slug)),x=await r.json();if(!r.ok)throw Error(x.error||'Makale bulunamadı');document.title=`${x.title} • Dijital Makinacı`;qs('#articleCategory').textContent=x.category;qs('#articleTitle').textContent=x.title;qs('#articleMeta').textContent=[x.standard,x.source,x.revision_date&&`Revizyon: ${new Date(x.revision_date).toLocaleDateString('tr-TR')}`].filter(Boolean).join(' • ');qs('#articleBody').innerHTML=escHtml(x.body).replace(/\n/g,'<br>')}catch(e){qs('#articleTitle').textContent=e.message;qs('#articleBody').textContent='İçerik görüntülenemiyor.'}}
loadArticles();initCalculator();initArticle();
