INSERT INTO diagnosis_trees(system_key,node_key,parent_key,question,yes_next,no_next,result_text,checks) VALUES
('motor','root',NULL,'Motor kontaktörü çekiyor ve sürücü/termik çıkışında üç faz gerilim var mı?','shaft','supply',NULL,'["LOTO uygula","Faz-faz gerilimlerini ölç","Kontaktör ve termik çıkışını kontrol et"]'),
('motor','supply','root','Kumanda devresinde start komutu ve emniyet zinciri tamam mı?','winding','control',NULL,'["Acil stop ve kapı emniyetlerini kontrol et","Kontaktör bobin gerilimini ölç","PLC çıkışını izle"]'),
('motor','control','supply','Kumanda zinciri/interlock arızası giderilmeden motora enerji verme.',NULL,NULL,'Kumanda veya emniyet zinciri arızası','["Elektrik şemasına göre açık kontağı bul","Yetkin elektrik personeliyle müdahale et"]'),
('motor','winding','supply','Sargı dirençleri dengeli ve gövde izolasyonu uygun mu?','shaft','winding_result',NULL,'["Faz dirençlerini karşılaştır","Uygun cihaz ve prosedürle izolasyon testi yap"]'),
('motor','winding_result','winding','Motor sargısı, bağlantısı veya izolasyonunda arıza olasılığı yüksek.',NULL,NULL,'Motor sargı/izolasyon arızası','["Motoru devreden ayır","Kablo ve terminal köprülerini doğrula","Motor servisine yönlendir"]'),
('motor','shaft','root','Motor mili enerjisiz durumda elle serbest ve takılmadan dönüyor mu?','load','bearing',NULL,'["Enerjiyi izole et","Kaplin veya kayışı güvenle ayır","Mil dönüşünü kontrol et"]'),
('motor','bearing','shaft','Rulman sıcaklığı, ses veya boşluk değeri sınır dışında.',NULL,NULL,'Motor rulmanı veya mekanik sıkışma','["Rulman boşluğu ve sıcaklığını ölç","Yağlamayı doğrula","Kaplin hizasını kontrol et"]'),
('motor','load','shaft','Yüksüz akımlar dengeli ve etiket akımının altında mı?','load_result','phase_result',NULL,'["Üç faz akımını ölç","Etiket değerleriyle karşılaştır","Faz dengesizliğini hesapla"]'),
('motor','load_result','load','Arıza mekanik yük, proses veya yanlış boyutlandırma kaynaklı görünüyor.',NULL,NULL,'Aşırı mekanik yük / proses yükü','["Yükü kademeli uygula","Kaplin hizasını ve tahrik elemanlarını kontrol et"]'),
('motor','phase_result','load','Besleme dengesizliği, bağlantı veya sargı arızası olasılığı yüksek.',NULL,NULL,'Faz dengesizliği / elektriksel motor arızası','["Klemens bağlantılarını sıkılık açısından kontrol et","Besleme gerilimlerini kaynağa kadar izle"]'),

('bearing','root',NULL,'Rulman bölgesinde sıcaklık üretici sınırının üzerinde mi?','lubrication','vibration',NULL,'["Temassız ölçümü temaslı ölçümle doğrula","Ortam ve yük koşullarını kaydet"]'),
('bearing','lubrication','root','Gres/yağ tipi, miktarı ve yağlama aralığı üretici talimatına uygun mu?','alignment','lube_result',NULL,'["Gres uyumluluğunu kontrol et","Aşırı ve yetersiz yağlamayı değerlendir"]'),
('bearing','lube_result','lubrication','Yanlış, kirli, aşırı veya yetersiz yağlama olasılığı yüksek.',NULL,NULL,'Rulman yağlama arızası','["Kontamine yağı güvenli şekilde değiştir","Doğru miktar ve periyodu kayda al"]'),
('bearing','vibration','root','Titreşim spektrumunda rulman arıza frekansı veya darbeli sinyal var mı?','damage','loose',NULL,'["Yatay-dikey-eksenel ölçüm al","Devir ve yükü kaydet","Trend ile karşılaştır"]'),
('bearing','damage','vibration','Rulman yüzey hasarı veya yuvarlanma elemanı arızası olasılığı yüksek.',NULL,NULL,'Rulman iç hasarı','["Planlı duruş oluştur","Mil ve yatak toleransını da kontrol et"]'),
('bearing','loose','vibration','Temel, yatak veya kaplin bağlantılarında gevşeklik/hizasızlık var mı?','alignment','balance',NULL,'["Civata torklarını kontrol et","Yumuşak ayak ve kaplin hizasını ölç"]'),
('bearing','alignment','loose','Hizasızlık, geçme veya eksenel yük problemi olasılığı yüksek.',NULL,NULL,'Rulman hizalama/geçme sorunu','["Mil-yatak geçmesini ölç","Kaplin hizasını düzelt","Eksenel yükü kontrol et"]'),
('bearing','balance','loose','Balans, rezonans veya tahrik kaynaklı titreşim olasılığı yüksek.',NULL,NULL,'Balans / rezonans / tahrik titreşimi','["Balans kontrolü yap","Rezonans ve kayış-kasnak durumunu incele"]'),

('hydraulic','root',NULL,'Pompa çıkışında ayar basıncına ulaşılıyor mu?','actuator','suction',NULL,'["Kalibre manometre kullan","Yağ seviyesi ve sıcaklığını kaydet"]'),
('hydraulic','suction','root','Emiş hattı, filtre ve yağ seviyesi uygun; köpürme/kavitasyon yok mu?','relief','suction_result',NULL,'["Emiş kaçaklarını kontrol et","Filtre fark basıncını ölç","Yağ viskozitesini doğrula"]'),
('hydraulic','suction_result','suction','Emiş kısıtı, hava girişi veya uygunsuz yağ olasılığı yüksek.',NULL,NULL,'Hidrolik emiş/kavitasyon sorunu','["Emiş hattını sızdırmaz yap","Filtreyi duruma göre değiştir"]'),
('hydraulic','relief','suction','Relief valfi ayarı ve dönüş hattı normal mi?','pump','relief_result',NULL,'["Relief üzerinden sürekli dönüşü kontrol et","Üretici basınç sınırını aşma"]'),
('hydraulic','relief_result','relief','Relief valfi açık kalmış, yanlış ayarlı veya kirlenmiş olabilir.',NULL,NULL,'Relief valfi arızası/ayar sorunu','["Valfi temizle ve test et","Yetkili prosedürle yeniden ayarla"]'),
('hydraulic','pump','relief','Pompa debisi yük altında katalog değerine yakın mı?','actuator','pump_result',NULL,'["Debimetre ile ölç","Drenaj debisini ve sıcaklığı izle"]'),
('hydraulic','pump_result','pump','Pompa aşınması veya iç kaçak olasılığı yüksek.',NULL,NULL,'Hidrolik pompa verim kaybı','["Pompa drenajını ölç","Revizyon/değişim iş emri aç"]'),
('hydraulic','actuator','root','Basınç normal olduğu hâlde aktüatör hareketi yavaş veya kaçırıyor mu?','actuator_result','valve_result',NULL,'["Silindir iç kaçak testi yap","Yön/debi valfi komutunu izle"]'),
('hydraulic','actuator_result','actuator','Silindir/motor iç kaçağı veya mekanik yük sorunu olasılığı yüksek.',NULL,NULL,'Hidrolik aktüatör iç kaçağı','["Conta ve yüzeyleri kontrol et","Mekanik sıkışmayı dışla"]'),
('hydraulic','valve_result','actuator','Yön valfi, debi ayarı veya kontrol sinyali incelenmeli.',NULL,NULL,'Hidrolik kontrol valfi sorunu','["Bobin gerilimini ölç","Sürgü kirlenmesini ve debi ayarını kontrol et"]'),

('pneumatic','root',NULL,'Makine girişinde basınç ve debi çalışma sırasında yeterli mi?','valve','supply',NULL,'["Statik ve dinamik basıncı karşılaştır","Ana hat kapasitesini kontrol et"]'),
('pneumatic','supply','root','FRL, regülatör, hortum ve susturucularda kısıt veya su var mı?','leak','supply_result',NULL,'["Filtre fark basıncını kontrol et","Drenajları boşalt","Hortum çapını doğrula"]'),
('pneumatic','supply_result','supply','Hava hazırlama veya besleme hattı yetersiz.',NULL,NULL,'Pnömatik besleme/FRL sorunu','["Filtre elemanını değiştir","Regülatörü güvenli değere ayarla"]'),
('pneumatic','leak','supply','Makine dururken belirgin kaçak veya valf egzozundan sürekli hava var mı?','leak_result','valve',NULL,'["Ultrasonik/sabunlu su kaçak kontrolü yap","Silindir portlarını izole ederek karşılaştır"]'),
('pneumatic','leak_result','leak','Rakor, hortum, valf veya silindir iç kaçağı olasılığı yüksek.',NULL,NULL,'Pnömatik kaçak','["Kaçak noktasını etiketle","Conta/hortum değişim iş emri aç"]'),
('pneumatic','valve','root','Valf bobini komut alıyor ve manuel kumandada aktüatör çalışıyor mu?','cylinder','signal_result',NULL,'["Bobin gerilimini ölç","PLC çıkışını izle","Manuel testi emniyetli yap"]'),
('pneumatic','signal_result','valve','Elektrik kumandası, sensör veya interlock arızası olasılığı yüksek.',NULL,NULL,'Pnömatik valf kumanda sorunu','["I/O durumunu ve sensör beslemesini kontrol et"]'),
('pneumatic','cylinder','valve','Silindir mekanik yükten ayrıldığında düzgün hareket ediyor mu?','load_result','cylinder_result',NULL,'["Debi ayarlarını kontrol et","Mil ve yataklamayı incele"]'),
('pneumatic','load_result','cylinder','Aktüatör değil mekanik yük/sıkışma kaynaklı sorun.',NULL,NULL,'Mekanik yük veya sıkışma','["Kızak, mafsal ve yük hizasını kontrol et"]'),
('pneumatic','cylinder_result','cylinder','Silindir keçesi, yataklaması veya valf debisi arızalı olabilir.',NULL,NULL,'Pnömatik silindir/valf arızası','["Silindir kaçak testini tamamla","Valf debisini doğrula"]'),

('cnc','root',NULL,'Alarm kodu ve alarm anındaki eksen/spindle durumu kaydedildi mi?','mechanical','record_result',NULL,'["Alarm geçmişini dışa aktar","Parametre değiştirmeden önce yedek al"]'),
('cnc','record_result','root','Alarm verisi olmadan kör müdahale yapılmamalı.',NULL,NULL,'CNC alarm verisi eksik','["Alarmı yeniden oluştururken güvenli mesafeyi koru","Kod ve zaman damgasını kaydet"]'),
('cnc','mechanical','root','Enerji izole edildiğinde ilgili eksende mekanik sıkışma veya anormal boşluk var mı?','mechanical_result','feedback',NULL,'["Vida, kızak, rulman ve kaplini kontrol et","Yağlama çevrimini doğrula"]'),
('cnc','mechanical_result','mechanical','Bilyalı vida, kızak, rulman veya yağlama kaynaklı mekanik arıza.',NULL,NULL,'CNC eksen mekanik arızası','["Backlash ölç","Yağlama noktalarını kontrol et","Mekanik iş emri aç"]'),
('cnc','feedback','mechanical','Encoder/feedback kablosu, konnektör ve batarya değerleri uygun mu?','drive','feedback_result',NULL,'["Kablo ekranlamasını kontrol et","Batarya uyarısını ve feedback değerini izle"]'),
('cnc','feedback_result','feedback','Encoder, kablo veya referans geri besleme arızası olasılığı yüksek.',NULL,NULL,'CNC encoder/feedback arızası','["Kabloyu hareket altında test etme","Üretici prosedürüyle encoder kontrolü yap"]'),
('cnc','drive','feedback','Sürücü ready/enable alıyor ve DC bara/besleme normal mi?','interlock','drive_result',NULL,'["Drive alarm kodunu üretici el kitabıyla eşleştir","Besleme ve enable zincirini ölç"]'),
('cnc','drive_result','drive','Servo/spindle sürücüsü veya besleme zinciri arızası.',NULL,NULL,'CNC sürücü/besleme arızası','["Yetkili servis prosedürüne geç","Parametre ve yedekleri koru"]'),
('cnc','interlock','drive','Kapı, yağlama, ayna/takım ve PLC interlock koşulları tamam mı?','program_result','interlock_result',NULL,'["PLC I/O ekranını izle","Emniyet devresini köprüleme"]'),
('cnc','interlock_result','interlock','PLC, sensör veya emniyet interlock zincirinde açık koşul var.',NULL,NULL,'CNC interlock/I-O sorunu','["Eksik koşulu elektrik şemasından izle"]'),
('cnc','program_result','interlock','Mekanik ve donanım koşulları normalse ofset, parametre ve program akışı incelenmeli.',NULL,NULL,'CNC program/ofset/parametre sorunu','["Son değişiklikleri karşılaştır","Yedekten parametre farkı analizi yap"]'),

('electrical','root',NULL,'Panoya doğru gerilim, faz sırası ve koruma elemanları üzerinden enerji geliyor mu?','control','supply_result',NULL,'["LOTO ve ark flaş prosedürünü uygula","Faz-faz/faz-nötr ölçümlerini kaydet"]'),
('electrical','supply_result','root','Ana besleme, sigorta, şalter veya faz kaybı sorunu.',NULL,NULL,'Elektrik besleme arızası','["Kaynağa doğru ölçerek ilerle","Koruma elemanını nedensiz büyütme"]'),
('electrical','control','root','24 VDC/110 VAC kumanda beslemesi ve emniyet rölesi normal mi?','output','control_result',NULL,'["Kumanda güç kaynağını yük altında ölç","Emniyet rölesi tanı kodunu kaydet"]'),
('electrical','control_result','control','Kumanda beslemesi veya emniyet zinciri arızası.',NULL,NULL,'Elektrik kumanda/emniyet arızası','["Açık kontağı şemaya göre bul","Emniyet fonksiyonunu bypass etme"]'),
('electrical','output','control','PLC çıkışı aktifken kontaktör/valf/sürücü girişinde doğru sinyal var mı?','load_result','output_result',NULL,'["PLC ve saha tarafını iki noktadan ölç","Kablo/klemens sürekliliğini doğrula"]'),
('electrical','output_result','output','Çıkış modülü, röle, kablo veya bağlantı arızası.',NULL,NULL,'Elektrik çıkış/kablolama arızası','["Röle kontaklarını ve klemensleri kontrol et"]'),
('electrical','load_result','output','Kumanda doğruysa yük elemanı veya mekanik proses incelenmeli.',NULL,NULL,'Elektrik yük elemanı/proses arızası','["Akım ve sıcaklık ölç","Yükü güvenli şekilde izole ederek karşılaştır"]'),

('gearbox','root',NULL,'Yağ seviyesi, viskozitesi ve görünümü üretici şartına uygun mu?','vibration','oil_result',NULL,'["Doğru duruş koşulunda seviyeyi kontrol et","Yağ numunesinde metal ve su ara"]'),
('gearbox','oil_result','root','Yanlış seviye/viskozite, kirlenme veya yağ kaçağı var.',NULL,NULL,'Redüktör yağlama sorunu','["Havalandırmayı ve keçeleri kontrol et","Doğru yağ ile bakım planla"]'),
('gearbox','vibration','root','Titreşim/akustik ölçümde dişli kavrama frekansı ve yan bantlar anormal mi?','gear_result','bearing',NULL,'["Yük ve devirle birlikte spektrum al","Trendle karşılaştır"]'),
('gearbox','gear_result','vibration','Dişli aşınması, pitting, kırık diş veya yanlış backlash olasılığı.',NULL,NULL,'Redüktör dişli arızası','["Boreskop kontrolü yap","Backlash ve temas izini ölç"]'),
('gearbox','bearing','vibration','Rulman frekansı, sıcaklık veya eksenel boşluk anormal mi?','bearing_result','alignment_result',NULL,'["Rulman ve kaplin noktalarında ölçüm al","Eksenel/radyal boşluğu kontrol et"]'),
('gearbox','bearing_result','bearing','Redüktör rulman arızası olasılığı yüksek.',NULL,NULL,'Redüktör rulman arızası','["Planlı duruş aç","Dişli temasını da kontrol et"]'),
('gearbox','alignment_result','bearing','Kaplin hizası, temel, rezonans veya tahrik yükü incelenmeli.',NULL,NULL,'Redüktör hizalama/tahrik sorunu','["Kaplin hizasını ve yumuşak ayağı ölç","Temel bağlantılarını kontrol et"]')
ON CONFLICT(system_key,node_key) DO UPDATE SET parent_key=EXCLUDED.parent_key,question=EXCLUDED.question,yes_next=EXCLUDED.yes_next,no_next=EXCLUDED.no_next,result_text=EXCLUDED.result_text,checks=EXCLUDED.checks,is_active=true,updated_at=NOW();
