'use strict';

const http=require('http');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const port=Number(process.env.PREVIEW_PORT)||4173;
const guest=process.env.PREVIEW_GUEST==='1';
const {calculatorSeo,seoArticles,articleSummary}=require('../seo-content');
const {renderCalculatorPage,renderArticlePage,renderLibraryPage,renderCalculatorIndexPage}=require('../seo-render');
const types={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.png':'image/png'};
const routeFile=urlPath=>{
  if(urlPath==='/'||urlPath==='/index.html')return 'index.html';
  if(urlPath==='/app'||urlPath.startsWith('/app/'))return 'app.html';
  if(urlPath==='/admin'||urlPath.startsWith('/admin/'))return 'admin.html';
  return decodeURIComponent(urlPath.replace(/^\//,''));
};
const server=http.createServer((req,res)=>{const requestUrl=new URL(req.url,'http://localhost'),pathname=requestUrl.pathname,seoOptions={baseUrl:`http://127.0.0.1:${port}`,nonce:'local-preview'};if(pathname==='/hesaplamalar'||pathname==='/hesaplamalar/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(renderCalculatorIndexPage(seoOptions))}if(pathname.startsWith('/hesaplamalar/')){const config=calculatorSeo[decodeURIComponent(pathname.split('/').pop())];if(!config){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(renderCalculatorPage(config,seoOptions))}if(pathname==='/teknik'||pathname==='/teknik/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(renderLibraryPage(seoArticles,seoOptions))}if(pathname.startsWith('/teknik/')){const article=seoArticles.find(item=>item.slug===decodeURIComponent(pathname.split('/').pop()));if(!article){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(renderArticlePage(article,seoOptions))}if(pathname==='/api/public/articles'){res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify(seoArticles.slice(0,Math.min(50,Math.max(1,Number(requestUrl.searchParams.get('limit'))||20))).map(articleSummary)))}if(pathname==='/api/auth/me'){if(guest){res.writeHead(401,{'Content-Type':'application/json'});return res.end(JSON.stringify({error:'Önizleme misafir modu'}))}res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify({user:{id:1,name:'Önizleme Yöneticisi',email:'preview@localhost',role:'admin',platform_admin:true,email_verified:true,mfa_enabled:true,mfa_verified:true}}))}if(pathname==='/api/admin/overview'){res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify({summary:{users:12,new_users_7d:2,companies:3,new_companies_7d:1,machines:24,critical_faults:1,open_faults:4,overdue_maintenance:2,open_work_orders:7,failed_logins_24h:1,storage_bytes:5242880},userTrend:[],loginTrend:[],critical:[],recentAdmin:[]}))}if(pathname.startsWith('/api/')){res.writeHead(503,{'Content-Type':'application/json'});return res.end(JSON.stringify({error:'Statik önizlemede API devre dışı'}))}const file=routeFile(pathname),target=path.resolve(root,file);if(!target.startsWith(root)||!fs.existsSync(target)||!fs.statSync(target).isFile()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':types[path.extname(target)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(target).pipe(res)});
server.listen(port,'127.0.0.1',()=>console.log(`Önizleme: http://127.0.0.1:${port}`));
